Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2022-08, with the labels that each got.

#3713 03615 token delete precompile
  hedera-node/src/main/java/com/hedera/services/contracts/sources/EvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DeleteWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/DeleteTokenPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/src/main/java/com/hedera/services/txns/token/DeleteLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenDeleteTransitionLogic.java
  hedera-node/src/test/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifierTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DeleteTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenDeleteTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DeleteTokenPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/DeleteTokenContract/DeleteTokenContract.bin
  test-clients/src/main/resource/contract/contracts/DeleteTokenContract/DeleteTokenContract.json
  test-clients/src/main/resource/contract/contracts/DeleteTokenContract/DeleteTokenContract.sol
Labels: enhancement, hts-contracts, CI:UnitTests, token-management precompile (HIP 514)

#3590 Refine INVALID_SIGNATURE codes for SC precompile signing requirements
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractAssociatePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractDissociatePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractWritePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/BurnPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/MintPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/CreatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DynamicGasCostSuite.java
Labels: CI:UnitTests

#3737 Fix tests that fail with INSUFFICIENT_PAYER_BALANCE
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleLongTermSignSpecs.java
Labels: CI:UnitTests

#3724 Generate sidecars for failing top-level contract creates
  hedera-node/src/main/java/com/hedera/services/records/TransactionRecordService.java
  hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/utils/SidecarUtils.java
  hedera-node/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
  hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/utils/SidecarUtilsTest.java
Labels: RSV6, CI:UnitTests

#3739 02449 d vm contract recovery
  test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/FibonacciPlusLoadProvider.java
Labels: CI:UnitTests

#3748 Add PrecompileFunctionSelector enum
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/EventConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/PrecompileFunctionSelector.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ApprovePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/RedirectViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/BurnPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/CreatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DeleteTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/FreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenDefaultFreezeStatusTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenDefaultKycStatusTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenInfoPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GrantKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/IsFrozenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/IsKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/MintPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/PausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/RevokeKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenGetCustomFeesPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnfreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnpausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeNonFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/RedirectViewExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
Labels: CI:UnitTests

#3709 Add sidecar file size limitations
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamFileWriter.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamManager.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamFileWriterTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamManagerTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
Labels: RSV6, CI:UnitTests

#3734 HIP 514: Add token management functions for kyc flow E2E
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
  test-clients/src/main/resource/contract/contracts/GrantRevokeKyc/GrantRevokeKyc.bin
  test-clients/src/main/resource/contract/contracts/GrantRevokeKyc/GrantRevokeKyc.json
  test-clients/src/main/resource/contract/contracts/GrantRevokeKyc/GrantRevokeKyc.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: hts-contracts, CI:UnitTests, token-management precompile (HIP 514)

#3757 Enable record stream 6, contract bytecode, and contract state changes…
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
Labels: CI:UnitTests

#3745 Help to debug node liveness timeout
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/pauses/NodeLivenessTimeout.java
Labels: CI:UnitTests

#3755 E2E Tests for 03623 Update token precompile
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.bin
  test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.json
  test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.sol
Labels: CI:UnitTests, token-management precompile (HIP 514)

#3768 Skip treasury clones in the `0.0.350-399` range
  hedera-node/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/src/main/java/com/hedera/services/config/HederaNumbers.java
  hedera-node/src/main/java/com/hedera/services/context/properties/SerializableSemVers.java
  hedera-node/src/main/java/com/hedera/services/state/initialization/TreasuryCloner.java
  hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/src/test/java/com/hedera/services/context/properties/SerializableSemVersTest.java
  hedera-node/src/test/java/com/hedera/services/state/initialization/TreasuryClonerTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
Labels: CI:UnitTests

#3750 adding accessorFactory in PrecompilePricingUtils
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/AccessorFactory.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/BurnPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/CreatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DeleteTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/FreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenDefaultFreezeStatusTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenDefaultKycStatusTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenInfoPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GrantKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/IsFrozenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/IsKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/MintPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/PausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/RevokeKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenGetCustomFeesPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnfreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnpausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeNonFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtilsTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/AccessorFactoryTest.java
Labels: CI:UnitTests

#3771 Add CI pipelines for release artifact builds
  .github/CODEOWNERS
  .github/workflows/comp-build-release-artifact.yaml
  .github/workflows/comp-compile-application-code.yaml
  .github/workflows/flow-build-application.yaml
  .github/workflows/flow-deploy-release-artifact.yaml
  .github/workflows/flow-pull-request-checks.yaml
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/RepairDashedCommentsFormatterStep.kt
  buildSrc/src/main/kotlin/StripOldLicenseFormatterStep.kt
  buildSrc/src/main/kotlin/Utils.kt
  buildSrc/src/main/kotlin/com.hedera.hashgraph.aggregate-reports.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.benchmark-conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.hedera-conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.shadow-jar.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-java-conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-kotlin-conventions.gradle.kts
  compose-build.sh
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
  hapi-fees/build.gradle.kts
  hapi-utils/build.gradle.kts
  hedera-node/build.gradle.kts
  hedera-node/configuration/update/during-freeze.sh
  hedera-node/configuration/update/immediate.sh
  settings.gradle.kts
  test-clients/build.gradle.kts
Labels: CI:UnitTests

#3778 Remove the Maven definitions from the Hedera Services code
  .mvn/maven.config
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.properties
  Dockerfile
  hapi-fees/pom.xml
  hapi-utils/pom.xml
  hedera-node/build.gradle.kts
  hedera-node/pom.xml
  mvnw
  mvnw.cmd
  pom.xml
  settings.gradle.kts
  test-clients/pom.xml
Labels: CI:UnitTests

#3775 Add dedicated account in wipe e2e tests
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
Labels: CI:UnitTests

#3792 Reset contracts before re-counting them inside `InitializationFlow`
  hedera-node/src/main/java/com/hedera/services/context/init/StoreInitializationFlow.java
  hedera-node/src/main/java/com/hedera/services/state/validation/UsageLimits.java
  hedera-node/src/test/java/com/hedera/services/context/init/StoreInitializationFlowTest.java
  hedera-node/src/test/java/com/hedera/services/state/validation/UsageLimitsTest.java
Labels: CI:UnitTests

#3677 Add contract action traceability
  hedera-node/src/main/java/com/hedera/services/contracts/execution/CallEvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/CreateEvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/HederaMessageCallProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/HederaTracer.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/TransactionProcessingResult.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/ContractActionType.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaOperationTracer.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/SolidityAction.java
  hedera-node/src/main/java/com/hedera/services/records/TransactionRecordService.java
  hedera-node/src/main/java/com/hedera/services/utils/SidecarUtils.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallLocalExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaMessageCallProcessorTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/SolidityActionTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/TransactionProcessingResultTest.java
  hedera-node/src/test/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsageTest.java
  hedera-node/src/test/java/com/hedera/services/queries/contract/ContractCallLocalAnswerTest.java
  hedera-node/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/EvmFnResultTest.java
  hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCallTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCreateTransitionLogicTest.java
Labels: CI:UnitTests

#3796 Add staking metadata to `nodeStakeUpdate` txn body
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/test/java/com/hedera/services/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
Labels: CI:UnitTests

#3803 Localize Gas Calculation
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallCodeOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaDelegateCallOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaStaticCallOperation.java
Labels: CI:UnitTests

#3798 Fix NPE when creating approve for all synth transaction
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
Labels: CI:UnitTests

#3780 [virtual_nfts] [1] Add configurable bootstrap property "tokens.nfts.useVirtualMerkle"
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
Labels: virtualized nfts, CI:UnitTests

#3557 Add all contract-related E2E tests to GitHub Actions
  test-clients/src/itest/java/ParallelIntegrationTests.java
  test-clients/src/itest/java/SequentialIntegrationTests.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
  test-clients/src/main/resource/contract/contracts/TokenCreateContract/FeeHelper.sol
  test-clients/src/main/resource/contract/contracts/TokenCreateContract/KeyHelper.sol
  test-clients/src/main/resource/contract/contracts/TokenCreateContract/TokenCreateContract.bin
  test-clients/src/main/resource/contract/contracts/TokenCreateContract/TokenCreateContract.json
  test-clients/src/main/resource/contract/contracts/TokenCreateContract/TokenCreateContract.sol
  test-clients/src/test/java/EndToEndPackageRunner.java
Labels: CI:UnitTests

#3761 feat: add implementation for token checks view precompile functions
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/GetTokenTypePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/IsTokenPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenPrecompileReadOperationsTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
Labels: CI:UnitTests, token-management precompile (HIP 514)

#3787 Add more GrantRevokeKycSuite test cases
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
Labels: CI:UnitTests, token-management precompile (HIP 514)

#3820 Add delay for reconnect correctness test
  test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateDuplicateTransactionAfterReconnect.java
Labels: CI:UnitTests

#3773 03722 e2e
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hapi-utils/src/test/java/com/hedera/services/contracts/ParsingConstantsTest.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenAndTypeCheckSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
  test-clients/src/main/resource/contract/contracts/TokenAndTypeCheck/TokenAndTypeCheck.bin
  test-clients/src/main/resource/contract/contracts/TokenAndTypeCheck/TokenAndTypeCheck.sol
Labels: CI:UnitTests, token-management precompile (HIP 514)

#3810 Added missing freeze and pause test cases
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
Labels: CI:UnitTests, token-management precompile (HIP 514)

#3784 [virtual_nfts] [2] Add an EntityId.fromNum static factory method
  hedera-node/src/main/java/com/hedera/services/state/submerkle/EntityId.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/EntityIdTest.java
Labels: virtualized nfts, CI:UnitTests

#3825 Upgrade Besu to 22.7.1
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallCodeOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaDelegateCallOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaStaticCallOperation.java
  settings.gradle.kts
Labels: CI:UnitTests, EVM, Smart Contract

#3818 Charge storage fee to auto-renewal fees
  hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java
  hapi-fees/src/main/java/com/hedera/services/usage/contract/ExtantContractContext.java
  hapi-fees/src/test/java/com/hedera/services/usage/contract/ExtantContractContextTest.java
  hedera-node/configuration/mainnet/upgrade/feeSchedules.json
  hedera-node/configuration/testnet/upgrade/feeSchedules.json
  hedera-node/src/main/java/com/hedera/services/fees/calculation/AutoRenewCalcs.java
  hedera-node/src/main/java/com/hedera/services/fees/calculation/FeeCalcUtils.java
  hedera-node/src/main/resources/feeSchedules.json
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/fees/calculation/AutoRenewCalcsTest.java
  hedera-node/src/test/java/com/hedera/services/fees/calculation/FeeCalcUtilsTest.java
  hedera-node/src/test/resources/fees/feeSchedules.json
  test-clients/src/main/resource/FeeSchedule.json
Labels: CI:UnitTests

#3833 Initial changes for refactoring auto renewal
  hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java
  hedera-node/src/main/java/com/hedera/services/ServicesApp.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryModule.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/classification/ClassificationResult.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/classification/ClassificationWork.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/classification/EntityLookup.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/RemovalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/RemovalWork.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalProcess.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalWork.java
  hedera-node/src/test/java/com/hedera/services/config/MockGlobalDynamicProps.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/classification/ClassificationWorkTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/AccountGCTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/RemovalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalProcessTest.java
Labels: CI:UnitTests

#3785 [virtual_nfts] [3] Adds key and value types and serializers needed for storing NFTs in VirtualMerkle.
  hedera-node/src/main/java/com/hedera/services/state/virtual/UniqueTokenKey.java
  hedera-node/src/main/java/com/hedera/services/state/virtual/UniqueTokenKeySerializer.java
  hedera-node/src/main/java/com/hedera/services/state/virtual/UniqueTokenKeySupplier.java
  hedera-node/src/main/java/com/hedera/services/state/virtual/UniqueTokenValue.java
  hedera-node/src/main/java/com/hedera/services/state/virtual/UniqueTokenValueSupplier.java
  hedera-node/src/test/java/com/hedera/services/state/virtual/UniqueTokenKeySerializerTest.java
  hedera-node/src/test/java/com/hedera/services/state/virtual/UniqueTokenKeySupplierTest.java
  hedera-node/src/test/java/com/hedera/services/state/virtual/UniqueTokenKeyTest.java
  hedera-node/src/test/java/com/hedera/services/state/virtual/UniqueTokenValueSupplierTest.java
  hedera-node/src/test/java/com/hedera/services/state/virtual/UniqueTokenValueTest.java
  hedera-node/src/test/java/com/hedera/services/utils/subjects/UniqueTokenValueSubject.java
  settings.gradle.kts
Labels: CI:UnitTests

#3738 03623 update token info precompile
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/exceptions/ValidationUtils.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/TokenUpdateLogic.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/GetTokenExpiryInfoWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/KeyValueWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/TokenCreateWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/TokenKeyWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/TokenUpdateExpiryInfoWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/TokenUpdateWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/GetTokenExpiryInfoPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenUpdatePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/UpdateTokenExpiryInfoPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenUpdateTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/util/TokenUpdateValidator.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/exceptions/ValidationUtilsTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/CreatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenExpiryInfoPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenPrecompileReadOperationsTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenUpdateLogicTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenUpdatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UpdateTokenExpiryInfoPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/TokenCreateWrapperTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenExpiryInfoSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
  test-clients/src/main/resource/contract/contracts/TokenExpiryContract/TokenExpiryContract.bin
  test-clients/src/main/resource/contract/contracts/TokenExpiryContract/TokenExpiryContract.json
  test-clients/src/main/resource/contract/contracts/TokenExpiryContract/TokenExpiryContract.sol
  test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.bin
  test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.json
  test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: P2, CI:UnitTests

#3835 3832 add call operation type to hedera tracer
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/CallOperationType.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/SolidityAction.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/SolidityActionTest.java
  hedera-node/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
Labels: CI:UnitTests, Hedera Smart Contract Service

#3831 Add alias configuration design doc template
  docs/design/alias-configuration.md
  docs/design/images/lazy-account-create.png
Labels: CI:UnitTests

#3852 Assemble before Run
  hedera-node/build.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#3776 Infrastructure needed for traceability testing
  hapi-utils/src/main/java/com/hedera/services/recordstreaming/RecordStreamingUtils.java
  hapi-utils/src/test/java/com/hedera/services/recordstreaming/RecordStreamingUtilsTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamFileWriterTest.java
  test-clients/src/itest/java/IntegrationTestBase.java
  test-clients/src/itest/java/SequentialIntegrationTests.java
  test-clients/src/itest/resources/network/config/bootstrap.properties
  test-clients/src/main/java/com/hedera/services/bdd/junit/HederaContainer.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/HapiApiSpec.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/ExpectedSidecar.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/MismatchedSidecar.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java
  test-clients/src/main/resource/spec-default.properties
  test-clients/src/test/java/EndToEndPackageRunner.java
Labels: CI:UnitTests

#3866 Disable the per commit CircleCI based JRS workflow
  .circleci/config.yml
Labels: P1, Improvement, CI:UnitTests, Tech Debt Reduced

#3772 feat: added E2E tests for scheduled crypto approve allowance transact…
  hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  test-clients/src/itest/resources/network/config/bootstrap.properties
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleUtils.java
  test-clients/src/main/resource/bootstrap.properties
  test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests

#3874 Update the release artifact pipeline to use the newest version of deterministic-zip
  .github/workflows/comp-build-release-artifact.yaml
Labels: CI:UnitTests

#3855 Ensure release pipeline replaces underscores in the branch name with periods
  .github/workflows/comp-build-release-artifact.yaml
Labels: Bug, CI:UnitTests, Escape, P0

#3841 Trim leading zeros from migration state changes
  hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
Labels: CI:UnitTests

#3860 Fix `NullPointerException` in `HederaTracer` on obtaining call operation type
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/SolidityAction.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/SolidityActionTest.java
  hedera-node/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
  test-clients/src/itest/resources/network/config/bootstrap.properties
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/ContractTraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java
Labels: Bug, CI:UnitTests, Escape, CI:FullStackTests, CI:FinalChecks

#3837 Make `BucketThrottle` generic and introduce `ExpiryThrottle`
  .gitignore
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/HapiThrottleUtils.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleDefinitions.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleGroup.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/HapiThrottleUtilsTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucketTest.java
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/files/HybridResouceLoader.java
  hedera-node/src/main/java/com/hedera/services/files/sysfiles/ConfigCallbacks.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/EntityAutoRenewal.java
  hedera-node/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
  hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
  hedera-node/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java
  hedera-node/src/main/java/com/hedera/services/throttling/ExpiryThrottle.java
  hedera-node/src/main/java/com/hedera/services/throttling/ExpiryThrottlePojo.java
  hedera-node/src/main/java/com/hedera/services/throttling/MapAccessType.java
  hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/main/resources/expiry-throttle.json
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/files/HybridResouceLoaderTest.java
  hedera-node/src/test/java/com/hedera/services/files/sysfiles/ConfigCallbacksTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/EntityAutoRenewalTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextSerdeTest.java
  hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleNetworkContextTest.java
  hedera-node/src/test/java/com/hedera/services/throttling/ExpiryThrottleTest.java
  hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
  hedera-node/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/src/test/java/com/hedera/test/utils/SeededPropertySource.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn0.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn1.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn10.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn11.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn12.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn13.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn14.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn2.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn3.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn4.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn5.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn6.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn7.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn8.hex
  hedera-node/src/test/resources/serdes/MerkleNetworkContext-v10-sn9.hex
  hedera-node/src/test/resources/testfiles/expiry-throttle.json
Labels: CI:UnitTests
