Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2022-07, with the labels that each got.

#3607 Improve and correct ABI names
  hedera-node/src/main/java/com/hedera/services/exceptions/InvalidTransactionException.java
  hedera-node/src/main/java/com/hedera/services/exceptions/ValidationUtils.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ApprovePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/RedirectViewExecutor.java
  hedera-node/src/test/java/com/hedera/services/exceptions/InvalidTransactionExceptionTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/RedirectViewExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/txns/crypto/validators/DeleteAllowanceChecksTest.java
Labels: hts-contracts

#3650 Apply Spotless Formatting - Part 6
  hapi-utils/src/main/java/com/hedera/services/sysfiles/serdes/FeesJsonToProtoSerde.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/validation/ExpectedCustomThrottles.java
Labels: CI:UnitTests

#3652 Apply Spotless Formatting - Part 7
  hedera-node/src/test/java/com/hedera/services/ledger/interceptors/UniqueTokensCommitInterceptorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/persistence/Account.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryUtils.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiContractCallLocal.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractBytecode.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/file/HapiGetFileInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetVersionInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/schedule/HapiGetScheduleInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileUpdate.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromFile.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/RecordFileChecker.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/throughput/FinishThroughputObs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/AccountAutoRenewalSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/MacroFeesChargedSanityCheckSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/block/BlockSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeCopyOperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeHashOperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeSizeOperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/GlobalPropertiesSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DynamicGasCostSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateForSuiteRunner.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/UpdateFailuresSpec.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/perf/AccountBalancesClientSaveLoadTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/FibonacciPlusLoadProvider.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoAllowancePerfSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/TokenTransferBasicLoadTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/regression/SteadyStateThrottlingCheck.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleLongTermExecutionSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenPauseSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/BookEntryPojo.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/sysfiles/serdes/StandardSerdes.java
Labels: CI:UnitTests

#3647 Apply Spotless Formatting - Part 3
  hapi-utils/README.md
  hapi-utils/src/main/java/com/hedera/services/ethereum/EthTxData.java
  hapi-utils/src/main/java/com/hedera/services/ethereum/EthTxSigs.java
  hapi-utils/src/main/java/com/hedera/services/keys/Ed25519Utils.java
  hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/ByteStringUtils.java
  hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/CommonUtils.java
  hapi-utils/src/main/java/com/hedera/services/legacy/proto/utils/SignatureGenerator.java
  hapi-utils/src/main/java/com/hedera/services/recordstreaming/RecordStreamingUtils.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/ParsingUtils.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/KnownBlockValues.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucket.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleDefinitions.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleGroup.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ThrottleReqOpsScaleFactor.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/serdes/ThrottlesJsonToProtoSerde.java
  hapi-utils/src/main/java/com/hedera/services/sysfiles/validation/ErrorCodeUtils.java
  hapi-utils/src/main/java/com/hedera/services/throttles/BucketThrottle.java
  hapi-utils/src/main/java/com/hedera/services/throttles/DeterministicThrottle.java
  hapi-utils/src/main/java/com/hedera/services/throttles/DiscreteLeakyBucket.java
  hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitBucketThrottle.java
  hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitDeterministicThrottle.java
  hapi-utils/src/main/java/com/hederahashgraph/builder/RequestBuilder.java
  hapi-utils/src/main/java/com/hederahashgraph/exception/InvalidTxBodyException.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilder.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/CryptoFeeBuilder.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/FeeObject.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/FileFeeBuilder.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/SigValueObj.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/SmartContractFeeBuilder.java
  hapi-utils/src/test/java/com/hedera/services/TestUtils.java
  hapi-utils/src/test/java/com/hedera/services/UtilsConstructorTest.java
  hapi-utils/src/test/java/com/hedera/services/ethereum/EthTxDataTest.java
  hapi-utils/src/test/java/com/hedera/services/ethereum/EthTxSigsTest.java
  hapi-utils/src/test/java/com/hedera/services/ethereum/TestingConstants.java
  hapi-utils/src/test/java/com/hedera/services/keys/Ed25519UtilsTest.java
  hapi-utils/src/test/java/com/hedera/services/legacy/proto/utils/ByteStringUtilsTest.java
  hapi-utils/src/test/java/com/hedera/services/legacy/proto/utils/SignatureGeneratorTest.java
  hapi-utils/src/test/java/com/hedera/services/recordstreaming/RecordStreamingUtilsTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/KnownBlockValuesTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/ThrottleBucketTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/ThrottleDefinitionsTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/ThrottleReqOpsScaleFactorTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/serdes/FeesJsonToProtoSerdeTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/serdes/ThrottlesJsonToProtoSerdeTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/validation/ErrorCodeUtilsTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/validation/ExpectedCustomThrottlesTest.java
  hapi-utils/src/test/java/com/hedera/services/throttles/BucketThrottleTest.java
  hapi-utils/src/test/java/com/hedera/services/throttles/ConcurrentThrottleTestHelper.java
  hapi-utils/src/test/java/com/hedera/services/throttles/DeterministicThrottleTest.java
  hapi-utils/src/test/java/com/hedera/services/throttles/DiscreteLeakyBucketTest.java
  hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitBucketThrottleTest.java
  hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitDeterministicThrottleTest.java
  hapi-utils/src/test/java/com/hederahashgraph/builder/RequestBuilderTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/ConsensusServiceFeeBuilderTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/CryptoFeeBuilderTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/FeeBuilderTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/FeeObjectTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/FileFeeBuilderTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/SmartContractFeeBuilderTest.java
Labels: CI:UnitTests

#3673 Add FOSSA Support to the GH Actions Workflow
  .github/workflows/comp-compile-application-code.yaml
  .github/workflows/flow-build-application.yaml
  .github/workflows/flow-pull-request-checks.yaml
Labels: CI:UnitTests

#3689 Update CircleCI automation to use Gradle
  .circleci/config.yml
  test-clients/build.gradle.kts
Labels: CI:UnitTests

#3693 Remove `getPseudoRandomNumber` from PRNG precompiles
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContractTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PrngPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/GracefullyFailingPrng/GracefullyFailingPrng.bin
  test-clients/src/main/resource/contract/contracts/GracefullyFailingPrng/GracefullyFailingPrng.json
  test-clients/src/main/resource/contract/contracts/GracefullyFailingPrng/GracefullyFailingPrng.sol
  test-clients/src/main/resource/contract/contracts/PrngSystemContract/IPrngSystemContract.sol
  test-clients/src/main/resource/contract/contracts/PrngSystemContract/PrngSystemContract.bin
  test-clients/src/main/resource/contract/contracts/PrngSystemContract/PrngSystemContract.json
  test-clients/src/main/resource/contract/contracts/PrngSystemContract/PrngSystemContract.sol
Labels: CI:UnitTests

#3695 Spotless formatting for sidecar work
  hedera-node/src/main/java/com/hedera/services/context/BasicTransactionContext.java
  hedera-node/src/main/java/com/hedera/services/context/TransactionContext.java
  hedera-node/src/main/java/com/hedera/services/records/InProgressChildRecord.java
  hedera-node/src/main/java/com/hedera/services/records/RecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/records/TransactionRecordService.java
  hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/state/submerkle/EvmFnResult.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamFileWriter.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamManager.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamObject.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamType.java
  hedera-node/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/utils/ResponseCodeUtil.java
  hedera-node/src/test/java/com/hedera/services/context/BasicTransactionContextTest.java
  hedera-node/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
  hedera-node/src/test/java/com/hedera/services/records/TxnAwareRecordsHistorianTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/EvmFnResultSerdeTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/EvmFnResultTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordSerdeTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamFileWriterTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamManagerTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamTypeTest.java
  hedera-node/src/test/java/com/hedera/services/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/test/utils/SerdeUtils.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilStateChange.java
Labels: CI:UnitTests

#3708 Allow staking to contract accounts, only return `stakePeriodStart` if staking to node
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/txns/validation/PureValidation.java
  hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/src/test/java/com/hedera/services/txns/validation/PureValidationTest.java
  pom.xml
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
Labels: CI:UnitTests

#3715 SuiteRunner JAR file is expected by JRS to be an Uber JAR file
  Dockerfile
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.shadow-jar.gradle.kts
  test-clients/build.gradle.kts
Labels: CI:UnitTests

#3662 Token info retrieval precompiles
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hapi-utils/src/test/java/com/hedera/services/contracts/ParsingConstantsTest.java
  hedera-node/src/main/java/com/hedera/services/ledger/properties/NftProperty.java
  hedera-node/src/main/java/com/hedera/services/ledger/properties/TokenProperty.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/TokenKeyType.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/TokenInfoWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractTokenInfoPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/FungibleTokenInfoPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/NonFungibleTokenInfoPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenInfoPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/RedirectViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewGasCalculator.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/src/test/java/com/hedera/services/ledger/properties/TokenPropertyTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenInfoPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/RedirectViewExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordsRunningHashLeafTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiContractCallLocal.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiBaseCall.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCall.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiParserUtil.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DelegatePrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DynamicGasCostSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/TokenKeyType.java
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.bin
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: enhancement, hts-contracts, CI:UnitTests, token-management precompile (HIP 514)

#3697 HIP 514: Add token management functions for defaultStatus
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hedera-node/src/main/java/com/hedera/services/ledger/properties/TokenProperty.java
  hedera-node/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/StaticEntityAccess.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/WorldLedgers.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/GetTokenDefaultFreezeStatusWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/GetTokenDefaultKycStatusWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/GetTokenDefaultFreezeStatus.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/GetTokenDefaultKycStatus.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/src/test/java/com/hedera/services/ledger/properties/TokenPropertyTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/StaticEntityAccessTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/WorldLedgersTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenDefaultFreezeStatusTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenDefaultKycStatusTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DefaultTokenStatusSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
  test-clients/src/main/resource/contract/contracts/TokenDefaultKycAndFreezeStatus/TokenDefaultKycAndFreezeStatus.bin
  test-clients/src/main/resource/contract/contracts/TokenDefaultKycAndFreezeStatus/TokenDefaultKycAndFreezeStatus.json
  test-clients/src/main/resource/contract/contracts/TokenDefaultKycAndFreezeStatus/TokenDefaultKycAndFreezeStatus.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: P1, enhancement, hts-contracts, CI:UnitTests, token-management precompile (HIP 514)

#3658 03622 wipe token precompile
  hedera-node/src/main/java/com/hedera/services/contracts/sources/EvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/WipeWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractWipePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/WipeFungiblePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/WipeNonFungiblePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenWipeTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/WipeLogic.java
  hedera-node/src/test/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifierTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeNonFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenWipeTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/WipeLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/WipeTokenAccount/WipeTokenAccount.bin
  test-clients/src/main/resource/contract/contracts/WipeTokenAccount/WipeTokenAccount.json
  test-clients/src/main/resource/contract/contracts/WipeTokenAccount/WipeTokenAccount.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: P1, enhancement, hts-contracts, CI:UnitTests, token-management precompile (HIP 514)

#3728 Port `0.27.5` fixes from `release/0.28` branch
  hedera-node/src/main/java/com/hedera/services/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/SizeLimitedStorage.java
  hedera-node/src/test/java/com/hedera/services/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/accounts/staking/PendingRewardsManagementTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/SizeLimitedStorageTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/resource/contract/bytecodes/farmInitcode.bin
Labels: CI:UnitTests

#3716 Add `StateView` to the `TxnAccessor` and add custom accessors
  hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java
  hapi-fees/src/main/java/com/hedera/services/usage/token/TokenOpsUsageUtils.java
  hapi-fees/src/test/java/com/hedera/services/usage/token/TokenOpsUsageUtilsTest.java
  hedera-node/src/main/java/com/hedera/services/context/MutableStateChildren.java
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/fees/calculation/utils/OpUsageCtxHelper.java
  hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/txns/TransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/submission/StructuralPrecheck.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenWipeTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/WipeLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/validation/ContextOptionValidator.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/AccessorFactory.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/PlatformTxnAccessor.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/SignedTxnAccessor.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/TokenWipeAccessor.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/TxnAccessor.java
  hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/src/test/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculatorTest.java
  hedera-node/src/test/java/com/hedera/services/records/RecordCacheTest.java
  hedera-node/src/test/java/com/hedera/services/sigs/SigVerifierRegressionTest.java
  hedera-node/src/test/java/com/hedera/services/sigs/verification/PrecheckVerifierTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/AwareNodeDiligenceScreenTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/StandardProcessLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/ExpandHandleSpanTest.java
  hedera-node/src/test/java/com/hedera/services/txns/auth/SystemOpPoliciesTest.java
  hedera-node/src/test/java/com/hedera/services/txns/submission/PlatformSubmissionManagerTest.java
  hedera-node/src/test/java/com/hedera/services/txns/submission/StructuralPrecheckTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenWipeTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/WipeLogicTest.java
  hedera-node/src/test/java/com/hedera/services/utils/EntityIdUtilsTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/AccessorFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/PlatformTxnAccessorTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/SignedTxnAccessorTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/TokenWipeAccessorTest.java
  hedera-node/src/test/java/com/hedera/test/factories/scenarios/ScheduleSignScenarios.java
  hedera-node/src/test/java/com/hedera/test/factories/txns/ScheduleCreateFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenWipe.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: CI:UnitTests

#3686 03613 token freeze unfreeze precompile
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hedera-node/src/main/java/com/hedera/services/contracts/sources/EvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/StaticEntityAccess.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/WorldLedgers.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/TokenFreezeUnfreezeWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractFreezeUnfreezePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/FreezeTokenPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/IsFrozenPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/UnfreezeTokenPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/src/main/java/com/hedera/services/txns/token/FreezeLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenFreezeTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenUnfreezeTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/UnfreezeLogic.java
  hedera-node/src/test/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifierTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/StaticEntityAccessTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/WorldLedgersTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/FreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/IsFrozenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnfreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenFreezeTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenUnfreezeTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
  test-clients/src/main/resource/contract/contracts/FreezeUnfreezeContract/FreezeUnfreezeContract.bin
  test-clients/src/main/resource/contract/contracts/FreezeUnfreezeContract/FreezeUnfreezeContract.json
  test-clients/src/main/resource/contract/contracts/FreezeUnfreezeContract/FreezeUnfreezeContract.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: enhancement, hts-contracts, CI:UnitTests, token-management precompile (HIP 514)

#3726 03617 token get custom fees precompile
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hapi-utils/src/test/java/com/hedera/services/contracts/ParsingConstantsTest.java
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/TokenGetCustomFeesWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenGetCustomFeesPrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenGetCustomFeesPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/EncodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.bin
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.json
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: P1, hts-contracts, CI:UnitTests, token-management precompile (HIP 514)

#3671 03621 pause/unpause token precompile
  hedera-node/src/main/java/com/hedera/services/contracts/sources/EvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifier.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/PauseWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/UnpauseWrapper.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/PausePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/UnpausePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/src/main/java/com/hedera/services/txns/token/PauseLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenPauseTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenUnpauseTransitionLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/token/UnpauseLogic.java
  hedera-node/src/test/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifierTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/PausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnpausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/PauseLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenPauseTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenUnpauseTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/UnpauseLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/PauseUnpauseTokenAccount/PauseUnpauseTokenAccount.bin
  test-clients/src/main/resource/contract/contracts/PauseUnpauseTokenAccount/PauseUnpauseTokenAccount.json
  test-clients/src/main/resource/contract/contracts/PauseUnpauseTokenAccount/PauseUnpauseTokenAccount.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: P1, enhancement, hts-contracts, CI:UnitTests, token-management precompile (HIP 514)
