Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2022-12, with the labels that each got.

#4365 Add Account and AccountBuilder
  hedera-node/hapi-fees/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/CryptoSignatureWaiversImpl.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/entity/AccountBuilderImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/entity/AccountImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/entity/AccountBuilderImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/entity/AccountImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/module-info.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/CryptoSignatureWaivers.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/entity/Account.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/entity/AccountBuilder.java
  hedera-node/hedera-token-service/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, Modularization

#4406 Fix module-info.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4401 Upgrade Besu EVM to 22.10.1
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractCodeCache.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldStateTokenAccount.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/WorldStateAccount.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/MockHederaEvmTxProcessor.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/AbstractCodeCacheTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_30Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_32Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperation.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
  settings.gradle.kts
Labels: dependencies, CI:UnitTests, Hedera Smart Contract Service

#4405 Bump platform version
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/SigWaivers.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/PreHandleContextTest.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/AbstractCodeCache.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/HederaEvmWorldStateTokenAccount.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/WorldStateAccount.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/MockHederaEvmTxProcessor.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/store/contracts/AbstractCodeCacheTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoSignatureWaiversImpl.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_30Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_32Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CallEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CreateEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/AbstractRecordingCreateOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/AliasManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/AliasManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4410 Tweak test-clients project to configure with hapi-fees jar
  test-clients/build.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4391 Fix E2E BigInteger casting issue
  test-clients/src/main/java/com/hedera/services/bdd/suites/perf/contract/MixedSmartContractOpsLoadTest.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4314 Implementation of pre-handle transaction workflow
  docs/design/app/images/Pre-Handle Transaction Workflow.png
  docs/design/app/images/Pre-Handle Transaction Workflow.svg
  docs/design/app/workflows.md
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/ErrorTransactionMetadata.java
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesAccessor.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/SessionContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/common/PreCheckException.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/onset/OnsetResult.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/onset/WorkflowOnset.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/PreCheckExceptionTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  settings.gradle.kts
Labels: CI:FinalChecks, Modularization

#4321 Enhance default implementations for evm library
  hedera-node/hapi-utils/build.gradle.kts
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigs.java
  hedera-node/hapi-utils/src/main/java/module-info.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigsTest.java
  hedera-node/hedera-evm-api/src/main/java/module-info.java
  hedera-node/hedera-evm/build.gradle.kts
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/traceability/DefaultHederaTracer.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmSLoadOperation.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/HederaEvmAccount.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/utils/EthSigsUtils.java
  hedera-node/hedera-evm/src/main/java/module-info.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmMessageCallProcessorTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/MockHederaEvmOperationTracer.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaBalanceOperationTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperationTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmOperationsUtilTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExceptionalHaltReasonTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeCopyOperationTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeHashOperationTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeSizeOperationTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmAccountTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/utils/EthSigsUtilsTest.java
  hedera-node/hedera-mono-service/data/saved/swirlds-tmp/99-database-uniqueTokenStore-1669896406471/pathToHashKeyValue/uniqueTokenStore:pathToHashKeyValue_metadata.dfc
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/StateView.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/AliasManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/WorldLedgers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/models/Account.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/StateViewTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/AliasManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractLogAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4414 Change setting to `consensus.roundsExpired`
  hedera-node/configuration/compose/settings.txt
  hedera-node/configuration/dev/settings.txt
  hedera-node/configuration/mainnet/settings.txt
  hedera-node/configuration/preprod/settings.txt
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/configuration/testnet/settings.txt
  hedera-node/settings.txt
  test-clients/src/eet/resources/network/config/settings.txt
  test-clients/src/itest/resources/network/config/settings.txt
  test-clients/src/main/resource/testfiles/updateFeature/updateSettings/sdk/settings.txt
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4385 Enable prometheus scrape endpoint for preprod
  hedera-node/configuration/preprod/settings.txt
Labels: CI:UnitTests

#4394 Add e2e for tranfer tokens with custom fees
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AdjustmentUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/BalanceChange.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/AdjustmentUtilsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/BalanceChangeManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/ImpliedTransfersMarshalTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/BalanceChangeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4430 Trace precompile execution actions consistently
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExceptionalHaltReason.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/BurnPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/CreatePrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/MintPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/WipeFungiblePrecompileTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/resource/contract/contracts/ApproveByDelegateCall/ApproveByDelegateCall.bin
  test-clients/src/main/resource/contract/contracts/ApproveByDelegateCall/ApproveByDelegateCall.json
  test-clients/src/main/resource/contract/contracts/ApproveByDelegateCall/ApproveByDelegateCall.sol
Labels: CI:UnitTests

#4382 Handle exceeded child records during EVM execution
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/ERC20Contract/ERC20Contract.bin
  test-clients/src/main/resource/contract/contracts/ERC20Contract/ERC20Contract.json
  test-clients/src/main/resource/contract/contracts/ERC20Contract/ERC20Contract.sol
Labels: Limechain, CI:UnitTests

#4408 Remove install aws tool
  .circleci/config.yml
Labels: CI:UnitTests, CI:FinalChecks

#4434 Hotfix to execute itests in IntelliJ
  test-clients/build.gradle.kts
Labels: Bug, dependencies, Improvement, CI:UnitTests, CI:FinalChecks, Modularization

#4426 Use `0.33.0-grpc-1.45.1-SNAPSHOT` protobuf artifact
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4441 Fix `gasUsed` in MintPrecompile
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MintPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/MintPrecompileTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4444 Cherry-pick commits from develop
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/MintPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/MintPrecompileTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4421 Create a test client to setup staked accounts and export CSV on e.g. previewnet
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StartStaking.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4473 Update log4j2 file name used in circle ci pipeline
  .circleci/config.yml
Labels: CI:UnitTests, CI:FinalChecks

#4381 Add E2E tests for payer with unsufficient balance
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4425 Add `AccountKeyLookup`
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/AccountKeyLookup.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/KeyOrLookupFailureReason.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/ErrorTransactionMetadata.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/SigTransactionMetadata.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/SigTransactionMetadataBuilder.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/TransactionMetadata.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/PreHandleContextTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/meta/ErrorTransactionMetadataTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/meta/SigTransactionMetadataBuilderTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/meta/SigTransactionMetadataTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/numbers/HederaAccountNumbersTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/numbers/HederaFileNumbersTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/SigTransactionMetadata.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/AccountStore.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/CryptoPreTransactionHandlerImpl.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/SigTransactionMetadataTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/token/impl/CryptoPreTransactionHandlerImplTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, Modularization

#4470 [HIP-583] Fix auto creation in precompile
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/LedgerModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/ContractAliases.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/HederaAliasManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/StackedContractAliases.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/EvmAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/StackedContractAliasesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/EvmAutoCreationLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.bin
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.json
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.sol
Labels: Limechain, CI:UnitTests

#4483 Add staking validation scenario
  test-clients/build.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeesAndRatesProvider.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/Scenarios.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/StakingScenario.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4481 Fix porting pt2
  gradle.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/RewardCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeChangeManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeInfoManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/merkle/MerkleStakingInfo.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/migration/StateVersions.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/StandardizedPropertySourcesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/RewardCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeChangeManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeInfoManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelperTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/merkle/MerkleStakingInfoTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4502 Port fixes to `release/0.33`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/sources/EvmSigsVerifier.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifier.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/keys/LegacyContractIdActivations.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/RewardCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeChangeManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeInfoManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/merkle/MerkleStakingInfo.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/AbstractTokenUpdatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenUpdateKeysPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenUpdatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/UpdateTokenExpiryInfoPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/sigs/KeyValidator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/sigs/LegacyKeyValidator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/sigs/TokenCreateReqs.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/utils/KeyActivationUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/utils/LegacyActivationTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/utils/LegacyKeyActivationTest.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/StandardizedPropertySourcesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/sources/TxnAwareEvmSigsVerifierTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/keys/LegacyContractIdActivationsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/RewardCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeChangeManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeInfoManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelperTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/impl/AbstractTokenUpdatePrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/impl/sigs/TokenCreateReqsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/utils/KeyActivationUtilsTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/spec/HapiPropertySource.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyShape.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/SigningReqsSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenExpiryInfoSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
  test-clients/src/main/resource/contract/contracts/MinimalTokenCreations/MinimalTokenCreations.bin
  test-clients/src/main/resource/contract/contracts/MinimalTokenCreations/MinimalTokenCreations.json
  test-clients/src/main/resource/contract/contracts/MinimalTokenCreations/MinimalTokenCreations.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4506 Update settings.gradle.kts
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4109 [HIP-583] Pre-charge hollow account finalization fees
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/TransferLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: P1, Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4422 Token implementation moved to token module
  README.md
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  gradle.properties
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/meta/SigTransactionMetadataTest.java
  hedera-node/hedera-evm-api/src/main/java/module-info.java
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/CryptoServiceImpl.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/KeyUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessorTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/ScheduleSignScenarios.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/FileCreateFactory.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/SignedTxnFactory.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/TokenUpdateFactory.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/KeyUtils.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TxnUtils.java
  hedera-node/hedera-mono-service/src/testFixtures/java/module-info.java
  hedera-node/hedera-token-service-impl/build.gradle.kts
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/AccountStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/CryptoQueryHandlerImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/CryptoSignatureWaiversImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/StandardCryptoService.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/AliasUtils.java
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/AccountStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/CryptoPreTransactionHandlerImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/CryptoPreTransactionHandlerNotImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/CryptoServiceImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/CryptoSignatureWaiversImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/StandardCryptoServiceTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/UtilsConstructorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/module-info.java
  settings.gradle.kts
Labels: dependencies, Java, CI:UnitTests, Tech Debt Reduced, CI:FinalChecks, Modularization

#4488 04361 token wipe prehandle
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/TokenPreTransactionHandlerImpl.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/token/impl/TokenServiceImpl.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/token/impl/TokenPreTransactionHandlerImplTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/token/impl/TokenServiceImplTest.java
Labels: CI:UnitTests, Modularization

#4510 Fix compile errors on develop
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenPreTransactionHandlerImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenPreTransactionHandlerImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenServiceImplTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4511 Avoid `txnCtx.consensusTime()` when recomputing rewards
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/RewardCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManager.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/RewardCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/StakePeriodManagerTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4512 Port staking fix
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/services/ledger/StakingActivityBench.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/RewardCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakePeriodManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/RewardCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakePeriodManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelperTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4509 Fixes for 0331
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsage.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/RewardCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakePeriodManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/staking/StakingUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/queries/contract/ContractCallLocalAnswer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/logic/NetworkCtxManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/TimedFunctionalityThrottling.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/TxnAwareHandleThrottling.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/contract/queries/ContractCallLocalResourceUsageTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/RewardCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakeStartupHelperTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/staking/StakingUtilsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/queries/contract/ContractCallLocalAnswerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/logic/NetworkCtxManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/throttling/TxnAwareHandleThrottlingTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4501 add the allow list functionality limits to specific array per enviro…
  test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
  test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
  test-clients/src/main/java/com/hedera/services/yahcli/config/domain/NetConfig.java
  test-clients/yahcli/README.md
  test-clients/yahcli/config.yml
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4520 Recompile `TransferToAliasPrecompileContract` as `PrecompileAliasXfer`
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/PrecompileAliasXfer/PrecompileAliasXfer.bin
  test-clients/src/main/resource/contract/contracts/PrecompileAliasXfer/PrecompileAliasXfer.json
  test-clients/src/main/resource/contract/contracts/PrecompileAliasXfer/PrecompileAliasXfer.sol
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.bin
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.json
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4335 [HIP-583] Don't populate `alias` in account info query if `alias` is evm address
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/StateView.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/StateViewTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/ReferenceType.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiParserUtil.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/SigningReqsSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4402 Add hapi pbj
  .gitignore
  build.gradle.kts
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-java-conventions.gradle.kts
  hedera-node/hapi/build.gradle.kts
  hedera-node/hapi/src/main/java/module-info.java
  settings.gradle.kts
Labels: CI:UnitTests

#4521 04480 add allow list to yachli
  test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
  test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
  test-clients/src/main/java/com/hedera/services/yahcli/config/domain/NetConfig.java
  test-clients/yahcli/README.md
  test-clients/yahcli/assets/screened-launch.sh
  test-clients/yahcli/config.yml
  test-clients/yahcli/run/build.sh
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4514 Fix `VS` contract scenario
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiBaseCall.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/ValidationScenarios.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/ContractScenario.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/utils/validation/domain/Network.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4522 Simplify `CryptoCreate` management of new aliases + sig impacts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/StateView.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/AliasManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/MiscUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/MiscUtilsTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4523 Use static ledgers to answer view queries
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/proxy/ViewExecutorTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4526 Update Hapi version
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4128 Implement completion of lazy created accounts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/SideEffectsTracker.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/charging/TxnChargingPolicyAgent.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/keys/HederaKeyActivation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JHollowKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/PlatformSigOps.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/SigsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookup.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigReqsManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/utils/MiscCryptoUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/verification/PrecheckVerifier.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/ExpiringCreations.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/SigsAndPayerKeyScreen.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/RationalizedSigMeta.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/SideEffectsTrackerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/keys/HederaKeyActivationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/legacy/core/jproto/JHollowKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/PlatformSigOpsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookupTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigReqsManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/verification/PrecheckVerifierTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/ExpiringCreationsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/SigsAndPayerKeyScreenTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/RationalizedSigMetaTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/TokenMovement.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: P1, Limechain, CI:UnitTests

#4378 Update CryptoCreate to correctly populate the TX body and TX rec with the newest protobufs
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/mocks/MockTransactionContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/BasicTransactionContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/TransactionContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/StateView.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/AliasManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/submerkle/ExpirableTxnRecord.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/MiscUtils.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/BasicTransactionContextTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/StateViewTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/submerkle/ExpirableTxnRecordSerdeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/submerkle/ExpirableTxnRecordTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/submerkle/ExpirableTxnRecordTestHelper.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/MiscUtilsTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn0.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn1.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn10.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn11.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn12.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn13.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn14.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn15.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn16.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn17.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn18.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn19.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn2.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn3.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn4.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn5.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn6.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn7.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn8.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/ExpirableTxnRecord-v12-sn9.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerklePayerRecords-v1-sn4.hex
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/FeatureFlags.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  test-clients/src/main/resource/bootstrap.properties
Labels: Limechain, CI:UnitTests

#4518 04497 token pause unpause prehandle
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenPreTransactionHandlerImpl.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenPreTransactionHandlerImplTest.java
Labels: CI:UnitTests, Modularization

#4070 [HIP-583] Add support for lazy account creation through top level `EthereumTransaction`
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmMessageCallProcessor.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExceptionalHaltReason.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmMessageCallProcessorTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AliasResolver.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/models/Account.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/DeterministicThrottling.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsTestComponent.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/files/interceptors/ThrottleDefsManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/AliasResolverTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdaterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/throttling/DeterministicThrottlingTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessorTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/throttles-sans-creation.json
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/throttles.json
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/FeatureFlags.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.bin
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.json
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.sol
Labels: P1, Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4515 Google Truth removed
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/UniqueTokensMigratorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeySerializerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeySupplierTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenValueSupplierTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenValueTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/token/BurnLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/token/MintLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/subjects/UniqueTokenValueSubject.java
  settings.gradle.kts
Labels: dependencies, Java, CI:UnitTests, Tech Debt Reduced, CI:FinalChecks

#4533 Skip PBJ unit tests in CI
  .github/workflows/comp-compile-application-code.yaml
Labels: CI:UnitTests

#4419 Refactoring of basic / api dependencies
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  hedera-node/hapi-fees/build.gradle.kts
  hedera-node/hapi-fees/src/main/java/module-info.java
  hedera-node/hapi-utils/build.gradle.kts
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
  hedera-node/hapi-utils/src/main/java/module-info.java
  hedera-node/hedera-admin-service-impl/build.gradle.kts
  hedera-node/hedera-admin-service-impl/src/main/java/module-info.java
  hedera-node/hedera-admin-service/build.gradle.kts
  hedera-node/hedera-admin-service/src/main/java/module-info.java
  hedera-node/hedera-app-spi/build.gradle.kts
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-consensus-service-impl/build.gradle.kts
  hedera-node/hedera-consensus-service-impl/src/main/java/module-info.java
  hedera-node/hedera-consensus-service/build.gradle.kts
  hedera-node/hedera-consensus-service/src/main/java/module-info.java
  hedera-node/hedera-evm-impl/build.gradle.kts
  hedera-node/hedera-evm/build.gradle.kts
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
  hedera-node/hedera-evm/src/main/java/module-info.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/MockHederaEvmTxProcessor.java
  hedera-node/hedera-file-service-impl/build.gradle.kts
  hedera-node/hedera-file-service-impl/src/main/java/module-info.java
  hedera-node/hedera-file-service/build.gradle.kts
  hedera-node/hedera-file-service/src/main/java/module-info.java
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-network-service-impl/build.gradle.kts
  hedera-node/hedera-network-service-impl/src/main/java/module-info.java
  hedera-node/hedera-network-service/build.gradle.kts
  hedera-node/hedera-network-service/src/main/java/module-info.java
  hedera-node/hedera-schedule-service-impl/build.gradle.kts
  hedera-node/hedera-schedule-service-impl/src/main/java/module-info.java
  hedera-node/hedera-schedule-service-impl/src/test/java/module-info.java
  hedera-node/hedera-schedule-service/build.gradle.kts
  hedera-node/hedera-schedule-service/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/build.gradle.kts
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service/build.gradle.kts
  hedera-node/hedera-smart-contract-service/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/build.gradle.kts
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
  hedera-node/hedera-token-service/build.gradle.kts
  hedera-node/hedera-token-service/src/main/java/module-info.java
  hedera-node/hedera-util-service-impl/build.gradle.kts
  hedera-node/hedera-util-service-impl/src/main/java/module-info.java
  hedera-node/hedera-util-service/build.gradle.kts
  hedera-node/hedera-util-service/src/main/java/module-info.java
  settings.gradle.kts
Labels: Java, Improvement, CI:UnitTests, Tech Debt Reduced, CI:FinalChecks, Modularization

#4532 Services renamed
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/FreezeServiceImpl.java
  hedera-node/hedera-admin-service-impl/src/main/java/module-info.java
  hedera-node/hedera-admin-service-impl/src/test/java/com/hedera/node/app/service/admin/impl/test/FreezeServiceImplTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ConsensusServiceImpl.java
  hedera-node/hedera-consensus-service-impl/src/main/java/module-info.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ConsensusServiceImplTest.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
  hedera-node/hedera-file-service-impl/src/main/java/module-info.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileServiceImplTest.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/NetworkServiceImpl.java
  hedera-node/hedera-network-service-impl/src/main/java/module-info.java
  hedera-node/hedera-network-service-impl/src/test/java/com/hedera/node/app/service/network/impl/test/NetworkServiceImplTest.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/ScheduleServiceImplTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/StandardContractService.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractServiceImplTest.java
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/CryptoServiceImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenServiceImplTest.java
  hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/UtilServiceImpl.java
  hedera-node/hedera-util-service-impl/src/main/java/module-info.java
  hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/UtilServiceImplTest.java
Labels: CI:UnitTests, CI:FinalChecks, Modularization

#4528 Add `RecordStreamValidator` framework
  .github/workflows/comp-compile-application-code.yaml
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/recordstreaming/RecordStreamingUtils.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/recordstreaming/RecordStreamingUtilsTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/forensics/RecordParsers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/forensics/RecordStreamEntry.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/forensics/OrderedComparisonTest.java
  settings.gradle.kts
  test-clients/src/itest/java/AllIntegrationTests.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/BalanceReconciliationValidator.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/RecordStreamAccess.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/RecordStreamValidator.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/RecordWithSidecars.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/TestBase.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/utils/AccountClassifier.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/validators/HgcaaLogValidator.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/validators/QueryLogValidator.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/grouping/ParallelSpecOps.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/misc/PerpetualTransfers.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/records/BalanceValidation.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/records/ClosingTime.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4306 Fix `0.0.0` assessed custom fee effective payer account when auto created in the same txn
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AssessedCustomFeeWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/ImpliedTransfers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/ImpliedTransfersMarshal.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/BalanceChange.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoTransferTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/span/SpanMapManager.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/AssessedCustomFeeWrapperTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/ImpliedTransfersMarshalTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/ImpliedTransfersTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/BalanceChangeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoTransferTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/span/SpanMapManagerTest.java
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.bin
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.json
  test-clients/src/main/resource/contract/contracts/TransferToAliasPrecompileContract/TransferToAliasPrecompileContract.sol
Labels: Bug, Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4477 Enriching evm-module's account/updater impl.
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldStateTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java
Labels: Limechain, CI:UnitTests

#4545 Migrate Actions workflows to new cluster
  .github/workflows/comp-build-release-artifact.yaml
  .github/workflows/comp-compile-application-code.yaml
  .github/workflows/flow-deploy-release-artifact.yaml
  .github/workflows/flow-pull-request-checks.yaml
Labels: CI:UnitTests, Feature Enhancement, P0
