Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2022-11, with the labels that each got.

#4057 03562 codecache default impl
  hedera-node/hedera-evm-api/build.gradle.kts
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/AbstractCodeCache.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/HederaEvmEntityAccess.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/HederaEvmWorldStateTokenAccount.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/store/contracts/utils/BytesKey.java
  hedera-node/hedera-evm-api/src/main/java/module-info.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/store/contracts/AbstractCodeCacheTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/store/contracts/HederaEvmWorldStateTokenAccountTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/store/contracts/MockAbstractCodeCache.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/store/contracts/utils/BytesKeyTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/tasks/TraceabilityExportTask.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/CodeCache.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/EntityAccess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/HederaStackedWorldStateUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/MutableEntityAccess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/StaticEntityAccess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/UpdateTrackingLedgerAccount.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/WorldLedgers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/WorldStateAccount.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/utils/KeyActivationUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/RationalizedSigMeta.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/ResponseCodeUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/merkle/MerklePayerRecordsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/tasks/TraceabilityExportTaskTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/HederaWorldStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/MutableEntityAccessTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/StaticEntityAccessTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/UpdateTrackingLedgerAccountTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/WorldLedgersTest.java
Labels: CI:UnitTests

#4131 Adds Token Store
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/TokenStore.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/TokenStoreTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, modularization

#4167 Cherry-pick fixes for `v0.31.2`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/BalanceChange.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/TransferLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/AccountsCommitInterceptor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/legacy/core/jproto/JECDSASecp256k1Key.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/legacy/core/jproto/JEd25519Key.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/LedgerBalanceChangesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/TransferLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/AccountsCommitInterceptorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4153 Reject transactions with unknown fields both in precheck and at consensus
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/traceability/SolidityAction.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/logic/AwareNodeDiligenceScreen.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/submission/PresolvencyFlaws.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/submission/StructuralPrecheck.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/accessors/PlatformTxnAccessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/accessors/SignedTxnAccessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/accessors/TxnAccessor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/SolidityActionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/logic/AwareNodeDiligenceScreenTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/submission/StructuralPrecheckTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/utils/accessors/PlatformTxnAccessorTest.java
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCornerCasesSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4163 Disable recovery test until new implementation is merged
  .circleci/config.yml
Labels: CI:UnitTests, CI:FinalChecks

#4110 Disable sender inheritance on contract creation via ethereum transaction
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CreateEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/ContractCustomizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/SynthCreationCustomizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/SynthCreationCustomizerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/ethereum/EthereumTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumContractCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
  test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests

#4169 Cherry pick changes from develop
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/CreateEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/ContractCustomizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/accounts/SynthCreationCustomizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/accounts/SynthCreationCustomizerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/ethereum/EthereumTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumContractCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
  test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests

#4181 Left-pad `(r, s)` curve points given to native library
  hapi-utils/src/main/java/com/hedera/services/ethereum/EthTxSigs.java
  hapi-utils/src/test/java/com/hedera/services/ethereum/EthTxSigsTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4179 Add E2Es verifying HIP-583 CryptoCreate txns are not accepted when flags are disabled
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4182 Move swirlds-hashstream log file to subdirectory
  hedera-node/configuration/compose/log4j2.xml
  hedera-node/configuration/dev/log4j2.xml
  hedera-node/configuration/mainnet/log4j2.xml
  hedera-node/configuration/preprod/log4j2.xml
  hedera-node/configuration/previewnet/log4j2.xml
  hedera-node/configuration/testnet/log4j2.xml
Labels: CI:UnitTests

#4193 Match user expectations on indirect staking reward situations
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4195 Platform version bump
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4177 Use the SPI Module
  .env
  .github/workflows/comp-build-release-artifact.yaml
  README.md
  docs/design/design.md
  docs/design/images/hedera-high-level-architecture.svg
  docs/design/images/hedera-module-block-diagram.svg
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/HapiThrottleUtilsTest.java
  hedera-node/hedera-app-api/src/main/java/module-info.java
  hedera-node/hedera-app-spi/build.gradle.kts
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/PreTransactionHandler.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/HederaKey.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/TransactionMetadata.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/package-info.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/State.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/States.java
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/main/java/com/hedera/services/api/implementation/PlaceholderImplementation.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/SigTransactionMetadata.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/Utils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/SigTransactionMetadataTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/UtilsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/AccountStoreTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImplTest.java
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/yahcli/suites/SpecialFileHashSuite.java
Labels: CI:UnitTests, CI:FinalChecks

#4158 03933 operation codes evm module impl
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaBalanceOperation.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaDelegateCallOperation.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmOperationsUtil.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmSLoadOperation.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExceptionalHaltReason.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExtCodeCopyOperation.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExtCodeHashOperation.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExtCodeSizeOperation.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaBalanceOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaDelegateCallOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaEvmOperationsUtilTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaExceptionalHaltReasonTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaExtCodeCopyOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaExtCodeHashOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaExtCodeSizeOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operations/HederaEvmSLoadOperationTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_30Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_32Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaCallCodeOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaCallOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaOperationUtil.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaSLoadOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaStaticCallOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/ResponseCodeUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallLocalExecutorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaCallCodeOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaCallOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaOperationUtilTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaSelfDestructOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaStaticCallOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/records/TransactionRecordServiceTest.java
Labels: CI:UnitTests

#4247 Fix Maven publishes of the EVM modules to properly respect prerelease versions
  .github/workflows/comp-build-release-artifact.yaml
  .github/workflows/flow-deploy-release-artifact.yaml
Labels: Bug, CI:UnitTests, P0

#4259 Enhance the release pipeline to ensure a failure if Jenkins fails to dispatch the job
  .github/workflows/comp-build-release-artifact.yaml
Labels: CI:UnitTests, Feature Enhancement, P0

#4261 Add concurrency group support to the PR Checks CI workflow
  .github/workflows/flow-pull-request-checks.yaml
Labels: CI:UnitTests, Feature Enhancement, P0

#4270 Fixes broken YahCli builds
  .gitignore
  gradle.properties
  test-clients/build.gradle.kts
  test-clients/yahcli/Dockerfile
  test-clients/yahcli/run/build.sh
  test-clients/yahcli/run/refresh-jar.sh
  test-clients/yahcli/yahcli
Labels: Bug, Regression, CI:UnitTests, P0

#4274 Update documentation
  docs/intellij-quickstart.md
  docs/maintainers-guide.md
Labels: CI:FinalChecks, modularization

#4178 Long term schedule transaction fees
  hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java
  hapi-fees/src/main/java/com/hedera/services/usage/schedule/ExtantScheduleContext.java
  hapi-fees/src/main/java/com/hedera/services/usage/schedule/ScheduleOpsUsage.java
  hapi-fees/src/main/java/module-info.java
  hapi-fees/src/test/java/com/hedera/services/usage/TxnUsageEstimatorTest.java
  hapi-fees/src/test/java/com/hedera/services/usage/schedule/ExtantScheduleContextTest.java
  hapi-fees/src/test/java/com/hedera/services/usage/schedule/ScheduleOpsUsageTest.java
  hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitDeterministicThrottle.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/FeeBuilder.java
  hapi-utils/src/main/java/com/hederahashgraph/fee/FeeUtils.java
  hapi-utils/src/test/java/com/hedera/services/UtilsConstructorTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/FeeBuilderTest.java
  hapi-utils/src/test/java/com/hederahashgraph/fee/FeeUtilsTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/AutoRenewCalcs.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/FeeCalcUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleCreateResourceUsage.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/util/UtilsConstructorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/config/MockGlobalDynamicProps.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/FeeCalcUtilsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/TxnResourceUsageEstimatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/UsageBasedFeeCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/schedule/txns/ScheduleCreateResourceUsageTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/charging/ContractStoragePriceTiersTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleLongTermExecutionSpecs.java
  test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4268 Set balance on synthetic creations export records
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/merkle/MerkleNetworkContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/submerkle/ExpirableTxnRecord.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/submerkle/ExpirableTxnRecordBuilderTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4230 Add `CryptoDelete` PreTransactionHandler
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/TransactionMetadata.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/SigTransactionMetadata.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/AccountStore.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/KeyOrLookupFailureReason.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/SigTransactionMetadataTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/AccountStoreTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImplTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerNotImplTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, modularization

#4183 Add HTS fungible token transfers to yahcli
  test-clients/src/main/java/com/hedera/services/bdd/spec/keys/TrieSigMapGenerator.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromFile.java
  test-clients/src/main/java/com/hedera/services/yahcli/commands/accounts/SendCommand.java
  test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigManager.java
  test-clients/src/main/java/com/hedera/services/yahcli/config/ConfigUtils.java
  test-clients/src/main/java/com/hedera/services/yahcli/suites/SendSuite.java
  test-clients/yahcli/README.md
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4262 added missing symbol to function hash
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
Labels: CI:UnitTests

#4284 Add `libs.log4j.core` as dependency in `test-clients`
  test-clients/build.gradle.kts
Labels: CI:UnitTests

#4287 Waive treasury sig if receiving NFT w/ fallback fee
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/sigs/order/SigRequirements.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/sigs/order/SigRequirementsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/factories/scenarios/CryptoTransferScenarios.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4289 Always set a PRNG synth body (without range choice)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContract.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/PrngSystemPrecompiledContractTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4286 Ensure `EthereumTransitionLogic` works during e.g. state recovery
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/ethereum/EthereumTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/span/SpanMapManager.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/ethereum/EthereumTransitionLogicTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4280 Adds `CryptoApproveAllowance` preTransactionHandler
  hapi-utils/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/SigTransactionMetadata.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/AccountStore.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/KeyOrLookupFailureReason.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/SigTransactionMetadataTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImplTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerNotImplTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, modularization

#4296 Adds `cryptoDeleteAllowance` preTransactionHandler
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImplTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerNotImplTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, modularization

#4246 Improve modularity documentation
  docs/design/design.md
  docs/design/images/hedera-high-level-architecture.png
  docs/design/images/hedera-high-level-architecture.svg
Labels: CI:FinalChecks, modularization

#4298 [HIP-583] Allow `CryptoCreate` txns with `ECDSA` key and `public address` alias when lazy creation flag is off
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4253 jackson version fixed
  settings.gradle.kts
Labels: dependencies, Improvement, CI:UnitTests, CI:FinalChecks, modularization

#4303 Fix precompile operations order execution inside `HederaEvmMessageCallProcessor`
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/execution/HederaEvmMessageCallProcessor.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmMessageCallProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/HederaMessageCallProcessorTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4292 Add EET for auto-renewal-triggered staking reward
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/charging/ContractStoragePriceTiers.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/charging/ContractStoragePriceTiersTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4188 Missing info in module definitions
  hapi-fees/src/main/java/module-info.java
  hapi-utils/src/main/java/module-info.java
  hedera-node/hedera-evm-api/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FinalChecks, modularization

#4120 Migrate EVM to 22.10.x
  hedera-node/hedera-evm-api/build.gradle.kts
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/execution/traceability/HederaEvmOperationTracer.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmOperationsUtil.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaEvmSLoadOperation.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/operations/HederaExtCodeHashOperation.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaBalanceOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaDelegateCallOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaEvmOperationsUtilTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaExtCodeCopyOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaExtCodeHashOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operation/HederaExtCodeSizeOperationTest.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/operations/HederaEvmSLoadOperationTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/AbstractRecordingCreateOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaChainIdOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaLogOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaOperationUtil.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaPrngSeedOperator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaSLoadOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaSStoreOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/AbstractRecordingCreateOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaCallCodeOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaCallOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaLogOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaOperationUtilTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaSLoadOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaSStoreOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaSelfDestructOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/operation/HederaStaticCallOperationTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4311 Update services version num
  gradle.properties
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/services/setup/InfrastructureManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesMain.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/StateModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/logic/StatusChangeListener.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/merkle/MerkleSpecialFiles.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesMainTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/keys/HederaKeyActivationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/sigs/SigOpsRegressionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/sigs/SigVerifierRegressionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/StateModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/logic/StatusChangeListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/stream/RecordsRunningHashLeafTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/CryptoConfigUtils.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4327 Mark `eet` and `itest` dependencies explicit
  test-clients/build.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4349 Check for zero-rewards-from-zero-stake condition in `stakePeriodStart` mgmt
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/pauses/HapiSpecWaitUntil.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4351 New tag to bump platform version
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4244 Refactor all read related token info Precompiles to use WorldLedgers
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/merkle/MerkleToken.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/StaticEntityAccess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/WorldLedgers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/FungibleTokenInfoPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/GetTokenExpiryInfoPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/GetTokenTypePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/IsTokenPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/NonFungibleTokenInfoPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenGetCustomFeesPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenInfoPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/StaticEntityAccessTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/WorldLedgersTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenExpiryInfoPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/GetTokenInfoPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/TokenGetCustomFeesPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/TokenPrecompileReadOperationsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/proxy/ViewExecutorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenExpiryInfoSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
  test-clients/src/main/resource/contract/contracts/TokenExpiryContract/TokenExpiryContract.bin
  test-clients/src/main/resource/contract/contracts/TokenExpiryContract/TokenExpiryContract.json
  test-clients/src/main/resource/contract/contracts/TokenExpiryContract/TokenExpiryContract.sol
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.bin
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.json
  test-clients/src/main/resource/contract/contracts/TokenInfoContract/TokenInfoContract.sol
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4305 Disable contract expiry, sidecars + don't do traceability export
  hedera-node/configuration/mainnet/bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4372 null annotations in hedera app
  hedera-node/hedera-app-spi/build.gradle.kts
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/PreHandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/States.java
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/itest/java/grpc/GrpcTransactionTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/GrpcServiceBuilder.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/KnownLengthStream.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/NoopMarshaller.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/QueryMethod.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/TransactionMethod.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
Labels: P1, Java, CI:UnitTests, Tech Debt Reduced, CI:FinalChecks, Modularization
