Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2022-10, with the labels that each got.

#4008 Disable traceability export and other cleanup
  hedera-node/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptor.java
  hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/TxnReceipt.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryRecordsHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/CryptoGcOutcome.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/logic/ServicesTxnManager.java
  hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/src/main/java/com/hedera/services/state/submerkle/CurrencyAdjustments.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptorTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryRecordsHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/ServicesTxnManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4009 Cherry-pick changes
  hedera-node/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptor.java
  hedera-node/src/main/java/com/hedera/services/legacy/core/jproto/TxnReceipt.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryRecordsHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/CryptoGcOutcome.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/logic/ServicesTxnManager.java
  hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/src/main/java/com/hedera/services/state/submerkle/CurrencyAdjustments.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptorTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryRecordsHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/ServicesTxnManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3952 Compress account balance files
  hapi-utils/src/main/java/com/hedera/services/exports/FileCompressionUtils.java
  hapi-utils/src/main/java/com/hedera/services/exports/recordstreaming/RecordStreamingUtils.java
  hapi-utils/src/test/java/com/hedera/services/recordstreaming/RecordStreamingUtilsTest.java
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/state/StateModule.java
  hedera-node/src/main/java/com/hedera/services/state/exports/SignedStateBalancesExporter.java
  hedera-node/src/main/java/com/hedera/services/state/exports/StandardSigFileWriter.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamFileWriter.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/config/MockGlobalDynamicProps.java
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java
  hedera-node/src/test/java/com/hedera/services/state/exports/StandardSigFileWriterTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamFileWriterTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/RecordFileChecker.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
Labels: CI:UnitTests, Feature Enhancement, CI:FullStackTests, CI:FinalChecks

#4001 Predefined keys and record stream forensics
  hapi-utils/src/main/java/com/hedera/services/keys/Ed25519Utils.java
  hedera-node/src/main/java/com/hedera/services/utils/forensics/DifferingEntries.java
  hedera-node/src/main/java/com/hedera/services/utils/forensics/OrderedComparison.java
  hedera-node/src/main/java/com/hedera/services/utils/forensics/RecordParsers.java
  hedera-node/src/main/java/com/hedera/services/utils/forensics/RecordStreamEntry.java
  hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleProcessingTest.java
  hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
  hedera-node/src/test/java/com/hedera/services/utils/forensics/OrderedComparisonTest.java
  hedera-node/src/test/resources/forensics/CaseOfTheObviouslyWrongNonce/node0/2022-09-19T21_09_14.082094801Z.rcd.gz
  hedera-node/src/test/resources/forensics/CaseOfTheObviouslyWrongNonce/node0/2022-09-19T21_09_17.348788413Z.rcd.gz
  hedera-node/src/test/resources/forensics/CaseOfTheObviouslyWrongNonce/node0/2022-09-19T21_09_18.321677003Z.rcd.gz
  hedera-node/src/test/resources/forensics/CaseOfTheObviouslyWrongNonce/node5/2022-09-19T21_09_14.082094801Z.rcd.gz
  hedera-node/src/test/resources/forensics/CaseOfTheObviouslyWrongNonce/node5/2022-09-19T21_09_17.348788413Z.rcd.gz
  hedera-node/src/test/resources/forensics/CaseOfTheObviouslyWrongNonce/node5/2022-09-19T21_09_18.321677003Z.rcd.gz
  test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyFactory.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/keys/KeyShape.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/keys/SigControl.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/SpecKeyFromFile.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/misc/GuidedTourRemoteSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4007 Design doc for atomic crypto transfer
  docs/design/crypto-transfer.md
  docs/design/images/crypto_wrappers.png
Labels: P2, Feature Enhancement

#4016 Reduce amount of garbage generated by UniqueTokenKey
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/virtual/UniqueTokenKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/virtual/UniqueTokenKeySerializer.java
Labels: CI:UnitTests, Performance, CI:FullStackTests, CI:FinalChecks

#4039 No traceability in high gas regime
  hapi-utils/src/main/java/com/hedera/services/throttles/DeterministicThrottle.java
  hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitBucketThrottle.java
  hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitDeterministicThrottle.java
  hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitBucketThrottleTest.java
  hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitDeterministicThrottleTest.java
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/state/tasks/SystemTask.java
  hedera-node/src/main/java/com/hedera/services/state/tasks/SystemTaskManager.java
  hedera-node/src/main/java/com/hedera/services/state/tasks/TraceabilityExportTask.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/state/tasks/SystemTaskManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/tasks/TraceabilityExportTaskTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4042 Basic interfaces needed for modularization
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/base/state/InMemoryStateImpl.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/base/state/OnDiskStateImpl.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/base/state/State.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/base/state/StateBase.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/base/state/States.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/base/state/StatesImpl.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/base/state/InMemoryStateImplTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/base/state/OnDiskStateImplTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/base/state/StateBaseTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/base/state/StatesImplTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4047 update version number of evm from v0.31.0 to v0.32.0
  docs/design/evm-versioning.md
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/ContractsV_0_32Module.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/ContractsTestComponent.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4040 Include traceability `SystemTask` for reference and possible reuse
  hapi-utils/src/main/java/com/hedera/services/throttles/DeterministicThrottle.java
  hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitBucketThrottle.java
  hapi-utils/src/main/java/com/hedera/services/throttles/GasLimitDeterministicThrottle.java
  hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitBucketThrottleTest.java
  hapi-utils/src/test/java/com/hedera/services/throttles/GasLimitDeterministicThrottleTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/tasks/SystemTask.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/tasks/SystemTaskManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/tasks/TaskModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/tasks/TraceabilityExportTask.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/tasks/SystemTaskManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/tasks/TraceabilityExportTaskTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4056 Use non-alpha SDK
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/CustomFeeMeta.java
  hedera-node/src/main/java/com/hedera/services/records/ConsensusTimeTracker.java
  hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java
  hedera-node/src/main/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedules.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/CustomFeeMetaTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersMarshalTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/StandardProcessLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedulesTest.java
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4064 Update the new develop branch to ensure all workflows are triggering appropriately
  .github/workflows/flow-build-application.yaml
  .github/workflows/flow-deploy-release-artifact.yaml
Labels: CI:UnitTests, Feature Enhancement, P0

#3973 Updating logging configs for different environment to exclude logging STATE_HASH events to swirlds.log and include STATE_HASH events for swirlds-hashstream.log
  hedera-node/configuration/compose/log4j2.xml
  hedera-node/configuration/dev/log4j2.xml
  hedera-node/configuration/mainnet/log4j2.xml
  hedera-node/configuration/preprod/log4j2.xml
  hedera-node/configuration/previewnet/log4j2.xml
  hedera-node/configuration/testnet/log4j2.xml
Labels: CI:UnitTests

#4044 Add needed feature flags for aliases work (HIP-583)
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4090 Revert "Remove `virtualMap.preferredFlushQueueSize` overrides"
  hedera-node/configuration/compose/settings.txt
  hedera-node/configuration/dev/settings.txt
  hedera-node/configuration/mainnet/settings.txt
  hedera-node/configuration/preprod/settings.txt
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/configuration/testnet/settings.txt
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4093 Switch to `iterator()`
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/utils/KeyActivationUtils.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
Labels: CI:UnitTests

#4094 Hotfixes for 0.31.1
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/utils/KeyActivationUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4061 Turn off CONTRACT_ACTION tracing in mainnet, testnet and performance testing.
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
  hedera-node/configuration/previewnet/bootstrap.properties
Labels: CI:FullStackTests, CI:FinalChecks

#4092 Refactor wrapper for atomic crypto transfer
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/codec/CryptoTransferWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/codec/TransferWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/ERCTransferPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/codec/TransferWrapperTest.java
Labels: P1, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4099 Ensure CircleCI cron tasks run on the develop branch
  .circleci/config.yml
Labels: CI:UnitTests

#3996 CryptoCreate to work with ECDSA public key aliases
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests

#4105 Externalize system account creations
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/initialization/BackedSystemAccountsCreator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/initialization/TreasuryCloner.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/initialization/BackedSystemAccountsCreatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/initialization/TreasuryClonerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4107 Add support for isApproval and hbar transfers
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4123 Resolve classpath issues with the Gradle run task
  hedera-node/hedera-mono-service/build.gradle.kts
Labels: Bug, CI:UnitTests, P0

#4130 Fix `ServicesApp` unit test
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/StateModule.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/StateModuleTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4091 Use JUnit's @TempDir for various tests
  hapi-utils/src/test/java/com/hedera/services/keys/Ed25519UtilsTest.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/serdes/FeesJsonToProtoSerdeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/config/MockGlobalDynamicProps.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/exports/SignedStateBalancesExporterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/exports/StandardSigFileWriterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/exports/ToStringAccountsExporterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/stream/RecordStreamFileWriterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/network/UpgradeActionsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/TestFileUtils.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, modularization

#4148 Fill `stakePeriodStartUpdates` array with `NA`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4149 Fill `stakePeriodStartUpdates` array with `NA`
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4118 With util congestion pricing
  hapi-utils/src/main/java/com/hedera/services/sysfiles/domain/throttling/ScaleFactor.java
  hapi-utils/src/main/java/module-info.java
  hapi-utils/src/test/java/com/hedera/services/sysfiles/domain/throttling/ScaleFactorTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/EntityType.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/CongestionMultipliers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/EntityScaleFactors.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/UtilizationScaleFactors.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/calculation/utils/TriggeredValuesParser.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/fees/congestion/TxnRateFeeMultiplierSource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/validation/UsageLimits.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/DeterministicThrottling.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/FunctionalityThrottling.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/throttling/ThrottleReqsManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/accessors/PlatformTxnAccessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/accessors/SignedTxnAccessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/utils/accessors/TxnAccessor.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/config/MockGlobalDynamicProps.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/EntityTypeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/context/properties/StandardizedPropertySourcesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/TxnRateFeeMultiplierSourceTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/EntityScaleFactorsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/fees/calculation/UtilizationScaleFactorsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/validation/UsageLimitsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/store/contracts/HederaWorldStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/throttling/DeterministicThrottlingTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/throttling/ThrottleReqsManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/utils/accessors/SignedTxnAccessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/SeededPropertySource.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/TxnUtils.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks
