Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2022-09, with the labels that each got.

#3861 Do not track actions in `ContractCallLocal`
  hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
Labels: CI:UnitTests

#3789 Compress record and sidecar files on creation
  hapi-utils/src/main/java/com/hedera/services/recordstreaming/RecordStreamingUtils.java
  hapi-utils/src/test/java/com/hedera/services/recordstreaming/RecordStreamingUtilsTest.java
  hapi-utils/src/test/resources/recordstream/2022-06-14T14_49_22.456975294Z.rcd
  hapi-utils/src/test/resources/recordstream/2022-06-30T09_07_20.147156221Z_03.rcd
  hapi-utils/src/test/resources/recordstream/2022-08-15T14_02_51.642641228Z.rcd.gz
  hapi-utils/src/test/resources/recordstream/2022-08-15T14_02_58.158861963Z_01.rcd.gz
  hapi-utils/src/test/resources/recordstream/2022-08-18T09_37_10.411994657Z.rcd
  hapi-utils/src/test/resources/recordstream/2022-08-18T09_37_10.411994657Z_01.rcd
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamFileWriter.java
  hedera-node/src/main/java/com/hedera/services/stream/RecordStreamManager.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/stream/RecordStreamFileWriterTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  test-clients/src/itest/java/SequentialIntegrationTests.java
Labels: CI:UnitTests

#3881 Ensure entities are deleted once auto-removal work begins
  hapi-utils/src/test/java/com/hedera/services/UtilsConstructorTest.java
  hedera-node/src/main/java/com/hedera/services/ServicesApp.java
  hedera-node/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/queries/AnswerService.java
  hedera-node/src/main/java/com/hedera/services/queries/answering/QueryResponseHelper.java
  hedera-node/src/main/java/com/hedera/services/queries/consensus/GetTopicInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/contract/ContractCallLocalAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/contract/GetBySolidityIdAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/contract/GetBytecodeAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/contract/GetContractInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/contract/GetContractRecordsAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/crypto/GetAccountBalanceAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/crypto/GetAccountInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/crypto/GetAccountRecordsAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/crypto/GetLiveHashAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/crypto/GetStakersAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/file/GetFileContentsAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/file/GetFileInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/meta/GetAccountDetailsAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/meta/GetExecTimeAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/meta/GetFastTxnRecordAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/meta/GetTxnReceiptAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/meta/GetTxnRecordAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/meta/GetVersionInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/schedule/GetScheduleInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/token/GetAccountNftInfosAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/token/GetTokenInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/token/GetTokenNftInfoAnswer.java
  hedera-node/src/main/java/com/hedera/services/queries/token/GetTokenNftInfosAnswer.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/ContractGC.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/TreasuryReturns.java
  hedera-node/src/main/java/com/hedera/services/state/migration/ReleaseThirtyMigration.java
  hedera-node/src/main/java/com/hedera/services/state/migration/ReleaseTwentySixMigration.java
  hedera-node/src/main/java/com/hedera/services/state/migration/StateVersions.java
  hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/queries/AbstractAnswerTest.java
  hedera-node/src/test/java/com/hedera/services/queries/crypto/GetLiveHashAnswerTest.java
  hedera-node/src/test/java/com/hedera/services/queries/crypto/GetStakersAnswerTest.java
  hedera-node/src/test/java/com/hedera/services/queries/meta/GetFastTxnRecordAnswerTest.java
  hedera-node/src/test/java/com/hedera/services/queries/token/GetAccountNftInfosAnswerTest.java
  hedera-node/src/test/java/com/hedera/services/queries/token/GetTokenNftInfosAnswerTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/ContractGCTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/TreasuryReturnsTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/ReleaseThirtyMigrationTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/ReleaseTwentySixMigrationTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/StateVersionsTest.java
  hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  hedera-node/src/test/java/com/hedera/services/utils/UtilsConstructorTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3856 03749 transaction logging
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/state/logic/BlockManager.java
  hedera-node/src/main/java/com/hedera/services/state/logic/RecordStreaming.java
  hedera-node/src/main/java/com/hedera/services/txns/span/ExpandHandleSpan.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/BlockManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/logic/RecordStreamingTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenPrecompileReadOperationsTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenAndTypeCheckSuite.java
Labels: CI:UnitTests

#3879 Add `NonHapiFeeCharging`
  hedera-node/src/main/java/com/hedera/services/fees/charging/NonHapiFeeCharging.java
  hedera-node/src/main/java/com/hedera/services/fees/charging/RecordedStorageFeeCharging.java
  hedera-node/src/main/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptor.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryRecordsHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
  hedera-node/src/test/java/com/hedera/services/fees/charging/RecordedStorageFeeChargingTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/interceptors/StakingAccountsCommitInterceptorTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/AutoExpiryCycleTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryRecordsHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/AccountAutoRenewalSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3899 De-alias accounts in contract actions and state changes
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSStoreOperation.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/operation/HederaSStoreOperationTest.java
Labels: Bug, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3907 Rationalize treatment of expired entity lifetimes
  hedera-node/src/main/java/com/hedera/services/fees/charging/RecordedStorageFeeCharging.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
  hedera-node/src/test/java/com/hedera/services/fees/charging/RecordedStorageFeeChargingTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/AutoExpiryCycleTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3801 [virtual_nfts][5] Replacing usage of MerkleUniqueToken with an intermediate adapter to smooth code transition for virtualization nfts
  hedera-node/src/main/java/com/hedera/services/context/init/StoreInitializationFlow.java
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/ledger/HederaLedger.java
  hedera-node/src/main/java/com/hedera/services/ledger/MerkleAccountScopedCheck.java
  hedera-node/src/main/java/com/hedera/services/ledger/TransferLogic.java
  hedera-node/src/main/java/com/hedera/services/ledger/backing/BackingNfts.java
  hedera-node/src/main/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptor.java
  hedera-node/src/main/java/com/hedera/services/ledger/properties/NftProperty.java
  hedera-node/src/main/java/com/hedera/services/state/migration/UniqueTokenAdapter.java
  hedera-node/src/main/java/com/hedera/services/store/ReadOnlyTokenStore.java
  hedera-node/src/main/java/com/hedera/services/store/StoresModule.java
  hedera-node/src/main/java/com/hedera/services/store/TypedTokenStore.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/WorldLedgers.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/tokens/HederaTokenStore.java
  hedera-node/src/test/java/com/hedera/services/context/init/StoreInitializationFlowTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/BaseHederaLedgerTestHelper.java
  hedera-node/src/test/java/com/hedera/services/ledger/HederaLedgerLiveTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/LedgerBalanceChangesTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/MerkleAccountScopedCheckTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/TransferLogicTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/backing/BackingNftsTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/backing/HashMapBackingNfts.java
  hedera-node/src/test/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptorTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/properties/NftPropertyTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/UniqueTokenAdapterTest.java
  hedera-node/src/test/java/com/hedera/services/store/ReadOnlyTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/store/TypedTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/AbstractLedgerWorldUpdaterTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/AbstractStackedLedgerUpdaterTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/MutableEntityAccessTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/WorldLedgersTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/AssociatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/BurnPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/CreatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DeleteTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/DissociatePrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/FreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/GrantKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/IsFrozenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/IsKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/MintPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/PausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/RevokeKycPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenUpdateKeysPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenUpdateLogicTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenUpdatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnfreezeTokenPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UnpausePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/UpdateTokenExpiryInfoPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/WipeNonFungiblePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/tokens/HederaTokenStoreTest.java
  hedera-node/src/test/java/com/hedera/services/txns/crypto/validators/ApproveAllowanceChecksTest.java
  hedera-node/src/test/java/com/hedera/services/txns/crypto/validators/DeleteAllowanceChecksTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3910 update token create and token update precompile selectors to match documentation/protobuf
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenCreatePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/TokenUpdatePrecompile.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/CreatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/TokenUpdatePrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/codec/DecodingFacadeTest.java
Labels: CI:UnitTests

#3890 Stabilize traceability suite
  hapi-utils/src/main/java/com/hedera/services/recordstreaming/RecordStreamingUtils.java
  test-clients/src/itest/java/SequentialIntegrationTests.java
  test-clients/src/itest/resources/network/config/bootstrap.properties
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3917 Traceability "invalid_solidity_address action" value correction
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java
  test-clients/src/main/resource/contract/contracts/RevertingContract/RevertingContract.bin
  test-clients/src/main/resource/contract/contracts/RevertingContract/RevertingContract.json
  test-clients/src/main/resource/contract/contracts/RevertingContract/RevertingContract.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3923 Check for `null` bytecode in traceability migration
  hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
Labels: P1, Bug, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3919 03918 actions clear failed recipient contract create
  hedera-node/src/main/java/com/hedera/services/contracts/execution/traceability/HederaTracer.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/HederaTracerTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3945 Fix migration issues
  hedera-node/src/main/java/com/hedera/services/state/migration/ReleaseThirtyMigration.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/test/java/com/hedera/services/state/migration/ReleaseThirtyMigrationTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3944 Fix contract traceability `state changes` sorting logic
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaOperationUtil.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/HederaWorldState.java
  hedera-node/src/main/java/com/hedera/services/utils/BytesComparator.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/HederaWorldStateTest.java
  hedera-node/src/test/java/com/hedera/services/utils/BytesComparatorTest.java
Labels: Bug, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3908 Allocate a reduced `consensusTimeStamp` to accommodate triggered transactions in balance file
  hedera-node/src/main/java/com/hedera/services/state/logic/StandardProcessLogic.java
  hedera-node/src/test/java/com/hedera/services/state/logic/StandardProcessLogicTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3901 Add hedera app submodules to prep for refactoring
  hedera-node/hedera-app-api/build.gradle.kts
  hedera-node/hedera-app-api/src/main/java/com/hedera/services/api/PlaceholderApi.java
  hedera-node/hedera-app-api/src/main/java/com/hedera/services/api/package-info.java
  hedera-node/hedera-app-api/src/main/java/module-info.java
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/main/java/com/hedera/services/api/implementation/PlaceholderImplementation.java
  hedera-node/hedera-app/src/main/java/com/hedera/services/api/implementation/package-info.java
  hedera-node/hedera-app/src/main/java/module-info.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3969 Move re-usable test helpers under `TestUtils`, clean up rehydrated calldata mgmt
  hedera-node/src/main/java/com/hedera/services/txns/span/SpanMapManager.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/PlatformTxnAccessor.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/SignedTxnAccessor.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/TxnAccessor.java
  hedera-node/src/test/java/com/hedera/services/txns/span/EthereumSpanMapManagerTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/PlatformTxnAccessorTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/SignedTxnAccessorTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/TokenWipeAccessorTest.java
  hedera-node/src/test/java/com/hedera/test/utils/TxnUtils.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3830 [virtual_nfts][6] Refactor usage of MerkleMap<EntityNumPair, MerkleUniqueToken> to use an intermediate adaptor.
  hedera-node/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/src/main/java/com/hedera/services/context/ImmutableStateChildren.java
  hedera-node/src/main/java/com/hedera/services/context/MutableStateChildren.java
  hedera-node/src/main/java/com/hedera/services/context/StateChildren.java
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/ledger/backing/BackingNfts.java
  hedera-node/src/main/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptor.java
  hedera-node/src/main/java/com/hedera/services/ledger/interceptors/UniqueTokensLinkManager.java
  hedera-node/src/main/java/com/hedera/services/state/StateModule.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/UniqueTokensListMutation.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/TreasuryReturnHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/TreasuryReturns.java
  hedera-node/src/main/java/com/hedera/services/state/migration/ReleaseThirtyMigration.java
  hedera-node/src/main/java/com/hedera/services/state/migration/UniqueTokenAdapter.java
  hedera-node/src/main/java/com/hedera/services/state/migration/UniqueTokenMapAdapter.java
  hedera-node/src/main/java/com/hedera/services/state/virtual/UniqueTokenValue.java
  hedera-node/src/main/java/com/hedera/services/store/StoresModule.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/StaticEntityAccess.java
  hedera-node/src/main/java/com/hedera/services/store/models/NftId.java
  hedera-node/src/main/java/com/hedera/services/utils/NonAtomicReference.java
  hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/src/test/java/com/hedera/services/context/ImmutableStateChildrenTest.java
  hedera-node/src/test/java/com/hedera/services/context/MutableStateChildrenTest.java
  hedera-node/src/test/java/com/hedera/services/context/init/StateInitializationFlowTest.java
  hedera-node/src/test/java/com/hedera/services/context/primitives/SignedStateViewFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/context/primitives/StateViewTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/backing/BackingNftsTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/interceptors/LinkAwareUniqueTokensCommitInterceptorTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/interceptors/UniqueTokensLinkManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/UniqueTokensListMutationTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/TreasuryReturnHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/TreasuryReturnsTest.java
  hedera-node/src/test/java/com/hedera/services/state/forensics/HashLoggerTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/ReleaseThirtyMigrationTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/UniqueTokenAdapterTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/UniqueTokenMapAdapterTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/StaticEntityAccessTest.java
  hedera-node/src/test/java/com/hedera/services/store/models/NftIdTest.java
  hedera-node/src/test/java/com/hedera/services/utils/NonAtomicReferenceTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3978 Add hedera-evm / hedera-evm-api submodules
  hedera-node/hedera-evm-api/build.gradle.kts
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/PlaceholderApi.java
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/package-info.java
  hedera-node/hedera-evm-api/src/main/java/module-info.java
  hedera-node/hedera-evm/build.gradle.kts
  hedera-node/hedera-evm/src/main/java/com/hedera/services/evm/implementation/PlaceholderImplementation.java
  hedera-node/hedera-evm/src/main/java/com/hedera/services/evm/implementation/package-info.java
  hedera-node/hedera-evm/src/main/java/module-info.java
  settings.gradle.kts
Labels: CI:UnitTests

#3981 Update services version
  .github/workflows/comp-build-release-artifact.yaml
  gradle.properties
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3983 Remove FOSSA support from the CI pipelines
  .github/workflows/comp-compile-application-code.yaml
  compose-build.sh
Labels: Bug, CI:UnitTests, P0

#3940 Traceability test plan implementation
  test-clients/src/eet/java/EndToEndTests.java
  test-clients/src/itest/java/SequentialIntegrationTests.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/ContractTraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/NewTraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/resource/contract/contracts/PrecompileCaller/PrecompileCaller.bin
  test-clients/src/main/resource/contract/contracts/PrecompileCaller/PrecompileCaller.json
  test-clients/src/main/resource/contract/contracts/PrecompileCaller/PrecompileCaller.sol
  test-clients/src/test/java/EndToEndPackageRunner.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3976 Fix wrong emitter address in `approve` and `approveForAll` precompiles
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ApprovePrecompile.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC721PrecompilesTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractLogAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
Labels: Bug, CI:UnitTests, CI:FullStackTests, Hedera Smart Contract Service, CI:FinalChecks

#3974 HTS precompile `transferFrom` support
  hapi-utils/src/main/java/com/hedera/services/contracts/ParsingConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/AbiConstants.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/ERCTransferPrecompileTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/HTSPrecompiledContractTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/HtsTransferFrom/HtsTransferFrom.bin
  test-clients/src/main/resource/contract/contracts/HtsTransferFrom/HtsTransferFrom.json
  test-clients/src/main/resource/contract/contracts/HtsTransferFrom/HtsTransferFrom.sol
Labels: CI:UnitTests, New Feature, CI:FullStackTests, Hedera Smart Contract Service, CI:FinalChecks

#3992 Merge expiry txn id fix
  hedera-node/src/jmh/java/com/hedera/services/mocks/MockRecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/records/RecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/EntityAutoExpiry.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryRecordsHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/RemovalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/TreasuryReturns.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/src/main/java/com/hedera/services/state/submerkle/TxnId.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/src/test/java/com/hedera/services/records/TxnAwareRecordsHistorianTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/EntityAutoExpiryTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryProcessTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryRecordsHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/RemovalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/TreasuryReturnsTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/TxnIdTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/AutoRemovalCasesSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3843 [virtual_nfts][7] Add and integrate virtual NFT migration when toggled on.
  hedera-node/src/main/java/com/hedera/services/ServicesState.java
  hedera-node/src/main/java/com/hedera/services/state/migration/UniqueTokenAdapter.java
  hedera-node/src/main/java/com/hedera/services/state/migration/UniqueTokensMigrator.java
  hedera-node/src/main/java/com/hedera/services/store/StoresModule.java
  hedera-node/src/test/java/com/hedera/services/ServicesStateTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/UniqueTokenAdapterTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/UniqueTokensMigratorTest.java
  hedera-node/src/test/java/com/hedera/services/store/StoresModuleTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3991 Align expiry record `TransactionID` with HIP-449
  hedera-node/src/jmh/java/com/hedera/services/mocks/MockRecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/records/RecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/records/TxnAwareRecordsHistorian.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/EntityAutoExpiry.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/ExpiryRecordsHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/RemovalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/removal/TreasuryReturns.java
  hedera-node/src/main/java/com/hedera/services/state/expiry/renewal/RenewalHelper.java
  hedera-node/src/main/java/com/hedera/services/state/migration/MigrationRecordsManager.java
  hedera-node/src/main/java/com/hedera/services/state/submerkle/TxnId.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/utils/MiscUtils.java
  hedera-node/src/test/java/com/hedera/services/records/TxnAwareRecordsHistorianTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/EntityAutoExpiryTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryProcessTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/ExpiryRecordsHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/RemovalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/removal/TreasuryReturnsTest.java
  hedera-node/src/test/java/com/hedera/services/state/expiry/renewal/RenewalHelperTest.java
  hedera-node/src/test/java/com/hedera/services/state/migration/MigrationRecordsManagerTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/TxnIdTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/utils/MiscUtilsTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/AutoRemovalCasesSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3977 Fix traceability suite race condition
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/resource/bootstrap.properties
Labels: Test Development, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3993 Add Maven Central publishing support
  .github/workflows/flow-deploy-release-artifact.yaml
  buildSrc/src/main/kotlin/com.hedera.hashgraph.aggregate-reports.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.maven-publish.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
  hapi-fees/build.gradle.kts
  hapi-utils/build.gradle.kts
  hedera-node/build.gradle.kts
  hedera-node/hedera-app-api/build.gradle.kts
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-evm-api/build.gradle.kts
  hedera-node/hedera-evm-api/src/main/java/module-info.java
  hedera-node/hedera-evm/build.gradle.kts
  test-clients/build.gradle.kts
Labels: CI:UnitTests, New Feature, P0

#3967 HIP-542: Payer sponsored auto creation with HTS assets
  hedera-node/src/main/java/com/hedera/services/context/primitives/StateView.java
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/AliasResolver.java
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/RoyaltyFeeAssessor.java
  hedera-node/src/main/java/com/hedera/services/ledger/BalanceChange.java
  hedera-node/src/main/java/com/hedera/services/ledger/TransferLogic.java
  hedera-node/src/main/java/com/hedera/services/sigs/order/SigRequirements.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/InfrastructureFactory.java
  hedera-node/src/main/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/AliasResolverTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/RoyaltyFeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/BalanceChangeTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/LedgerBalanceChangesTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/TransactionalLedgerTest.java
  hedera-node/src/test/java/com/hedera/services/ledger/TransferLogicTest.java
  hedera-node/src/test/java/com/hedera/services/sigs/order/SigRequirementsTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/AbstractLedgerWorldUpdaterTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/InfrastructureFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
  hedera-node/src/test/java/com/hedera/test/factories/scenarios/CryptoTransferScenarios.java
  hedera-node/src/test/java/com/hedera/test/factories/txns/TinyBarsFromTo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AutoAssocAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/TokenMovement.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3999 Maven Central release workflow failed on push due to missing fields
  .github/workflows/flow-deploy-release-artifact.yaml
Labels: Bug, CI:UnitTests, P0

#3970 Add feature flag for enabling HTS auto creations
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/txns/crypto/AutoCreationLogic.java
  hedera-node/src/main/java/com/hedera/services/utils/accessors/TxnAccessor.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/txns/crypto/AutoCreationLogicTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/PlatformTxnAccessorTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/resource/bootstrap.properties
  test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3989 Allow zero unit token transfers
  hedera-node/src/main/java/com/hedera/services/ledger/PureTransferSemanticChecks.java
  hedera-node/src/main/java/com/hedera/services/store/models/Token.java
  hedera-node/src/main/java/com/hedera/services/txns/token/TokenOpsValidator.java
  hedera-node/src/test/java/com/hedera/services/ledger/PureTransferSemanticChecksTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/BurnLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/MintLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenBurnTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenMintTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenOpsValidatorTest.java
  hedera-node/src/test/java/com/hedera/services/txns/token/TokenWipeTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#3911 EVM versioning and Paris Updates
  docs/design/evm-versioning.md
  hedera-node/src/main/java/com/hedera/services/context/properties/BootstrapProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/GlobalDynamicProperties.java
  hedera-node/src/main/java/com/hedera/services/context/properties/PropertyNames.java
  hedera-node/src/main/java/com/hedera/services/contracts/ContractsModule.java
  hedera-node/src/main/java/com/hedera/services/contracts/ContractsV_0_30Module.java
  hedera-node/src/main/java/com/hedera/services/contracts/ContractsV_0_31Module.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/CallEvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/CreateEvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaBalanceOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallCodeOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaCallOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaChainIdOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaDelegateCallOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaExtCodeCopyOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaExtCodeHashOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaExtCodeSizeOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaPrngSeedOperator.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaSelfDestructOperation.java
  hedera-node/src/main/java/com/hedera/services/contracts/operation/HederaStaticCallOperation.java
  hedera-node/src/main/resources/bootstrap.properties
  hedera-node/src/test/java/com/hedera/services/context/properties/BootstrapPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/ContractsModuleTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/ContractsTestComponent.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PrngSeedOperationSuite.java
  test-clients/src/main/resource/bootstrap.properties
  test-clients/src/main/resource/contract/contracts/PrngSeedOperationContract/PrngSeedOperationContract.bin
  test-clients/src/main/resource/contract/contracts/PrngSeedOperationContract/PrngSeedOperationContract.sol
  test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests

#3943 Update alias design with additional notes
  docs/design/alias-configuration.md
Labels: P2, Limechain, CI:UnitTests, Design

#4003 Implement HIP-573 test plan
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessor.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessorTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/CustomFeeSpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/CustomFeeTests.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4006 Implement HIP-573
  hapi-fees/src/main/java/com/hedera/services/pricing/BaseOperationUsage.java
  hedera-node/src/main/java/com/hedera/services/fees/CustomFeePayerExemptions.java
  hedera-node/src/main/java/com/hedera/services/fees/StandardCustomPayerExemptions.java
  hedera-node/src/main/java/com/hedera/services/grpc/GrpcModule.java
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FeeAssessor.java
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FixedFeeAssessor.java
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessor.java
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/HtsFeeAssessor.java
  hedera-node/src/main/java/com/hedera/services/grpc/marshalling/RoyaltyFeeAssessor.java
  hedera-node/src/main/java/com/hedera/services/state/submerkle/FcCustomFee.java
  hedera-node/src/test/java/com/hedera/services/fees/StandardCustomExemptionsTest.java
  hedera-node/src/test/java/com/hedera/services/fees/calculation/AccessorBasedUsagesTest.java
  hedera-node/src/test/java/com/hedera/services/fees/calculation/utils/OpUsageCtxHelperTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/CustomFeeMetaTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/CustomSchedulesManagerTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FixedFeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/FractionalFeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/HbarFeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/HtsFeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/ImpliedTransfersTest.java
  hedera-node/src/test/java/com/hedera/services/grpc/marshalling/RoyaltyFeeAssessorTest.java
  hedera-node/src/test/java/com/hedera/services/sigs/metadata/TokenMetaUtilsTest.java
  hedera-node/src/test/java/com/hedera/services/state/merkle/MerkleTokenTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/FcCustomFeeSerdeTest.java
  hedera-node/src/test/java/com/hedera/services/state/submerkle/FcCustomFeeTest.java
  hedera-node/src/test/java/com/hedera/services/txns/crypto/CryptoTransferTransitionLogicTest.java
  hedera-node/src/test/java/com/hedera/services/txns/customfees/FcmCustomFeeSchedulesTest.java
  hedera-node/src/test/java/com/hedera/services/txns/schedule/ScheduleProcessingTest.java
  hedera-node/src/test/java/com/hedera/services/txns/span/SpanMapManagerTest.java
  hedera-node/src/test/java/com/hedera/services/utils/accessors/SignedTxnAccessorTest.java
  hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenCreateScenarios.java
  hedera-node/src/test/java/com/hedera/test/factories/scenarios/TokenFeeScheduleUpdateScenarios.java
  hedera-node/src/test/java/com/hedera/test/factories/scenarios/TxnHandlingScenario.java
  hedera-node/src/test/java/com/hedera/test/utils/SeededPropertySource.java
  hedera-node/src/test/resources/serdes/FcCustomFee-v3-sn0.hex
  hedera-node/src/test/resources/serdes/FcCustomFee-v3-sn1.hex
  hedera-node/src/test/resources/serdes/FcCustomFee-v3-sn2.hex
  hedera-node/src/test/resources/serdes/FcCustomFee-v3-sn3.hex
  hedera-node/src/test/resources/serdes/FcCustomFee-v3-sn4.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn0.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn1.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn2.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn3.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn4.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn5.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn7.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn8.hex
  hedera-node/src/test/resources/serdes/MerkleToken-v5-sn9.hex
  test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks
