Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-11, with the labels that each got.

#9481 9479: Add more logs to debug virtual map reconnect issues
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleTreeVisualizer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: Platform Reconnect, Platform Virtual Map, Platform Data Structures

#9569 Populate evm function result on failing eth transaction (modulatized …
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/ContextTransactionProcessor.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
Labels: Bug, Limechain

#9586 9584: Backport the fix for 9479 to release/0.43
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/LearningSynchronizer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleTreeVisualizer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: Platform Reconnect, Platform Virtual Map, Platform Data Structures

#9490 Support for @Tag in HapiTestEngine
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngineExecutionContext.java
Labels: Limechain, Modularization

#9379 Implement ContractUpdateHandler.handle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/SingleTransactionRecordBuilderImpl.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/TokenServiceApi.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
Labels: Limechain, Modularization

#9621 Fix More Txn Receipt Tests
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnReceiptRegression.java
Labels: Modularization

#9672 Add comments to failing record regression tests
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TxnRecordRegression.java
Labels: Modularization

#9742 fix: issue with workflow due to missing brace
  .github/workflows/node-zxc-build-release-artifact.yaml
Labels: Bug, P0

#9743 fix: issue with workflow due to missing brace
  .github/workflows/node-zxc-build-release-artifact.yaml
Labels: Bug, P0

#9723 Preserve logic via dependency migration test
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/OrderedServiceMigrator.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/DependencyMigrationTest.java
Labels: Modularization

#8733 Support "isolated" flag on HapiTestSuite
  hedera-node/configuration/dev/settings.txt
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/impl/netty/NettyGrpcServerManager.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngineExecutionContext.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEnv.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestNode.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/InProcessHapiTestNode.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/SubProcessHapiTestNode.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/LifecycleOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/ops/WaitForActiveOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/ops/WaitForFreezeOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/ops/WaitForShutdownOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/selectors/NodeSelector.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/selectors/SelectAll.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/selectors/SelectByName.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/selectors/SelectByNodeId.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/lifecycle/selectors/SelectByOperatorAccountId.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/freeze/CryptoTransferThenFreezeTest.java
  hedera-node/test-clients/src/main/java/module-info.java
Labels: Limechain

#9625 Fix E2E tests in TokenUpdatePrecompileSuite
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleSystemContractOperations.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/QuerySystemContractOperations.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/SystemContractOperations.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/PrngSystemContract.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbstractNonRevertibleTokenViewCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenkey/TokenKeyTranslator.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaWorldUpdater.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/state/ProxyWorldUpdater.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleSystemContractOperationsTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/QuerySystemContractOperationsTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/state/ProxyWorldUpdaterTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
Labels: Limechain

#9682 Add support for underscored numerical literals in Configuration Converters
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/converters/IntegerConverter.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/converters/LongConverter.java
  platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/converters/IntegerConverterTest.java
  platform-sdk/swirlds-config-impl/src/test/java/com/swirlds/config/impl/converters/LongConverterTest.java
Labels: Limechain

#9686 Fix E2E tests in TokenExpiryInfoSuite
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/tokenexpiry/TokenExpiryCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenExpiryInfoSuite.java
Labels: Limechain

#9735 Add test to confirm preceding child record for HTS transfer
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
Labels: Limechain

#9308 Validations for dispatchSyntheticTxn
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/SolvencyPreCheck.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
  hedera-node/hedera-app/src/xtest/java/common/BaseScaffoldingModule.java
Labels: Limechain

#9632 Fix handling of custom fees in token create transaction builder
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/CreateDecoder.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/CreateSyntheticTxnFactory.java
Labels: Limechain

#9780 9477: Direct memory / data source leak if teacher becomes inaccessible during reconnect
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceMetricsTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: Platform Reconnect, Platform Virtual Map, Platform Data Structures

#9649 Fix ApproveAllowanceSuite tests
  hedera-node/hedera-app/src/xtest/java/common/AbstractXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/AbstractContractXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/AssortedOpsXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/AssortedOpsXTestConstants.java
  hedera-node/hedera-app/src/xtest/java/contract/BurnsXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/ClassicViewsXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/ContractLimitsXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/Erc721XTest.java
  hedera-node/hedera-app/src/xtest/java/contract/Erc721XTestConstants.java
  hedera-node/hedera-app/src/xtest/java/contract/FuseXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/MiscViewsXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/TestApproverXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/XTestConstants.java
  hedera-node/hedera-app/src/xtest/java/contract/approvals/ApproveAllowanceXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/approvals/ApproveAllowanceXTestConstants.java
  hedera-node/hedera-app/src/xtest/resources/initcode/HtsApproveAllowance.bin
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/AbiConstants.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/LogBuilder.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/isapprovedforall/IsApprovedForAllCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/isapprovedforall/IsApprovedForAllTranslator.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/HtsSystemContractTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/HtsCallAttemptTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/HtsCallTestBase.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCallTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/isoperator/IsApprovedForAllCallTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/setapproval/SetApprovalForAllCallTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
Labels: Limechain

#9707 Fix cannotUseMoreThanChildContractLimit test
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HederaEvmTransactionResult.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
Labels: Limechain

#9630 Fix tests from GasLimitThrottlingSuite
  hedera-node/test-clients/src/eet/java/EndToEndTests.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/throttling/GasLimitThrottlingSuite.java
Labels: Limechain

#9800 9764: ReconnectNodeRemover.getRecordsToDelete() loops forever
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/StoppableThreadImpl.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskVirtualKeySet.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ReconnectNodeRemover.java
Labels: Platform Reconnect, Platform Virtual Map, Platform Data Structures

#9817 Fix transfer tests for fees in LeakyContractTestsSuite
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: Limechain

#9829 9477: Direct memory / data source leak if teacher becomes inaccessible during reconnect
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceMetricsTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: Platform Reconnect, Platform Virtual Map, Platform Data Structures

#9732 Fix ContractHTSSuite tests
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersCall.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/fixtures/FakeCryptoTransferRecordBuilder.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/records/CryptoTransferRecordBuilder.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
Labels: Limechain

#9850 Fix `updateHappyPath` in `TokenUpdateSpec`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/token/txns/TokenUpdateResourceUsage.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: Limechain

#9832 Fix `customFeesOnlyUpdatableWithKey` in `TokenUpdateSpec`
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
  hedera-node/test-clients/src/main/resource/spec-default.properties
Labels: Limechain

#9847 Fix ContractUpdateSuite and address ContractUpdateHandle comments
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/infra/HevmTransactionFactoryTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/api/TokenServiceApiImpl.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/api/TokenServiceApiImplTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/api/TokenServiceApi.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
Labels: Limechain, Modularization

#9541 Enable leftover tests from TokenAssociateSpecs
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
Labels: Limechain

#9877 Fix `gasLimitOverMaxGasLimitFailsPrecheck` and `createGasLimitOverMaxGasLimitFailsPrecheck`
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/spec-default.properties
Labels: Limechain

#9927 Support @Tag annotation on a class level
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java
Labels: Limechain, Modularization

#9870 HIP-796 `HapiSpec`'s
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountInfoAsserts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/TokenMovement.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/GeneralSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/Hip796Verbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/InterPartitionMovementSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/LockSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/MiscSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/PartitionAssociationsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/PartitionsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/TokenKeysDefinitionSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/TransfersSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/operations/DesiredAccountTokenRelation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/operations/DesiredPartition.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/operations/TokenAttributeNames.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/operations/TokenDefOperation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/hip796/operations/TokenFeature.java
Labels: HIP-796

#9913 Fix `standardImmutabilitySemanticsHold` in `TokenUpdateSpec`
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: Limechain

#9884 Fix HAPI tests in LeakyContractTestSuite.
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: Limechain

#9956 Move `Hip17UnhappyAccountsSuite` tests for expiry to new suite
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyAccountsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUnhappyAccountsSuite.java
Labels: Limechain

#9897 Add migration properties needed for synthetic records
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/BlockRecordManager.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/BlockRecordService.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/ReadableBlockRecordStore.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/BlockRecordManagerImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/ConsensusTimeHook.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/StakingPeriodTimeHook.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/record/GenesisRecordsConsensusHook.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/ReadableBlockRecordStoreTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/records/impl/codec/BlockInfoTranslatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/StakingPeriodTimeHookTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordManagerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/BlockRecordServiceTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/record/GenesisRecordsConsensusHookTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/EndOfStakingPeriodUpdater.java
  settings.gradle.kts
Labels: Modularization

#9792 `CreatePrecompileSuite` fixed E2E tests
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallAttempt.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallFactory.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/ClassicCreatesCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/CreateTranslator.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/HtsCallAttemptTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/create/ClassicCreatesCallTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
Labels: Limechain

#9042 Fix ContractRecordSanityCheckSuite
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/ContractRecordsSanityCheckSuite.java
Labels: Limechain

#10094 Add negative X tests scenarios for key verification on token update
  hedera-node/hedera-app/src/xtest/java/contract/UpdatesExpiryXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/UpdatesKeysXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/UpdatesXTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/UpdateDecoder.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/update/UpdateTranslator.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/update/UpdateDecoderTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/update/UpdateTranslatorTest.java
Labels: Limechain, Modularization

#10092 Provide more X test for burnToken key verification
  hedera-node/hedera-app/src/xtest/java/contract/BurnsXTest.java
Labels: Limechain, Modularization

#9791 fix: enable tests from Issue2051spec
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractDeleteHandlerTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue2051Spec.java
Labels: Limechain

#9937 Provide more X tests for Non-payer Key verification
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
  hedera-node/hedera-app/src/xtest/java/contract/AbstractContractXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/FreezeUnfreezeXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/GrantRevokeKycXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/MintsXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/PausesXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/WipeXTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
Labels: Limechain

#9955 Fix `whitelistpositivecase` test in LeakyContractTestsSuite
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/utils/FrameUtils.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/utils/FrameUtilsTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: Limechain

#10122 Add negative X tests scenarios for key verification on token create
  hedera-node/hedera-app/src/xtest/java/contract/CreatesERC20XTest.java
  hedera-node/hedera-app/src/xtest/java/contract/CreatesERC721XTest.java
  hedera-node/hedera-app/src/xtest/java/contract/CreatesXTest.java
  hedera-node/hedera-app/src/xtest/java/contract/CreatesXTestConstants.java
Labels: Limechain, Modularization

#10154 10153: Comparator wrapped in lambda generates lots of garbage
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java
Labels: Performance, Modularization

#9965 Fix CongestionPricingSuite
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/fees/FeeCalculator.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/fees/FakeFeeCalculator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/BootstrapConfigProviderImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/ChildFeeContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeCalculatorImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeeManager.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/NoOpFeeCalculator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/congestion/CongestionMultipliers.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/congestion/EntityUtilizationMultiplier.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/ChildFeeContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/FeeCalculatorImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/congestion/CongestionMultipliersTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/congestion/EntityUtilizationMultiplierTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacilityTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
  hedera-node/hedera-app/src/xtest/java/common/BaseScaffoldingModule.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/ProfileConverter.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/HederaConfig.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/types/Profile.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/converter/ProfileConverterTest.java
  hedera-node/hedera-config/src/testFixtures/java/com/hedera/node/config/testfixtures/HederaTestConfigBuilder.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ReadableTopicStoreImpl.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ReadableTopicStoreImplTest.java
  hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/ReadableTopicStore.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/ReadableFileStoreImplTest.java
  hedera-node/hedera-file-service/src/main/java/com/hedera/node/app/service/file/ReadableFileStore.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaOperations.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaOperationsTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableNftStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableNftStore.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAccountStoreImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableTokenStoreImplTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableNftStore.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableTokenStore.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/CongestionPricingSuite.java
Labels: Limechain

#10077 Provide more Mint X tests for Non-payer key verification
  hedera-node/hedera-app/src/xtest/java/contract/MintsXTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
Labels: Limechain

#9995 Enable tests from ERCPrecompileSuite
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/allowance/GetAllowanceCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/allowance/GetAllowanceCallTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/setapproval/SetApprovalForAllCallTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
Labels: Limechain

#10158 fix: 09872: MerkleSynchronizationException: Timed out waiting to supply a new leaf to the hashing iterator buffer
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ConcurrentBlockingIterator.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ConcurrentBlockingIteratorTest.java
Labels: Platform Reconnect
