Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-01, with the labels that each got.

#4504 minor changes in token update precompile
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/KeyValueWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TokenUpdatePrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdatePrecompileTest.java
Labels: CI:UnitTests

#4557 Fix failing services tests
  test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4559 Relocate sig reqs pre-handlers
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/PreHandleDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/StoreCache.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/HandlersFactory.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/SchedulePreTransactionHandlerImpl.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleSignHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/module-info.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/SchedulePreTransactionHandlerImplTest.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleCreateHandlerTest.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleHandlerTestBase.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleSignHandlerTest.java
  hedera-node/hedera-schedule-service-impl/src/test/java/module-info.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/CryptoPreTransactionHandlerImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoApproveAllowanceHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteAllowanceHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/CryptoPreTransactionHandlerImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/CryptoPreTransactionHandlerNotImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/module-info.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/CryptoPreTransactionHandler.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/CryptoService.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4562 Don't delete summary test files from google storage during rsycn process
  .circleci/config.yml
Labels: CI:UnitTests, CI:FinalChecks

#4508 CREATE2 contract deploy to hollow account
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldStateTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_32Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV032.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaStackedWorldStateUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/SolvencyPrecheck.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsV032ModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV032Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/HederaStackedWorldStateUpdaterTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/ReferenceType.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: Limechain, CI:UnitTests

#4558 Update platform and services version numbers
  buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
  gradle.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapter.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/AutoRenewCalcsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingNftsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StatusChangeListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/ResponsibleVMapUser.java
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4570 Update platform and services version numbers (#4558)
  buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
  gradle.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapter.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/AutoRenewCalcsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingNftsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StatusChangeListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/ResponsibleVMapUser.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4571 Add override for class path `state.mainClassNameOverride`
  hedera-node/configuration/compose/settings.txt
  hedera-node/configuration/mainnet/settings.txt
  hedera-node/configuration/preprod/settings.txt
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/configuration/testnet/settings.txt
  hedera-node/settings.txt
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4492 Create FileSignTool to support v6 record stream file
  hedera-node/hapi-utils/build.gradle.kts
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Labels: CI:UnitTests, CI:FinalChecks

#4572 Hollow account id fix
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperation.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperationTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4569 Enable HIP-583 feature flags for previewnet and preprod
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
Labels: CI:UnitTests

#4574 Bump platform version
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4576 Update workflows to use patched test reporting step
  .github/workflows/comp-compile-application-code.yaml
  buildSrc/src/main/kotlin/Utils.kt
  gradle.properties
Labels: CI:UnitTests

#4581 Annotate leaky specs
  .env
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/Ed25519Utils.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/keys/Ed25519UtilsTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  test-clients/src/itest/java/ConcurrentSuites.java
  test-clients/src/itest/java/SequentialSuites.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/annotations/LeakyFeeSchedule.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/LogsSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountUpdateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/fees/SpecialAccountsAreExempted.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4431 Docker gradle setup
  .env
  .github/workflows/comp-compile-application-code.yaml
  .gitignore
  build.gradle.kts
  compose-build.sh
  docker/.dockerignore
  docker/Dockerfile
  docker/README.md
  docker/docker-build.sh
  docker/docker-compose.yml
  docker/google-registry-login.sh
  docker/read-env.sh
  docker/start-services.sh
  docker/update-env.sh
  docs/docker-quickstart.md
  hedera-node/build.gradle.kts
  image-utils/wait-for-it
  run/gcr-login.sh
  run/gcr-push.sh
  run/gcr-tag.sh
Labels: DevOps, docker, CI:UnitTests, Tech Debt Reduced, CI:FullStackTests, CI:FinalChecks, Modularization

#4592 Fix hollow account with CryptoCreate to set EMPTY_KEY instead on null
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Labels: Limechain, CI:UnitTests

#4582 Port `0.34.0-alpha.1` patches
  .github/workflows/comp-compile-application-code.yaml
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldStateTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_32Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV032.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaStackedWorldStateUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/SolvencyPrecheck.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsV032ModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/AbstractRecordingCreateOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV032Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/HederaStackedWorldStateUpdaterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractInfoAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/QueryVerbs.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountBalance.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/HapiGetAccountInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/crypto/ReferenceType.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4585 Remove `0.34` properties from develop prod config files
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4556 HIP 632 design/test doc
  docs/design/hedera-account-service.md
Labels: CI:UnitTests, Design

#4611 Bump platform version in services to v0.35.0-alpha.1
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4618 Prepare for v0.34.0 tag
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4601 Reenable PBJ and update pbj and hapi versions
  hedera-node/hapi/build.gradle.kts
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4626 Port `v0.33.3` fixes
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessor.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/contract/ContractCallTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4615 Add `LazyCreateThroughPrecompileSuite` to integration tests
  test-clients/src/itest/java/ConcurrentSuites.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Labels: CI:UnitTests

#4636 Use explicit offset to set child consensus times during finalization
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorian.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorianTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/resource/contract/contracts/ConsTimeRepro/ConsTimeRepro.bin
  test-clients/src/main/resource/contract/contracts/ConsTimeRepro/ConsTimeRepro.json
  test-clients/src/main/resource/contract/contracts/ConsTimeRepro/ConsTimeRepro.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4577 `ContractCreate` and `ContractCall` preTransactionHandler
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/build.gradle.kts
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/module-info.java
  hedera-node/hedera-token-service-impl/build.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4640 Fix state leak during ISS.
  hedera-node/hedera-evm-api/src/main/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessor.java
  hedera-node/hedera-evm-api/src/test/java/com/hedera/services/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/services/state/forensics/ServicesIssListener.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/state/forensics/ServicesIssListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/services/txns/contract/ContractCallTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/HapiApiSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4669 Fix state leak during ISS
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListener.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListenerTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4671 Use explicit offset to set child consensus times during finalization
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorian.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorianTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/resource/contract/contracts/ConsTimeRepro/ConsTimeRepro.bin
  test-clients/src/main/resource/contract/contracts/ConsTimeRepro/ConsTimeRepro.json
  test-clients/src/main/resource/contract/contracts/ConsTimeRepro/ConsTimeRepro.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4638 04616 use ledgers for approval checks
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractAssociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractDissociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ApprovePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AssociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/DissociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MultiAssociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MultiDissociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/ApproveAllowanceChecks.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/DeleteAllowanceChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/resource/contract/contracts/TestApprover/TestApprover.bin
  test-clients/src/main/resource/contract/contracts/TestApprover/TestApprover.json
  test-clients/src/main/resource/contract/contracts/TestApprover/TestApprover.sol
Labels: CI:UnitTests, CI:FullStackTests

#4654 Do not try to perform a lazy create for a non-existing mirror address
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV032.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV032Test.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4628 Fix `contractCallResult` in txn record on hollow account creation via top-level `EthereumTransaction`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4674 Fix state leak during ISS (#4669)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListener.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListenerTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4668 Get record stream header info from command line parameter
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Labels: CI:UnitTests, CI:FinalChecks

#4675 04616 use ledgers for approval checks (#4638)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractAssociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractDissociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ApprovePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AssociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/DissociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MultiAssociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MultiDissociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/ApproveAllowanceChecks.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/DeleteAllowanceChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/resource/contract/contracts/TestApprover/TestApprover.bin
  test-clients/src/main/resource/contract/contracts/TestApprover/TestApprover.json
  test-clients/src/main/resource/contract/contracts/TestApprover/TestApprover.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4641 Change `0.32` EVM to `0.34`
  docs/design/services/smart-contract-service/evm-versioning.md
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_34Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV034.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsTestComponent.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsV032ModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV034Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4650 Pin used Github action to SHA hashes
  .github/workflows/comp-build-release-artifact.yaml
  .github/workflows/comp-compile-application-code.yaml
  .github/workflows/flow-deploy-release-artifact.yaml
  .github/workflows/flow-pull-request-checks.yaml
Labels: CI:UnitTests

#4684 Add support for python virtual environment in CircleCI
  .circleci/config.yml
Labels: CI:UnitTests

#4678 Fix `contractCallResult` in txn record on hollow account creation via top-level `EthereumTransaction`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallLocalEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4679 Cherry pick EVM 0.34 update
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  docs/design/evm-versioning.md
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_34Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV034.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsTestComponent.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsV032ModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/CallEvmTxProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV034Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4681 Integrate platform 0.35.0
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4642 Add the PayableCreate2Deploy contract to test clients
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  test-clients/src/main/resource/contract/contracts/PayableCreate2Deploy/PayableCreate2Deploy.bin
  test-clients/src/main/resource/contract/contracts/PayableCreate2Deploy/PayableCreate2Deploy.json
  test-clients/src/main/resource/contract/contracts/PayableCreate2Deploy/PayableCreate2Deploy.sol
Labels: CI:UnitTests, CI:FullStackTests

#4686 Make PR checks run on PRs from forks
  .github/workflows/comp-compile-application-code.yaml
  .github/workflows/flow-pull-request-checks.yaml
Labels: CI:UnitTests

#4703 Disable chatter in testnet config
  hedera-node/configuration/testnet/settings.txt
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4746 Add staking test with `isReceiverSigRequired=true`
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4705 move hedera account service design doc to appropriate sub folder
  docs/design/services/smart-contract-service/hedera-account-service.md
Labels: CI:UnitTests

#4617 ContractUpdate and ContractDelete pre-transaction handler
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/AccountKeyLookup.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/TransactionMetadataBuilder.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/Schema.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/SchemaTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/meta/ScheduleSigTransactionMetadataBuilderTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/test/meta/SigTransactionMetadataBuilderTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/AliasManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
  hedera-node/hedera-smart-contract-service-impl/build.gradle.kts
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractDeleteHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerParityTest.java
  hedera-node/hedera-token-service-impl/build.gradle.kts
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStore.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAccountStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/module-info.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, Modularization

#4690 Move ServicesMain to `hedera-app`
  docs/dev/testnet-rekey.md
  docs/docker-quickstart.md
  docs/intellij-quickstart.md
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKey.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskValue.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskValueSerializer.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryValue.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/ServicesMainTest.java
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/SystemAccountsCreator.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  run/reset-data-saved-from.sh
Labels: CI:UnitTests, CI:FinalChecks

#4749 Bind missing Hedera operations in EVM version 0.34
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaBalanceOperation.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaBalanceOperationTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_34Module.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  test-clients/src/main/resource/bootstrap.properties
  test-clients/src/main/resource/contract/contracts/Create2Factory/Create2Factory.bin
  test-clients/src/main/resource/contract/contracts/Create2Factory/Create2Factory.sol
  test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:FullStackTests, CI:FinalChecks

#4759 Add CI pipeline support for automatic release branch creation
  .github/workflows/config/release.yaml
  .github/workflows/support/scripts/release-branch-check.sh
  .github/workflows/xcron-release-branching.yaml
  hedera-node/configuration/preprod/log4j2.xml
Labels: CI:UnitTests

#4762 Flag to enable workflows
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/ServicesMainTest.java
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/ledger/StakingActivityModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalStaticProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests, CI:FinalChecks

#4796 Change release branch creation time
  .github/workflows/config/release.yaml
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4760 Add spec characterizing `ERC721Metadata.tokenURI()` with non-UTF-8 data
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/resource/contract/contracts/ErcAndHtsAlternatives/ErcAndHtsAlternatives.bin
  test-clients/src/main/resource/contract/contracts/ErcAndHtsAlternatives/ErcAndHtsAlternatives.json
  test-clients/src/main/resource/contract/contracts/ErcAndHtsAlternatives/ErcAndHtsAlternatives.sol
  test-clients/src/main/resource/contract/solidity/IERC721Metadata.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4797 Add Singleton States
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/EmptyReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/EmptyWritableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/FilteredReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/FilteredWritableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableSingletonState.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableSingletonStateBase.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/StateDefinition.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableSingletonState.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableSingletonStateBase.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableStates.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/EmptyReadableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/EmptyWritableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/FilteredReadableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/FilteredWritableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/ReadableSingletonStateBaseTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/SingletonStateTestBase.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/StateTestBase.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/WritableSingletonStateBaseTest.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapReadableStates.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapWritableStates.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/StateMetadata.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/singleton/ReadableSingletonStateImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/singleton/SingletonNode.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/singleton/StringLeaf.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/singleton/ValueLeaf.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/singleton/WritableSingletonStateImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleHederaStateTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistryTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/SerializationTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateUtilsTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableStateTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/singleton/StringLeafTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/singleton/ValueLeafTest.java
Labels: CI:UnitTests, CI:FinalChecks

#4799 Fix ServicesMain run
  hedera-node/hedera-app/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4815 Disable chatter on previewnet
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/settings.txt
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4819 Cherry pick tracking property changes for 0.35
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacks.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/SigImpactHistorian.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookup.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/RationalizedSigMeta.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/files/sysfiles/ConfigCallbacksTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookupTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/RationalizedSigMetaTest.java
  test-clients/src/main/java/com/hedera/services/bdd/junit/validators/HgcaaLogValidator.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: CI:UnitTests, CI:FinalChecks

#4813 Enable prometheus scrape endpoint in previewnet and testnet
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/configuration/testnet/settings.txt
Labels: CI:UnitTests

#4677 implement ScheduleDelete preHandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
  hedera-node/hedera-schedule-service-impl/build.gradle.kts
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleDeleteHandler.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerParityTest.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/handlers/ScheduleDeleteHandlerTest.java
  hedera-node/hedera-schedule-service-impl/src/test/java/module-info.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks
