Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-02, with the labels that each got.

#4823 Update `autoRenew.targetTypes=CONTRACT`
  hedera-node/configuration/mainnet/application.properties
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/application.properties
  hedera-node/configuration/previewnet/application.properties
  hedera-node/configuration/testnet/application.properties
  test-clients/src/main/resource/bootstrap.properties
  test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4822 Update `autoRenew.targetTypes=CONTRACT`
  hedera-node/configuration/mainnet/application.properties
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/application.properties
  hedera-node/configuration/previewnet/application.properties
  hedera-node/configuration/testnet/application.properties
  test-clients/src/main/resource/bootstrap.properties
  test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4821 Update services version num to 0.36.0-SNAPSHOT
  gradle.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4758 Define `SignatureVerifier` API
  hedera-node/hedera-app-spi/build.gradle.kts
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/signatures/OverrideSignatureVerifier.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/signatures/SignatureVerifier.java
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JContractIDKey.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4635 Implement TokenMintHandler prehandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/ParityTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4852 Update intellij-quickstart guide #4850
  docs/assets/gradle-run.png
  docs/assets/node-config.png
  docs/intellij-quickstart.md
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4853 Update platform version
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4652 Implemented `TokenRevokeKycFromAccount` PreHandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigRequirementsTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/TokenKycRevokeScenarios.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRevokeKycFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenRevokeKycFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/MetaAssertion.java
Labels: Limechain, CI:UnitTests, Modularization

#4498 Implement token fee schedule update prehandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/Dispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/DispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFeeScheduleUpdateHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
Labels: Limechain, CI:UnitTests, Modularization

#4752 Еxplicit `redirectForToken` call fix
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/codec/ExplicitRedirectForTokenWrapper.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/impl/EvmRedirectForTokenPrecompile.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/proxy/RedirectTarget.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/utils/DescriptorUtils.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/precompile/impl/EvmRedirectForTokenPrecompileTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/utils/DescriptorUtilsTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/RedirectPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/RedirectPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/UtilsConstructorTest.java
  test-clients/src/itest/java/ConcurrentSuites.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/RedirectTestContract/RedirectTestContract.bin
  test-clients/src/main/resource/contract/contracts/RedirectTestContract/RedirectTestContract.json
  test-clients/src/main/resource/contract/contracts/RedirectTestContract/RedirectTestContract.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: Limechain, CI:UnitTests, CI:FinalChecks

#4851 update hedera-services to use FSTS CLI instead of system properties
  .circleci/config.yml
Labels: CI:UnitTests, CI:FinalChecks

#4864 BugFix: Еxplicit `redirectForToken` call fix (#4752)
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/codec/ExplicitRedirectForTokenWrapper.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/impl/EvmRedirectForTokenPrecompile.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/precompile/proxy/RedirectTarget.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/utils/DescriptorUtils.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/precompile/impl/EvmRedirectForTokenPrecompileTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/utils/DescriptorUtilsTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/RedirectPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/utils/DescriptorUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/RedirectPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/UtilsConstructorTest.java
  test-clients/src/itest/java/ConcurrentSuites.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
  test-clients/src/main/resource/contract/contracts/RedirectTestContract/RedirectTestContract.bin
  test-clients/src/main/resource/contract/contracts/RedirectTestContract/RedirectTestContract.json
  test-clients/src/main/resource/contract/contracts/RedirectTestContract/RedirectTestContract.sol
  test-clients/src/main/resource/contract/solidity/hip-206/HederaTokenService.sol
  test-clients/src/main/resource/contract/solidity/hip-206/IHederaTokenService.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4709 04208 query workflow
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/FreeQueryHandler.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PaidQueryHandler.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/QueryHandler.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/authorization/Authorizer.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/CallContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/HandlersFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionHandlers.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/onset/OnsetResult.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/onset/WorkflowOnset.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryHandlers.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/common/SubmissionManagerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/onset/OnsetResultTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetInfoHandler.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkGetAccountDetailsHandler.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkGetByKeyHandler.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkGetExecutionTimeHandler.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkGetVersionInfoHandler.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkTransactionGetReceiptHandler.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkTransactionGetRecordHandler.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkUncheckedSubmitHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleGetInfoHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBySolidityIDHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBytecodeHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetRecordsHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountRecordsHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetLiveHashHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetStakersHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetAccountNftInfosHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetInfoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfosHandler.java
Labels: CI:FinalChecks, Modularization

#4524 Initial documentation of query workflow
  docs/design/app/images/Ingest Workflow.png
  docs/design/app/images/Pre-Handle Transaction Workflow.png
  docs/design/app/images/Query Workflow.svg
  docs/design/app/workflows.md
Labels: CI:FinalChecks, Modularization

#4882 Add a test for validating auto-renew behavior
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4517 old files removed from repo
  data/upgrade/.gitkeep
  hedera-node/.env
  hedera-node/hapi-utils/copyright.txt
  hedera-node/tools/gen-explicit-fee-schedules.py
  hedera-node/tools/reset-data-saved-from.sh
  logback.xml
  run/application.yml
  run/generate-changelog.sh
  run/new-release-branch.sh
  run/set-cron-times.py
  test-tools/drop_database.psql
  test-tools/test_state_recover.sh
Labels: CI:UnitTests, CI:FinalChecks

#4369 6166: Migrate VirtualMap data from JasperDB to MerkleDb data sources
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/setup/InfrastructureManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/StateModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokensMigrator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractMerkleDbKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/EntityNumMerkleDbKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/EntityNumVirtualKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/IterableContractMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/IterableContractValue.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/OnDiskAccountMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/OnDiskTokenRelMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenMerkleDbKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenValue.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobMerkleDbKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobValue.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/entities/OnDiskAccount.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/entities/OnDiskTokenRel.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/UniqueTokensMigratorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobValueTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/StoresModuleTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/resource/bootstrap.properties
  test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4900 Add NFT stat logging on startup
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/token/BurnLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/token/WipeLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EntityNumPair.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/SignedState.swh
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore.vmap
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-36-896________268.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-37-394________269.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-37-899________270.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-38-398________271.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-38-898________272.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-39-395________273.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/metadata.jdbm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_2023-02-08--03-00-37-950__________0.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_bucket_index.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_metadata.hdhm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToDiskLocationInternalNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToDiskLocationLeafNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-37-899________270.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-38-398________271.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-38-898________272.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-39-395________273.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore.vmap
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/internalHashStoreDisk/smartContractIterableKvStore:internalHashes_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/metadata.jdbm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_bucket_index.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_metadata.hdhm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/pathToDiskLocationInternalNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/pathToDiskLocationLeafNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/pathToHashKeyValue/smartContractIterableKvStore:pathToHashKeyValue_metadata.dfc
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4917 Fix `nftsOwned` for treasury during expiry
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/removal/TreasuryReturnHelper.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/removal/TreasuryReturnHelperTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/file/FileUpdateSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4920 Created new export of workflow diagrams
  hedera-node/docs/design/app/images/Ingest Workflow.drawio.png
  hedera-node/docs/design/app/images/Ingest Workflow.svg
  hedera-node/docs/design/app/images/Pre-Handle Transaction Workflow.drawio.png
  hedera-node/docs/design/app/images/Pre-Handle Transaction Workflow.svg
  hedera-node/docs/design/app/images/Query Workflow.drawio.png
  hedera-node/docs/design/app/images/Query Workflow.svg
  hedera-node/docs/design/app/workflows.md
Labels: CI:FinalChecks, Modularization

#4839 Update platform version to `0.36.0-alpha.1`
  hedera-node/hedera-app/src/itest/java/grpc/GrpcTestBase.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/test/java/utils/TestUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/annotations/StaticAccountMemo.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/StateChildIndices.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn0.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn1.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn10.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn11.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn12.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn13.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn14.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn2.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn3.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn4.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn5.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn6.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn7.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn8.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleNetworkContext-v12-sn9.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerklePayerRecords-v1-sn4.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleSpecialFiles-v2-sn0.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleSpecialFiles-v2-sn1.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleSpecialFiles-v2-sn2.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleSpecialFiles-v2-sn3.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleSpecialFiles-v2-sn4.hex
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4880 Adding support for Redirect Token Calls fro evm-module
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractEvmStackedLedgerUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockAccountAccessor.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractStackedLedgerUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MockLedgerWorldUpdater.java
Labels: Limechain, CI:UnitTests, CI:FinalChecks

#4868 Enable HIP-583 features on testnet and mainnet
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Limechain, CI:UnitTests, CI:FinalChecks

#4916 Fix : Fix nftsOwned for Treasury when NFTs are returned back to treasury
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/removal/TreasuryReturnHelper.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/removal/TreasuryReturnHelperTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4926 Adding support for Redirect Token Calls for hedera-evm (#4880)
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractEvmStackedLedgerUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldState.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockAccountAccessor.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/MockEntityAccess.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractStackedLedgerUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/UpdateTrackingLedgerAccount.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MockLedgerWorldUpdater.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4924 Clean up block number/record file relationship
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/BlockManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/BlockNumberMeta.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/ReconnectListener.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/RecordStreaming.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamObject.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/BlockManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/ReconnectListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/RecordStreamingTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamObjectTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4928 Update parameter name to avoid confusion
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Labels: CI:UnitTests, CI:FinalChecks

#4907 Crypto create refactoring
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/Ed25519Utils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/meta/InitialAccountIdentifiers.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  settings.gradle.kts
Labels: CI:UnitTests

#4937 Upgrade platform dependency to `0.36.0-alpha.2`
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4941 Clean up block number/record file relationship (#4924)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/BlockManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/BlockNumberMeta.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/ReconnectListener.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/RecordStreaming.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamObject.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/BlockManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/ReconnectListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/RecordStreamingTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamObjectTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4942 Cherry pick 4907
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/keys/Ed25519Utils.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/keys/Ed25519UtilsTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  settings.gradle.kts
  test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/meta/InitialAccountIdentifiers.java
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4975 Upgrade platform dependency to 0.36.0
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4977 Reduce itest and e2e test logging to ERROR or above
  hedera-node/test-clients/src/eet/resources/log4j2.xml
  hedera-node/test-clients/src/itest/resources/log4j2.xml
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4980 feat: update code style enforcement and configuration
  .github/workflows/comp-build-release-artifact.yaml
  .github/workflows/comp-compile-application-code.yaml
  .github/workflows/flow-build-application.yaml
  .github/workflows/flow-pull-request-checks.yaml
  buildSrc/build.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-java-conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.spotless-kotlin-conventions.gradle.kts
  gradle.properties
Labels: P1, Feature Enhancement, CI:FinalChecks

#4978 Port NFT logging
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokenMapAdapter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/token/BurnLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/token/WipeLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EntityNumPair.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/SignedState.swh
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore.vmap
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-36-896________268.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-37-394________269.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-37-899________270.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-38-398________271.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-38-898________272.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_2023-02-08--03-02-39-395________273.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/internalHashStoreDisk/fileStore:internalHashes_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/metadata.jdbm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_2023-02-08--03-00-37-950__________0.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_bucket_index.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/objectKeyToPath/fileStore:objectKeyToPath_metadata.hdhm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToDiskLocationInternalNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToDiskLocationLeafNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-37-899________270.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-38-398________271.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-38-898________272.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_2023-02-08--03-02-39-395________273.jdb
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore.vmap
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/internalHashStoreDisk/smartContractIterableKvStore:internalHashes_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/metadata.jdbm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_bucket_index.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_metadata.hdhm
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/pathToDiskLocationInternalNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/pathToDiskLocationLeafNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/signedState/v0.35.0/smartContractIterableKvStore/pathToHashKeyValue/smartContractIterableKvStore:pathToHashKeyValue_metadata.dfc
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4988 Update FileSignTool
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Labels: CI:UnitTests, CI:FinalChecks

#4992 (Gradle) Module Documentation
  hedera-node/docs/design/modules.md
Labels: CI:UnitTests, CI:FinalChecks

#4986 Implement TokenUpdateHandler preHandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateHandlerParityTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4987 Implement TokenDeleteHandler preHandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDeleteHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerParityTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4877 Implement TokenDissociateFromAccountHandler preHandle
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4875 Implement TokenAssociateHandler prehandle
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAssociateToAccountHandlerTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4991 Implement TokenFreezeAccountHandler preHandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFreezeAccountHandlerTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4886 Fix : Fix `SigRequirements` for NFT Transfer using alias
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/metadata/SigMetadataLookup.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookup.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigRequirements.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/DelegatingSigMetadataLookup.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookupTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/lookups/AccountSigMetaLookup.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/lookups/DefaultAccountLookup.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigRequirementsTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/ParityTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAssociateToAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFeeScheduleUpdateHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateHandlerParityTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4973 Fix created contract ids after hollow account creation
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaMutableWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.json
  hedera-node/test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.sol
Labels: CI:UnitTests

#4999 Fix created contract ids after hollow account creation (#4973)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaMutableWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.json
  hedera-node/test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.sol
  test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4881 4838 d contract expiry specs
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFreezeAccountHandlerTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecSetup.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5002 Update platform version to 0.35.3
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5005 Upgrade platform to v0.36.1
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5007 Port NFT logging (#4978)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5006 CI pipeline file and workflow name updates
  .github/workflows/config/node-release.yaml
  .github/workflows/node-flow-build-application.yaml
  .github/workflows/node-flow-deploy-release-artifact.yaml
  .github/workflows/node-flow-pull-request-checks.yaml
  .github/workflows/node-zxc-build-release-artifact.yaml
  .github/workflows/node-zxc-compile-application-code.yaml
  .github/workflows/node-zxcron-release-branching.yaml
  README.md
Labels: CI:FinalChecks

#5008 Add Snyk scanning
  .github/workflows/node-flow-pull-request-checks.yaml
  .github/workflows/node-flow-snyk-monitor.yml
  .github/workflows/node-zxc-compile-application-code.yaml
Labels: CI:UnitTests, New Feature

#4989 Implement TokenBurnHandler preHandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerParityTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4996 Implement TokenAccountWipeHandler preHandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
Labels: Limechain, CI:UnitTests, Modularization

#4921 Remove logic that auto assigns alias on CryptoCreate with ECDSA key
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/SigningReqsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Labels: CI:UnitTests

#5014 fix: resolve issues with the Snyk monitor workflow
  .github/workflows/node-flow-snyk-monitor.yml
  .github/workflows/node-zxcron-release-branching.yaml
  .github/workflows/node-zxf-snyk-monitor.yaml
Labels: P1, Bug, CI:FinalChecks

#4997 Adding block number tool
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/RecordBlockNumberTool.java
Labels: CI:UnitTests, CI:FinalChecks

#4888 Add basic validator for validating renewal and expiry records
  hedera-node/test-clients/src/itest/java/AllIntegrationTests.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/BalanceReconciliationValidator.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/ExpiryRecordsValidator.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/ContractAutoExpirySpecs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/streaming/RecordStreamValidation.java
  hedera-node/test-clients/src/main/resource/spec-default.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5026 Update property `contracts.evm.version=v0.34`
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5029 Update release.yaml for creating the release/0.36 branch
  .github/workflows/config/node-release.yaml
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5027 Disable contract expiry
  hedera-node/configuration/mainnet/application.properties
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/application.properties
  hedera-node/configuration/previewnet/application.properties
  hedera-node/configuration/testnet/application.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5033 Implement topic deletion prehandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerParityTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusTestUtils.java
  hedera-node/hedera-consensus-service-impl/src/test/java/module-info.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/accounts/MockMMapFactory.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, Modularization

#5036 Minor spec update to reflect current behavior
  hedera-node/docs/scheduled-transactions/revised-spec.md
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5034 enable node software compression of recordstream and account balance files for testnet
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/configuration/update/during-freeze.sh
  hedera-node/configuration/update/immediate.sh
Labels: CI:FinalChecks

#5038 Add missing code to TokenPUV test suite cleanup
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/validation/TokenPuvSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5047 Fix regression test
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/SuiteRunner.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5050 fix: resolve issues in the CI pipeline preventing Snyk and Sonar analysis from running on push and workflow_dispatch triggers
  .github/workflows/node-flow-build-application.yaml
  .github/workflows/node-zxc-compile-application-code.yaml
Labels: CI:UnitTests

#5032 Generalize workflows enabled and add workflow ports
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/GlobalConfig.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/NodeConfig.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigurationAdaptor.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/ConfigurationAdaptorTest.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalStaticProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/NodeLocalProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/ScreenedNodeFileProps.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalStaticPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/NodeLocalPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/ScreenedNodeFilePropsTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/node.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4596 Service modules architecture documentation
  hedera-node/docs/design/service-modules.md
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks, Modularization

#5063 feat: updates the e2e and itest based network log captures and adds a conditional flag
  .github/workflows/node-flow-build-application.yaml
  .github/workflows/node-flow-pull-request-checks.yaml
  .github/workflows/node-zxc-compile-application-code.yaml
Labels: CI:FinalChecks

#4708 Enable Traceability sidecars on testnet and mainnet
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5054 Support auto-scheduling operations by type within a suite
  hedera-node/test-clients/src/itest/java/ConcurrentSuites.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TestBase.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecSetup.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleSign.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java
  hedera-node/test-clients/src/main/resource/spec-default.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5089 Sidecars configuration cherry pick to 0.36
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
Labels: CI:FinalChecks

#5046 4915 - added the pure metrics value and not only the percentage out of the total
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/EntityUtilGauges.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/EntityUtilGaugesTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5091 Reset account balance on TOKEN_TREASURY to correct a failed itest
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
Labels: CI:UnitTests

#5060 Add `WritableTopicStore`
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/WritableTopicStore.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/entity/TopicBuilderImpl.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/entity/TopicImpl.java
  hedera-node/hedera-consensus-service-impl/src/main/java/module-info.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ReadableTopicStoreTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/WritableTopicStoreTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/entity/TopicBuilderImplTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/entity/TopicImplTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusGetTopicInfoHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
  hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/entity/Topic.java
  hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/entity/TopicBuilder.java
  hedera-node/hedera-consensus-service/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/entity/AccountBuilderImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/entity/AccountImpl.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/entity/AccountImplTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/entity/Account.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5079 Fix hash stream log.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
Labels: CI:FinalChecks

#5085 Fix log4j configuration for local tests.
  platform-sdk/sdk/log4j2.xml
Labels: CI:FinalChecks

#5077 Move delay function so it is called per round instead of per transaction
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
Labels: CI:UnitTests, CI:FinalChecks

#5100 added the missing functionality to FileSignTool
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5059 Consensus Message Submission Prehandle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusTestUtils.java
Labels: CI:UnitTests
