Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-04, with the labels that each got.

#5898 `hedera-app` Part 4
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/StateUtils.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/data/MeteredOutputStream.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKey.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskValue.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskWritableKVState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryValue.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/handle/AdaptedMonoTransitionRunnerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleHederaStateTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistryTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/ResponsibleVMapUser.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/SerializationTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/MonoThrottleAccumulatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowModuleTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryDispatcherTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/AbstractVirtualCodecTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#5891 fix fallen behind
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/SyncFallenBehindStatus.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTestExecutor.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/SyncTests.java
Labels: CI:FinalChecks

#5094 refactoring of config class scan
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/ConfigUtils.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/singleton/ConfigurationHolder.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/FileUtils.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultMetricsProvider.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/ConfigUtilsTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sub/TestConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/MetricsDocUtils.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/MetricsDocUtilsTest.java
  platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/com/swirlds/test/framework/config/TestConfigBuilder.java
Labels: CI:UnitTests, CI:FinalChecks

#5915 Add more `selfdestruct` tests
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_30Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_34Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaOperationUtil.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperation.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/SelfDestructCallable/SelfDestructCallable.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/SelfDestructCallable/SelfDestructCallable.json
  hedera-node/test-clients/src/main/resource/contract/contracts/SelfDestructCallable/SelfDestructCallable.sol
Labels: Limechain, CI:UnitTests, CI:FinalChecks

#5765 05476 - Allow zero stake nodes to create events / process transactions
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldTransactionSubmitter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventTaskCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SignatureTransmitter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SwirldTransactionSubmitterTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSigningTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventTaskCreatorTest.java
Labels: CI:FinalChecks

#5936 Cherry pick - Use mirror address of selfdestruct-ed creation in record
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5924 05923 Fixed persistence issue for a restored `LongListOffHeap`
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/LongListOffHeap.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/LongListOffHeapTest.java
Labels: CI:UnitTests, CI:FinalChecks

#5948 Update typo `CONTRACT_STATE_CHANGE`
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: CI:FinalChecks

#5675 Extract evm version of HederaChainIdOperation
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/EvmProperties.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmChainIdOperation.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmChainIdOperationTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_30Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_34Module.java
Labels: Limechain, CI:UnitTests

#4894 Refactoring for `Adding support for Redirect Token Calls fro evm-module` PR
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/UpdateAccountTracker.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractEvmStackedLedgerUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractLedgerEvmWorldUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmStackedWorldStateUpdater.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdateTrackingAccount.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccount.java
  hedera-node/hedera-evm/src/main/java/module-info.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/HederaEvmStackedWorldStateUpdaterTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdateTrackingAccountTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/models/UpdatedHederaEvmAccountTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/UpdateAccountTrackerImpl.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/AbstractStackedLedgerUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaStackedWorldStateUpdater.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldState.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/AbstractLedgerWorldUpdaterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/AbstractStackedLedgerUpdaterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/HederaWorldStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/CreatePrecompileTest.java
Labels: Limechain, CI:UnitTests, CI:FinalChecks

#5937 enable record stream and balance compression by default
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
Labels: CI:FinalChecks

#5945 Update gradle.properties
  gradle.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5947 Schedule 0.37 release creation
  .github/workflows/config/node-release.yaml
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5799 Implement blocklisting of EVM addresses
  hedera-node/configuration/compose/bootstrap.properties
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/BlocklistAccountCreator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/ServicesTxnManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManager.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/evm-addresses-blocklist.csv
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/BlocklistAccountCreatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/ServicesTxnManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/MigrationRecordsManagerTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/hedera-mono-service/src/test/resources/invalid-col-count-blocklist.csv
  hedera-node/hedera-mono-service/src/test/resources/invalid-hex-blocklist.csv
  hedera-node/hedera-mono-service/src/test/resources/test-blocklist.csv
  hedera-node/test-clients/src/itest/resources/network/config/bootstrap.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java
Labels: Limechain, CI:UnitTests

#5949 5179: Bucket.findEntryOffset() can reduce calls to getKeySize()
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java
Labels: CI:UnitTests, Tech Debt Reduced, Performance, CI:FinalChecks, Platform Data Structures

#5968 Rebuild contract storage mappings and links using stable `hashCode()` impl
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/LinkRepairs.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/StorageLinksFixer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKey.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/SmartContractState/SmartContractState.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/SmartContractState/SmartContractState.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5966 5824: Create a `VirtualMap` benchmark for remove operations
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BaseBench.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkMetrics.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBenchJPDB.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBenchMerkleDb.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/Utils.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/VirtualMapBench.java
Labels: CI:FinalChecks

#5790 05786 5396 misc startup improvements
  platform-sdk/docs/components/eventflow-threads.drawio.svg
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/BrowseCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/BackgroundHashChecker.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/BackgroundHashCheckerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
Labels: CI:FinalChecks

#5952 Update settings.gradle.kts
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5971 05875 query workflow improvements
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/info/CurrentPlatformStatus.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/info/NetworkInfo.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/info/NodeInfo.java
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/InfoDaggerModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/MonoCurrentPlatformStatus.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/MonoNetworkInfo.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/info/MonoNodeInfo.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusGetTopicInfoHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
Labels: CI:UnitTests, Modularization

#5989 5951 gradle kts update release branch
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5991 Cherry Pick - Add signing requirements for transfer of NFT with fallback royalty fee
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/CustomFeeType.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AdjustmentUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/BalanceChange.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/BalanceChangeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysStillWorkAsExpectedSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  test-clients/src/main/resource/bootstrap.properties
Labels: CI:FinalChecks

#5992 Cherry Pick - Add signing requirements for transfer of NFT with fallback royalty fee
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/CustomFeeType.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AdjustmentUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/BalanceChange.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/BalanceChangeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysStillWorkAsExpectedSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/contract/contracts/SmartContractState/SmartContractState.json
Labels: CI:FinalChecks

#5997 Cherry Pick to develop - Add signing requirements for transfer of NFT with fallback royalty fee
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/CustomFeeType.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AdjustmentUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/BalanceChange.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/BalanceChangeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysStillWorkAsExpectedSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:FinalChecks

#6005 0.36: Turn Contract ACTION sidecars ON in testnet + mainnet
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
Labels: CI:FinalChecks

#6011 Remove testnet-only contract storage migration
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/LinkRepairs.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/StorageLinksFixer.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5988 Implement FreezeService preHandle
  hedera-node/hedera-admin-service-impl/build.gradle.kts
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/FreezeServiceImpl.java
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/ReadableSpecialFileStore.java
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/codec/MonoSpecialFilesAdapterCodec.java
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/handlers/FreezeHandler.java
  hedera-node/hedera-admin-service-impl/src/main/java/module-info.java
  hedera-node/hedera-admin-service-impl/src/test/java/com/hedera/node/app/service/admin/impl/test/FreezeServiceImplTest.java
  hedera-node/hedera-admin-service-impl/src/test/java/com/hedera/node/app/service/admin/impl/test/codec/MonoSpecialFilesAdapterCodecTest.java
  hedera-node/hedera-admin-service-impl/src/test/java/com/hedera/node/app/service/admin/impl/test/handlers/FreezeHandlerTest.java
  hedera-node/hedera-admin-service-impl/src/test/java/module-info.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/NetworkServiceImpl.java
  hedera-node/hedera-network-service-impl/src/test/java/com/hedera/node/app/service/network/impl/test/NetworkServiceImplTest.java
Labels: CI:FinalChecks

#6007 Update FileSignTool to support compressed rcd file with extension "rcd.gz"
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
Labels: CI:UnitTests, CI:FinalChecks

#5984 Fix flaky preconsensus event stream test
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java
Labels: CI:FinalChecks

#6000 Change the file name for preconsensus event stream files.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileTests.java
Labels: CI:FinalChecks

#6028 balance and recordstream compression prop update mainnet
  hedera-node/configuration/mainnet/bootstrap.properties
Labels: CI:FinalChecks

#5974 Remove SessionContext
  hedera-node/hedera-app/src/itest/java/grpc/GrpcQueryTest.java
  hedera-node/hedera-app/src/itest/java/grpc/GrpcTestBase.java
  hedera-node/hedera-app/src/itest/java/grpc/GrpcTransactionTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/SessionContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/QueryMethod.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/TransactionMethod.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/TransactionChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/GrpcServiceBuilderTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/QueryMethodTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/TransactionMethodTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/TransactionCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
Labels: CI:UnitTests, Modularization

#6012 Revert to `v0.35.3` `ContractKey.hashCode()`
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKey.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/ContractKeyTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6040 Enable default services compression properties
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:FinalChecks

#6014 5910: VirtualKey doesn't need to be comparable
  platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/virtual/AccountVirtualMapKey.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/VirtualMerkleLeafHasher.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/account/AccountVirtualMapKey.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/data/SmartContractMapKey.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkKey.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/DataSourceValidator.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/JasperDbBuilder.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/VirtualDataSourceJasperDB.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/VirtualLeafRecordSerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/Bucket.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/BucketMutation.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/BucketSerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/HalfDiskVirtualKeySet.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/VirtualKeySetSerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/DataSourceValidator.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSourceBuilder.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbTableConfig.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/VirtualLeafRecordSerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/BucketMutation.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/BucketSerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskVirtualKeySet.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/VirtualKeySetSerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/serialize/AbstractFixedSizeKeySerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/serialize/KeySerializer.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/CloseFlushTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/TestType.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualKey.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualLongKey.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMap.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMapMigration.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSourceBuilder.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualKeySet.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/RecordAccessor.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/ArrayHashingQueue.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/CompoundHashingQueue.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/HashJob.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/HashingQueue.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHashListener.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/RecordAccessorImpl.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualInternalNode.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualLeafNode.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListener.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/ReconnectNodeRemover.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualLearnerTreeView.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualTeacherTreeView.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualTreeViewBase.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualLongKeyTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapValidator.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/datasource/InMemoryDataSource.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/datasource/InMemoryKeySet.java
Labels: CI:UnitTests, Tech Debt Reduced, CI:FinalChecks, Platform Data Structures

#6039 Bump JRS spec `0.0.X` ids to `0.0.(X+300)` to account for EVM blocklist accounts
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java
Labels: CI:UnitTests, CI:FinalChecks

#5960 Implement `TokenPause` and `TokenUnpause` Handlers
  hedera-node/hapi/src/main/java/module-info.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/records/BaseRecordBuilder.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleException.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/workflows/HandleExceptionTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactoryTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/WritableTopicStore.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/pbj/PbjConverterTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenPauseHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnpauseHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableTokenStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableTokenStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/codec/EntityNumCodecTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/codec/StringCodecTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/ParityTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenPauseHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenPauseHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnpauseHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnpauseHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
  hedera-node/hedera-token-service-impl/src/test/java/module-info.java
  settings.gradle.kts
Labels: CI:FinalChecks

#6044 Cherry pick Add signing requirements for transfer of NFT with fallback royalty fee (#5997)
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/CustomFeeType.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertySource.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AdjustmentUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/BalanceChange.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ERCTransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FixedFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/FractionalFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HbarFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/HtsFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/marshalling/RoyaltyFeeAssessorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/BalanceChangeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysStillWorkAsExpectedSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:FinalChecks

#6042 Explicitly disable `transThrottle`
  hedera-node/configuration/compose/settings.txt
  hedera-node/configuration/dev/settings.txt
  hedera-node/configuration/mainnet/settings.txt
  hedera-node/configuration/preprod/settings.txt
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/configuration/testnet/settings.txt
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
Labels: CI:FinalChecks

#6048 Decrement entity numbers (299 not 300 blocklist accounts)
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java
Labels: CI:FinalChecks

#6064 Fix compile errors
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
Labels: CI:FinalChecks

#6046 Turn on the contract actions sidecar in mainnet and testnet
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
Labels: CI:FinalChecks

#6066 Change HAPI Jar
  settings.gradle.kts
Labels: CI:FinalChecks

#6033 05796 HTS precomipile clears memo
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStore.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/UpdateTokenInfoContract/UpdateTokenInfoContract.sol
Labels: Limechain, CI:UnitTests

#6067 Fix NPE in `SigReqAdapterUtils`
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
Labels: CI:FinalChecks

#5963 More robust state dumps
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/StateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/dispatch/triggers/control/StateDumpRequestedTrigger.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTeacher.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyStateFinder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/IssHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFinder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateMap.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateUtilities.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocolTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/SignedStateMapTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/AbstractSignedStateManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/AddIncompleteStateTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/EarlySignaturesTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/EmergencyStateFinderTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/OldCompleteStateEventuallyReleasedTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/RegisterStatesWithoutSignaturesTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SequentialSignaturesRestartTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SequentialSignaturesTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SignedStateManagerBuilder.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssHandlerTests.java
Labels: CI:FinalChecks

#5998 #5380 Introduced MappedConfigSource
  platform-sdk/docs/base/configuration/configuration.md
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/AliasConfigSource.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/ConfigMapping.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/MappedConfigSource.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sources/AliasConfigSourceTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sources/MappedConfigSourceTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigAliases.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigMappings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/config/ConfigMappingsTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6069 Make accounts blocklisting feature flag disabled by default
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java
Labels: Limechain, CI:UnitTests

#5687 Turn on the contract actions sidecar in mainnet and testnet
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
Labels: CI:UnitTests, CI:FinalChecks

#6078 Revert "#5380 Introduced MappedConfigSource"
  platform-sdk/docs/base/configuration/configuration.md
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/AliasConfigSource.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/ConfigMapping.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/MappedConfigSource.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sources/AliasConfigSourceTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sources/MappedConfigSourceTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigAliases.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigMappings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/config/ConfigAliasesTest.java
Labels: CI:FinalChecks

#6057 05987 - write human readable state address book during state save.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
Labels: CI:FinalChecks

#6074 Make accounts blocklisting feature flag disabled by default (#6069)
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/TargetNetworkPrep.java
Labels: CI:FinalChecks

#6086 fix: update log rollover configuration
  hedera-node/configuration/compose/log4j2.xml
  hedera-node/configuration/dev/log4j2.xml
  hedera-node/configuration/mainnet/log4j2.xml
  hedera-node/configuration/preprod/log4j2.xml
  hedera-node/configuration/previewnet/log4j2.xml
  hedera-node/configuration/testnet/log4j2.xml
Labels: CI:FinalChecks

#6079 6077 - if no state is loaded, always use config address book.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
Labels: CI:FinalChecks

#5940 05930 - fix address book init on software downgrade
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/BootstrapUtils.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
Labels: CI:FinalChecks

#6098 change hapi version
  settings.gradle.kts
Labels: CI:FinalChecks

#6096 update hapi version in gradle kts file
  settings.gradle.kts
Labels: CI:FinalChecks

#5899 05584 - automating address book initialization tests
  platform-sdk/platform-apps/tests/AddressBookTestingTool/README.md
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/module-info.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SwirldState.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookValidator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Network.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSigningTests.java
Labels: CI:FinalChecks

#6111 Omit auto-renew id if unused in synth `ContractCreateTransactionBody`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/AccountCustomizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizer.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizerTest.java
Labels: CI:FinalChecks

#6076 update platform version to 38
  platform-sdk/gradle.properties
Labels: CI:FinalChecks

#6087 Set the ledger ID for preproduction environments
  hedera-node/configuration/preprod/bootstrap.properties
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5911 Implement Token Grant KYC Handle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactoryTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenRelationStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableTokenRelationStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
Labels: CI:FinalChecks

#5918 Add more hollow finalization tests
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java
Labels: Test Development, Limechain, CI:UnitTests, CI:FinalChecks

#6179 Fix angry log message when state metadata doesn't record any state signatures
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadata.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateMetadataTests.java
Labels: CI:FinalChecks

#6134 Enable writing pcli plugins in `hedera-services` and provide an example plugin
  hedera-node/cli-clients/build.gradle.kts
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/ExamplePcliPlugin.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SummarizeSignedStateFileCommand.java
  hedera-node/cli-clients/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#6181 Use correct path when loading state.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SavedStateLoader.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/BootstrapUtils.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateLoaderTests.java
Labels: CI:FinalChecks

#4943 Add fuzzing tests for CryptoTransfer-to-alias, CryptoTransfer-to-EVM-address covering auto/lazy creates and transfers to existing accounts
  hedera-node/test-clients/src/eet/java/EndToEndTests.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/meta/InitialAccountIdentifiers.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/RandomAccount.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/TransferToRandomEVMAddress.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/TransferToRandomKey.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoTransfer.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/ProviderRun.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/AddressAliasIdFuzzing.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/IdFuzzingProviderFactory.java
  hedera-node/test-clients/src/main/resource/eet-config/id-fuzzing.properties
Labels: Limechain, CI:UnitTests

#6177 Include ownerId in synthetic child createApproveAllowanceForAllNFT txn
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SetApprovalForAllPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java
Labels: Limechain, CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6208 Enable mainnet prometheus endpoint
  hedera-node/configuration/mainnet/settings.txt
Labels: CI:FinalChecks

#5964 Upgrade EVM to Shanghai
  buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/AbstractEvmRecordingCreateOperation.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmChainIdOperation.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmCreate2Operation.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmCreateOperation.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmSLoadOperation.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/AbstractCodeCache.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/HederaEvmWorldStateTokenAccount.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/store/contracts/WorldStateAccount.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/AbstractEvmRecordingCreateOperationTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmCreate2OperationTest.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/store/contracts/AbstractCodeCacheTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_38Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/CreateEvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaLogOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaPrngSeedOperator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaSStoreOperation.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaSStoreOperationTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PushZeroOperationSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/OpcodesContract/OpcodesContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/OpcodesContract/OpcodesContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/OpcodesContract/OpcodesContract.sol
  hedera-node/test-clients/src/main/resource/contract/contracts/OpcodesContract/recompile.sh
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests

#6211 Added break statement.
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/KeyUtils.java
Labels: CI:FinalChecks

#6102 Merge relevant work from `replay-develop`
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/FreezeServiceImpl.java
  hedera-node/hedera-admin-service-impl/src/test/java/com/hedera/node/app/service/admin/impl/test/FreezeServiceImplTest.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/AttributeValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/components/IngestComponent.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/meta/MonoHandleContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServiceModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WorkingStateWritableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflowModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandlersModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedExpiryValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowModule.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/handle/AdaptedMonoTransitionRunnerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/meta/MonoHandleContextTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/adapters/MerkleMapLikeAdapterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/WorkingStateWritableStoreFactoryTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowModuleTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidatorTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ConsensusServiceImpl.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ConsensusServiceImplTest.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileServiceImplTest.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/NetworkServiceImpl.java
  hedera-node/hedera-network-service-impl/src/test/java/com/hedera/node/app/service/network/impl/test/NetworkServiceImplTest.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleServiceImpl.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/ScheduleServiceImplTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractServiceImplTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenServiceImplTest.java
  hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/UtilServiceImpl.java
  hedera-node/hedera-util-service-impl/src/test/java/com/hedera/node/app/service/util/impl/test/UtilServiceImplTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6210 Make readable stores available to all services
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/TransactionHandler.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/workflows/PreHandleContextListUpdatesTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoFeeAccumulator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/AdaptedMonoFeeCalculator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/MonoFeeAccumulatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactoryTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
Labels: CI:UnitTests, Modularization

#6212 Turn on the Shanghai version of the EVM in previewnet
  hedera-node/configuration/previewnet/bootstrap.properties
Labels: CI:FinalChecks

#5814 Config API use null annotations and checks
  platform-sdk/swirlds-base/build.gradle.kts
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/ArgumentUtils.java
  platform-sdk/swirlds-base/src/main/java/module-info.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/CommonUtils.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/Configuration.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/ConfigurationBuilder.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/converter/ConfigConverter.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/intern/ConfigurationProvider.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/source/ConfigSource.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/spi/ConfigurationBuilderFactory.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/ConfigPropertyConstraint.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/ConfigValidator.java
  platform-sdk/swirlds-config-api/src/main/java/com/swirlds/config/api/validation/ConfigViolationException.java
  platform-sdk/swirlds-config-impl/build.gradle.kts
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigDataFactory.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigDataService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigListUtils.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigNumberUtils.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigPropertiesService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigSourceService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigValidationService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationBuilderFactoryImpl.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationBuilderImpl.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationImpl.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConstraintValidator.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConverterService.java
  platform-sdk/swirlds-config-impl/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FinalChecks

#6053 Implement HRC facade implementation of associate/dissociate functions
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/AbiConstants.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AssociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/DissociatePrecompile.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/AssociatePrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HRCPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSTestsUtil.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/HRCPrecompileSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/contract/contracts/HRC/HRC.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/HRC/HRC.json
  hedera-node/test-clients/src/main/resource/contract/contracts/HRC/HRC.sol
  hedera-node/test-clients/src/main/resource/contract/contracts/HRCContract/HRCContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/HRCContract/HRCContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/HRCContract/HRCContract.sol
Labels: CI:FinalChecks

#6182 06141 - Fix AddressBookTestingToolState errors for test scenarios
  platform-sdk/platform-apps/tests/AddressBookTestingTool/README.md
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestScenario.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolConfig.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SwirldState.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateValidator.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSigningTests.java
Labels: CI:FinalChecks

#6207 Bump platform version to a 0.38 adhoc build
  buildSrc/src/main/kotlin/com.hedera.hashgraph.conventions.gradle.kts
  gradle.properties
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/EmptyReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/EmptyWritableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/FilteredReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/FilteredWritableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVState.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableKVStateBase.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/StateDefinition.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableKVState.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableKVStateBase.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableStates.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapReadableKVState.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapReadableStates.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapWritableKVState.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapWritableStates.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/MonoServicesMain.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/StateMetadata.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/adapters/MerkleMapLikeAdapter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/adapters/VirtualMapLikeAdapter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKey.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryKey.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryValue.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/ServicesMainTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/ResponsibleVMapUser.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/WritableTopicStore.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/NodeInfo.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/adapters/VirtualMapLike.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/codec/MonoMapCodecAdapter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/HfsSystemFilesManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/VirtualMapDataAccess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/SizeLimitedStorage.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/NodeInfoTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/VirtualBlobKey.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/initialization/HfsSystemFilesManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/ContractKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/EntityNumVirtualKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/schedule/ScheduleEqualityVirtualKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/temporal/SecondSinceEpocVirtualKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/HapiOpCountersTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/HapiOpSpeedometersTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlowTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/ResponsibleVMapUser.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/StateKeyAdapter.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenStore.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6034 Introduces KeyValuePair record as workaround to have maps in config
  hedera-node/hedera-app-spi/build.gradle.kts
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/internal/KeyValuePairConverter.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/types/KeyValuePair.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/validation/EmulatesMap.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/validation/internal/EmulatesMapValidator.java
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/internal/KeyValuePairConverterTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/validation/BadDefinedRecord.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/validation/CorrectDefinedRecord.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/validation/EmulatesMapValidatorTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#6202 Ensure complete record files and sidecars are written during event stream recovery
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/recordstreaming/RecordStreamingUtils.java
  hedera-node/hapi-utils/src/main/java/module-info.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/recordstreaming/RecordStreamingUtilsTest.java
  hedera-node/hapi-utils/src/test/resources/multipleRecords/2023-04-18T14_08_20.465612003Z.rcd.gz
  hedera-node/hapi-utils/src/test/resources/multipleRecords/2023-04-18T14_08_20.465612004Z.rcd.gz
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryComponentTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamObject.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecoveryRecordsWriter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/forensics/RecordParsers.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamFileWriterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamObjectTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamRecoveryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecoveryRSO.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecoveryRecordsWriterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/Release038xStreamType.java
  hedera-node/hedera-mono-service/src/test/resources/recovery/corruptOnDiskFiles/2023-04-18T14_08_20.465612003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/corruptOnDiskFiles/2023-04-18T14_08_20.465612004Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/full-stream.txt
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_19.942918298Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_20.465612003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_20.465612003Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_22.967161003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_22.967161003Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_24.967604003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_24.967604003Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_26.965090003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_26.965090003Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_28.966975003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_28.966975003Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_30.964623003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_08_30.964623003Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_09_27.742657002Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFiles/2023-04-18T14_09_27.742657002Z.rcd_sig
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFilesAndSidecars/2023-04-19T21_25_00.796582298Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFilesAndSidecars/2023-04-19T21_25_00.796582298Z_01.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFilesAndSidecars/2023-04-19T21_25_02.446651003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFilesAndSidecars/2023-04-19T21_25_02.446651003Z_01.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFilesAndSidecars/2023-04-19T21_25_21.121406003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFilesAndSidecars/2023-04-19T21_25_22.244660003Z.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/onDiskFilesAndSidecars/2023-04-19T21_25_22.244660003Z_01.rcd.gz
  hedera-node/hedera-mono-service/src/test/resources/recovery/recovery-stream-only.txt
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/RecordStreamAccess.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
Labels: CI:FinalChecks

#6239 Migrated ConsensusService to new design
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoFeeAccumulator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoGetTopicInfoUsage.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/AdaptedMonoFeeCalculator.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/MonoFeeAccumulatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/MonoGetTopicInfoUsageTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactoryTest.java
  hedera-node/hedera-consensus-service-impl/build.gradle.kts
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ReadableTopicStoreImpl.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/TopicStore.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ReadableTopicStoreImplTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerParityTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusGetTopicInfoHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusTestUtils.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/module-info.java
  hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/ReadableTopicStore.java
  hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/TopicMetadata.java
Labels: CI:UnitTests, Modularization

#6238 Migrated AdminService to new design
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/ReadableSpecialFileStoreImpl.java
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/handlers/FreezeHandler.java
  hedera-node/hedera-admin-service-impl/src/test/java/com/hedera/node/app/service/admin/impl/test/handlers/FreezeHandlerTest.java
  hedera-node/hedera-admin-service-impl/src/test/java/module-info.java
  hedera-node/hedera-admin-service/src/main/java/com/hedera/node/app/service/admin/ReadableSpecialFileStore.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
Labels: CI:UnitTests, Modularization

#6254 Add MerkleStakingInfo `weight` and export weight in `stake` field
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfo.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/PendingRewardsManagementTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoSerdeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/SeededPropertySource.java
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn0.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn1.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn2.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn3.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn4.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn5.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn6.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn7.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn8.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn9.hex
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
Labels: CI:FinalChecks

#6249 Dagger module for token service
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServiceModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandlersModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowModule.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowModuleTest.java
  hedera-node/hedera-token-service-impl/build.gradle.kts
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/CryptoSignatureWaiversImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/components/TokenServiceModule.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenComponent.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/TokenComponentTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6259 Cross service storages: Simplify PRs
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
Labels: CI:UnitTests, Modularization

#6240 Migrated FileService to new design
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileAppendHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileCreateHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileDeleteHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemDeleteHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileSystemUndeleteHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileUpdateHandler.java
Labels: CI:UnitTests, Modularization

#6241 Migrated NetworkService to new design
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkUncheckedSubmitHandler.java
Labels: CI:UnitTests, Modularization

#6251 Move noop metrics.
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/NoOpMetrics.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/AbstractNoOpMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpCounter.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpDoubleAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpDoubleGauge.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpDurationGauge.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpFunctionGauge.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpIntegerAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpIntegerGauge.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpIntegerPairAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpLongAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpLongGauge.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpMetricsFactory.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpRunningAverageMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpSpeedometerMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpStatEntry.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/noop/internal/NoOpStatsBuffered.java
  platform-sdk/swirlds-common/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/StartUpEventFrozenManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/AbstractEventHandlerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SignedStateManagerBuilder.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/stats/CycleTimingStatTest.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/NoOpMetricsTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/ChatterCoreTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreConsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssMetricsTests.java
Labels: CI:FinalChecks

#6257 Traceability migration now gated only on migration feature flag
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiry.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/ExpiryProcess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/SystemTask.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/TaskModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTask.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/ExpiryProcessTest.java
Labels: CI:FinalChecks

#6244 Migrated SmartContractService to new design
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemDeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemUndeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EtherumTransactionHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractDeleteHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/module-info.java
Labels: CI:UnitTests, Modularization

#6245 Migrated UtilService to new design
  hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/handlers/UtilPrngHandler.java
Labels: CI:UnitTests, Modularization

#6267 Scale up weights while exporting to mirror node
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
Labels: CI:FinalChecks

#6258 Standardize to `ledger.maxAutoAssociations` property limit
  hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/BaseOperationUsage.java
  hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/crypto/CryptoOpsUsage.java
  hedera-node/hapi-fees/src/test/java/com/hedera/node/app/hapi/fees/usage/crypto/CryptoOpsUsageTest.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/utils/AccessorBasedUsages.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfo.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractUpdateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoUpdateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/AccessorBasedUsagesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/PendingRewardsManagementTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoSerdeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractUpdateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoUpdateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecksTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/SeededPropertySource.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn0.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn1.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn2.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn3.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn4.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn5.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn6.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn7.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn8.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn9.hex
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:FinalChecks

#6270 Add some ascii art to Hedara.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
Labels: CI:UnitTests

#6279 Call getNumberOfChildren() less in iterator.
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/iterators/internal/PostOrderedDepthFirstRandomAlgorithm.java
Labels: CI:FinalChecks

#6263 exports com.swirlds.platform.cli to services
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6283 Cherry-pick from 0.37 : Standardize to `ledger.maxAutoAssociations` property limit (#6258)
  hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/pricing/BaseOperationUsage.java
  hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/crypto/CryptoOpsUsage.java
  hedera-node/hapi-fees/src/test/java/com/hedera/node/app/hapi/fees/usage/crypto/CryptoOpsUsageTest.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/fees/calculation/utils/AccessorBasedUsages.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfo.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractUpdateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoUpdateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/fees/calculation/AccessorBasedUsagesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/PendingRewardsManagementTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoSerdeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfoTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractUpdateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/helpers/UpdateCustomizerFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoUpdateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecksTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/utils/SeededPropertySource.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn0.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn1.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn2.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn3.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn4.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn5.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn6.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn7.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn8.hex
  hedera-node/hedera-mono-service/src/test/resources/serdes/MerkleStakingInfo-v2-sn9.hex
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoUpdateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/staking/StakingSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:FinalChecks

#6287 Add new test workflow
  .github/workflows/platform-flow-jrs-daily-regression.yaml
  .github/workflows/platform-zxf-jrs-daily-interval-06.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6231 Update `StakingInfo.weight` midnight UTC
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleHederaStateTest.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleAccountState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleStakingInfo.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/EntityNumValue.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/staking/EndOfStakingPeriodCalculatorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/backing/BackingAccountsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleAccountStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleNetworkContextTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleScheduledTransactionsStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleSpecialFilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/merkle/MerkleTokenRelStatusTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/EntityNumValueTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenValueTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/schedule/ScheduleEqualityVirtualValueTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/schedule/ScheduleSecondVirtualValueTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/VirtualValueDataTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/incomplete.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/precompile-bootstrap.properties
  settings.gradle.kts
Labels: CI:FinalChecks

#6285 Don't require signing keys when doing event stream recovery.
  platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
  platform-sdk/sdk/settings.txt
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
Labels: CI:FinalChecks

#6289 Add addressBook test panel
  .github/workflows/platform-zxf-jrs-daily-interval-06.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6260 consensus service & admin service use new DI pattern
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/AdminServiceModule.java
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/handlers/AdminHandlers.java
  hedera-node/hedera-admin-service-impl/src/main/java/module-info.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServiceModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandlersModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowModule.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowModuleTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ConsensusServiceModule.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusHandlers.java
  hedera-node/hedera-consensus-service-impl/src/main/java/module-info.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ConsensusComponentTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceModule.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenHandlers.java
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FinalChecks

#6275 AppTestBase use simple config
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/AppTestBase.java
Labels: CI:UnitTests, CI:FinalChecks

#6107 ConfigConverter and ConfigSource implementations for the service layer
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/converter/AbstractEnumConfigConverter.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/converter/AccountIDConverter.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/converter/ContractIDConverter.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/converter/FileIDConverter.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/converter/HederaFunctionalityConverter.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/converter/ProfileConverter.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/converter/SidecarTypeConverter.java
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/converter/AbstractEnumConfigConverterTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/converter/AccountIDConverterTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/converter/ContractIDConverterTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/converter/FileIDConverterTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/converter/HederaFunctionalityConverterTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/converter/ProfileConverterTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/config/converter/SidecarTypeConverterTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/CongestionMultipliersConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/EntityScaleFactorsConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/EntityTypeConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/KnownBlockValuesConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/LegacyContractIdActivationsConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/MapAccessTypeConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/RecomputeTypeConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/converter/ScaleFactorConverter.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/source/PropertySourceBasedConfigSource.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/PropertySourceBasedConfigTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/CongestionMultipliersConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/EntityScaleFactorsConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/EntityTypeConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/KnownBlockValuesConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/LegacyContractIdActivationsConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/MapAccessTypeConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/RecomputeTypeConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/converter/ScaleFactorConverterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/source/PropertySourceBasedConfigSourceTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6108 05875 query workflow improvements part3
  hedera-node/docs/design/app/images/Ingest Workflow.drawio.png
  hedera-node/docs/design/app/images/Query Workflow.drawio.png
  hedera-node/docs/design/app/workflows.md
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/AdaptedMonoFeeCalculator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/FeesModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoQueryFeeCheck.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/QueryFeeCheck.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/solvency/MonoSolvencyPreCheck.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/solvency/SolvencyPreCheck.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoFeeCalculatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/queries/validation/QueryFeeCheck.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/SolvencyPrecheck.java
Labels: CI:UnitTests, Modularization

#6264 Add PCLI command to sign account balance files
  hedera-node/cli-clients/build.gradle.kts
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/AccountBalanceCommand.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/AccountBalanceSignCommand.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/AccountBalanceSigningUtils.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/AccountBalanceType.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/SignUtils.java
  hedera-node/cli-clients/src/main/java/module-info.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6223 Create Entity Map Warmer For Performance
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/adapters/VirtualMapLikeAdapter.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/cache/EntityMapWarmer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/adapters/VirtualMapLike.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/EntityNumVirtualKey.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/cache/EntityMapWarmerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/EntityNumVirtualKeyTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, Performance

#6246 Finalize cross service stores
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/accounts/AccountAccess.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/TransactionHandler.java
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/workflows/FakePreHandleContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleContextListUpdatesTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java
Labels: CI:UnitTests, Modularization

#6140 Implement token revoke KYC handle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenRelationStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRevokeKycFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableTokenRelationStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenRevokeKycFromAccountHandlerTest.java
Labels: CI:FinalChecks, Modularization

#6121 #6030 Add throwArgBlank for ArgumentUtils
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/ArgumentUtils.java
Labels: CI:FullStackTests, CI:FinalChecks

#6105 #5380 Introduced MappedConfigSource
  platform-sdk/docs/base/configuration/configuration.md
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/AliasConfigSource.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/ConfigMapping.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/MappedConfigSource.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sources/AliasConfigSourceTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sources/MappedConfigSourceTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigAliases.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigMappings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/config/ConfigMappingsTest.java
Labels: CI:FullStackTests, CI:FinalChecks

#6269 Added system startup diagram.
  platform-sdk/docs/core/system-startup-sequence.svg
  platform-sdk/docs/platformWiki.md
Labels: CI:FinalChecks

#6288 Bump hapi version to 0.38.1
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6222 05761 pces span heuristic
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventMutableFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventStreamConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventReadWriteTests.java
Labels: CI:FinalChecks

#6315 feat: update Platform SDK CI/CD release pipelines to support the integrated repository
  .github/workflows/platform-flow-deploy-ea-release.yaml
  .github/workflows/platform-flow-deploy-mc-release.yaml
  .github/workflows/platform-zxc-release-internal.yaml
  .github/workflows/platform-zxc-release-maven-central.yaml
Labels: CI:FinalChecks

#6290 Distinguish auto-approvals in synthetic `CryptoTransfer` transfer lists
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SynthApprovalRecordsTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/AssertingBiConsumer.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/BaseIdScreenedAssertion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/streams/assertions/TransactionBodyAssertion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysStillWorkAsExpectedSuite.java
Labels: CI:UnitTests, CI:FullStackTests, Hedera Smart Contract Service, CI:FinalChecks

#6319 6316 bump platform version 38 adhoc
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/SignedStateHolder.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflowModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowModule.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/SignedStateViewFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigReqsManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListener.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/SignedStateViewFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/forensics/ServicesIssListenerTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6323 feat: update Platform SDK version number
  settings.gradle.kts
Labels: CI:FinalChecks
