Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-06, with the labels that each got.

#6863 Rename module networkadmin-service to network-admin-service
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-mono-service/build.gradle.kts
  hedera-node/hedera-network-admin-service-impl/build.gradle.kts
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkAdminServiceInjectionModule.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkServiceImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/ReadableRunningHashLeafStoreImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/ReadableSpecialFileStoreImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/codec/MonoSpecialFilesAdapterCodec.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/config/NetworkAdminServiceConfig.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeUpgradeActions.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkAdminHandlers.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetByKeyHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetExecutionTimeHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetVersionInfoHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetRecordHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/UnzipUtility.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/package-info.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/serdes/EntityNumCodec.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/serdes/MonoContextAdapterCodec.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/serdes/MonoRunningHashesAdapterCodec.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/module-info.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/FreezeServiceImplTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/NetworkServiceImplTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/ReadableRunningHashLeafStoreImplTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/codec/MonoSpecialFilesAdapterCodecTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeUpgradeActionsTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/UnzipUtilityTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/serdes/EntityNumSerdesTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/serdes/MonoContextAdapterSerdesTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/serdes/MonoRunningHashesAdapterSerdesTest.java
  hedera-node/hedera-network-admin-service/build.gradle.kts
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/FreezeService.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/NetworkService.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/ReadableRunningHashLeafStore.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/ReadableSpecialFileStore.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/package-info.java
  hedera-node/hedera-network-admin-service/src/main/java/module-info.java
  hedera-node/test-clients/build.gradle.kts
  settings.gradle.kts
Labels: CI:FinalChecks

#6783 save state after reconnect
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateToDiskAttempt.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/TestStateToDiskAttemptConsumer.java
Labels: CI:FinalChecks

#6544 Add HIP-729 design doc
  hedera-node/docs/design/services/smart-contract-service/contract-accounts-nonces.md
Labels: CI:UnitTests, Design

#6884 Update HAPI version
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#6890 Update Release/0.39 branch hedera-protobufs tag
  settings.gradle.kts
Labels: CI:FinalChecks

#6896 Changed HAPI version to add block and running hash state
  settings.gradle.kts
Labels: CI:FinalChecks

#6861 use ledger id from config and not from the netwrok
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/LedgerConfig.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetInfoHandler.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetInfoHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileHandlerTestBase.java
Labels: CI:UnitTests, CI:FinalChecks

#6894 Add more logging when intentionally shutting down JVM.
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SavedStateLoader.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/BrowseCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/common/output/FatalErrorConsumer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoSetup.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/dispatch/triggers/control/ShutdownRequestedTrigger.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/SwirldMenu.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinBrowser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectController.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearnerThrottle.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/EmergencyRecoveryManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/IssHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/Shutdown.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/SystemExitCode.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/SystemExitUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/system/SystemUtils.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/system/SystemUtilsTest.java
Labels: CI:FinalChecks

#6899 injected ledger ID in ConsensusGetTopicInfo
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusGetTopicInfoHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
Labels: CI:FinalChecks

#6865 6846: Accounts integrity violated with accounts.storeOnDisk enabled
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCacheTest.java
Labels: CI:UnitTests, Platform Virtual Map

#6911 fix: browser won't start in PROD mode
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  buildSrc/src/main/kotlin/com/hedera/hashgraph/gradlebuild/rules/IoNettyNativeEpollMetadataRule.kt
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/test-clients/src/itest/resources/network/config/node.properties
  settings.gradle.kts
Labels: CI:FinalChecks

#6546 Remove JasperDbSettingsImpl and move everything to JasperDbConfig
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkSettings.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/JasperDbBuilder.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/VirtualDataSourceJasperDB.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/config/JasperDbConfig.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/DataFileCollection.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/DataFileIterator.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/DataFileWriter.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/hashmap/HalfDiskVirtualKeySet.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/settings/DefaultJasperDbSettings.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/settings/JasperDbSettings.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/settings/JasperDbSettingsFactory.java
  platform-sdk/swirlds-jasperdb/src/main/java/module-info.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSourceJPDB.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/TestJasperDbSettings.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapJPDBReconnectTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/JasperDbSettingsImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/JasperDbSettingsImplTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/RandomVirtualMapJPDBReconnectTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/TestJasperDbSettings.java
Labels: CI:UnitTests, CI:FinalChecks

#6927 Clean up entity id mgmt during hollow account finalization
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKey.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKeyTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
Labels: CI:UnitTests

#6957 Use AccountID instead of EntityNumVirtualKey
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableKVState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskWritableKVState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryReadableKVState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/memory/InMemoryWritableKVState.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/AppTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAccountStore.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAccountStoreImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAccountStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountBalanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTokenHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
Labels: CI:UnitTests

#6959 Use FileID instead of EntityNum as the key into the FILES map
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/ReadableFileStoreImpl.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/WritableFileStoreImpl.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/base/FileQueryBase.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileGetContentsHandler.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/ReadableFileStoreImplTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableFileStoreImplTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetInfoHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileHandlerTestBase.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateHandlerTest.java
Labels: CI:UnitTests

#6919 Network get version info
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/SemanticVersionConverter.java
  hedera-node/hedera-config/src/testFixtures/java/com/hedera/node/config/testfixtures/HederaTestConfigBuilder.java
  hedera-node/hedera-network-admin-service-impl/build.gradle.kts
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/config/SemanticVersionConfig.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetVersionInfoHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/module-info.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkGetVersionInfoHandlerTest.java
Labels: CI:FinalChecks

#6940 6939: Backport #6887 to 0.39
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactory.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/interceptors/UniqueTokensLinkManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/UniqueTokensMigratorTest.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Virtual Map, Platform Data Structures

#6923 Fix flaky unit test.
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreConsensusEventWriterTests.java
Labels: CI:FinalChecks

#6925 Change log marker for pause detector.
  platform-sdk/swirlds-logging/src/main/java/com/swirlds/logging/LogMarker.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
Labels: CI:FinalChecks

#6977 Integrate platform build 0.39.0-alpha.5 to release/0.39 branch
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#6982 Use Helidon for gRPC in mono service
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/ConfigDrivenNettyFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/GrpcModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/HelidonGrpcServerManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/NettyBuilderFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/NettyGrpcServerManager.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/ConfigDrivenNettyFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/NettyGrpcServerManagerTest.java
  settings.gradle.kts
Labels: CI:FinalChecks

#6797 06594 ISS scheduled log error
  platform-sdk/platform-apps/tests/ISSTestingTool/build.gradle.kts
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolConfig.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolMain.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/PlannedIncident.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/PlannedIss.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/PlannedLogError.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/module-info.java
  platform-sdk/sdk/config.txt
Labels: CI:UnitTests

#6953 Fix UI hashgraph sorting bug.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiPlatformAccessor.java
Labels: CI:FinalChecks

#6898 Add contract to hollow account merge e2e test
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKey.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/accounts/ContractCustomizerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKeyTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/Create2MultipleCreates/Create2MultipleCreates.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/Create2MultipleCreates/Create2MultipleCreates.json
  hedera-node/test-clients/src/main/resource/contract/contracts/Create2MultipleCreates/Create2MultipleCreates.sol
Labels: Limechain, CI:UnitTests

#6992 Partial fixes for #6984
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/validators/HgcaaLogValidator.java
Labels: CI:FinalChecks

#6949 Unsupported NetworkAdmin queries
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetByKeyHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetExecutionTimeHandler.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkGetByKeyHandlerTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkGetExecutionTimeHandlerTest.java
Labels: CI:FinalChecks

#6955 NetworkUncheckedSubmit service
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkUncheckedSubmitHandler.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkUncheckedSubmitHandlerTest.java
Labels: CI:FinalChecks

#6978 Remove deprecated registerMonoAdapterSchemas
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/Service.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/records/RecordCache.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/MigrationContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/Schema.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/SchemaTest.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/TestSchema.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MigrationContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheService.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistryTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/SerializationTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/adapters/MerkleMapLikeAdapterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
  hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeSchemaRegistry.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/BytesConverter.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/BootstrapConfig.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/converter/BytesConverterTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ConsensusServiceImpl.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceImpl.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/schemas/GenesisSchema.java
  hedera-node/hedera-file-service-impl/src/main/java/module-info.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileServiceImplTest.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkServiceImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/ReadableRunningHashLeafStoreImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/module-info.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/FreezeServiceImplTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/NetworkServiceImplTest.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/ReadableRunningHashLeafStore.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleServiceImpl.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/ScheduleServiceImplTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractServiceImplTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
  hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/UtilServiceImpl.java
Labels: CI:FinalChecks

#6921 Api permission config
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/PermissionedAccountsRangeConverter.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/PropertySourceBasedConfigTest.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/converter/PermissionedAccountsRangeConverterTest.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/data/ApiPermissionConfigTest.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/data/ConfigDataSupportTest.java
  hedera-node/hedera-config/src/testFixtures/java/com/hedera/node/config/testfixtures/HederaTestConfigBuilder.java
Labels: CI:UnitTests, CI:FinalChecks

#6592 Remove MerkleDbSettingsImpl and move everything to MerkleDbConfig
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkSettings.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbTableConfig.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/AbstractLongList.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileIterator.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/settings/DefaultMerkleDbSettings.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/settings/MerkleDbSettings.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/settings/MerkleDbSettingsFactory.java
  platform-sdk/swirlds-jasperdb/src/main/java/module-info.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbBuilderTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/TestMerkleDbSettings.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/settings/MerkleDbSettingsFactoryTest.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/TestMerkleDbSettings.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapMerkleDbReconnectTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/MerkleDbSettingsImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/MerkleDbSettingsImplTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/RandomVirtualMapMerkleDbReconnectTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/TestMerkleDbSettings.java
Labels: CI:UnitTests, CI:FinalChecks

#6623 Introduce reset implementations for accumulators
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/DoubleAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/LongAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/atomic/AtomicDouble.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultDoubleAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultIntegerAccumulator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultLongAccumulator.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultIntegerAccumulatorTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultIntegerPairAccumulatorTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultLongAccumulatorTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6948 Implemented a basic recycle bin.
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/config/RecycleBinConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/RecycleBin.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/utility/RecycleBinTests.java
Labels: CI:FinalChecks

#6974 Fix flaky qeuue thread busy time test.
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/ControllableQueue.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
Labels: CI:FinalChecks

#6620 Fix #6446 Remove VirtualMapSettingsImpl and use VirtualMapConfig
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkSettings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/VirtualMapSettingsImpl.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/VirtualMapSettingsImplTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/DefaultVirtualMapSettings.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMapSettings.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMapSettingsFactory.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipeline.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/TestVirtualMapSettings.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapSettingsFactoryTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/DummyVirtualRoot.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java
Labels: CI:UnitTests, CI:FinalChecks

#6845 05397 replay pces
  platform-sdk/sdk/settings.txt
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/FileUtils.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformStatNames.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponentFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/StateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/StateManagementComponentFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreconsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/NoOpPreconsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMultiFileIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMutableFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayPipeline.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/PreConsensusEventHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/ReservedSignedState.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateManager.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/AddIncompleteStateTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/EarlySignaturesTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/RegisterStatesWithoutSignaturesTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SequentialSignaturesTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReadWriteTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayPipelineTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayWorkflowTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreconsensusEventWriterTests.java
Labels: CI:FinalChecks

#7011 Change CLASS_ID for HederaSoftwareVersion
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/version/HederaSoftwareVersion.java
Labels: CI:FinalChecks

#6987 06986 Update platform status enum
  platform-sdk/docs/core/platform-status-transitions.svg
  platform-sdk/docs/core/platform-status.md
  platform-sdk/platform-apps/demos/HelloSwirldDemo/src/main/java/com/swirlds/demo/hello/HelloSwirldDemoMain.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/notification/listeners/PlatformStatusChangeNotification.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/DualState.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformStatus.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/platformstatus/PlatformStatus.java
  platform-sdk/swirlds-common/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldTransactionSubmitter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponentFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SignatureTransmitter.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SwirldTransactionSubmitterTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayWorkflowTests.java
Labels: CI:FinalChecks

#7016 Fix `nextExportTime` if time exceeded one exportPeriod
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporter.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
Labels: CI:FinalChecks

#6904 Token Dissociation
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenRelationStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenHandlerHelper.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/IdConvenienceUtils.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenRelListCalculator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/DeleteAllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/ContextualRetrieverTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/IdConvenienceUtilsTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/TokenHandlerHelperTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/TokenRelListCalculatorTest.java
Labels: CI:FinalChecks, Modularization

#7020 Cherry Pick - Fix `nextExportTime` if time exceeded one exportPeriod (#7016)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporter.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
Labels: CI:FinalChecks

#6979 Implement token deletion handler
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDeleteHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
Labels: CI:FinalChecks, Modularization

#7010 More small refinements for Helidon version of GRPC
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/HelidonGrpcServerManager.java
  hedera-node/test-clients/src/eet/java/E2ETestBase.java
  hedera-node/test-clients/src/itest/java/IntegrationTestBase.java
Labels: CI:FinalChecks

#6712 Fix #6447 Remove StateSetttings and move everything to StateConfig
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SavedStateLoader.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingsProvider.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StaticSettingsProvider.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigMappings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectHelper.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectTeacher.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencySignedStateValidator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/EmergencyRecoveryFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/StateSettings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/HashLogger.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateLoaderTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/TestSettings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/HashLoggerTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/TestSettings.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
Labels: CI:UnitTests, CI:FinalChecks

#7013 Implementation of Transaction Get Receipt and some refactor of Get account details
  hedera-node/hedera-network-admin-service-impl/build.gradle.kts
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkAdminHandlerTestBase.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkGetAccountDetailsHandlerTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetReceiptHandlerTest.java
Labels: CI:FinalChecks

#7021 Run spotlessApply on _build.gradle.kts_ files
  hedera-node/build.gradle.kts
  hedera-node/cli-clients/build.gradle.kts
  hedera-node/hapi-fees/build.gradle.kts
  hedera-node/hapi-utils/build.gradle.kts
  hedera-node/hedera-app-spi/build.gradle.kts
  hedera-node/hedera-config/build.gradle.kts
  hedera-node/hedera-evm-impl/build.gradle.kts
  hedera-node/hedera-evm/build.gradle.kts
  hedera-node/hedera-schedule-service-impl/build.gradle.kts
  hedera-node/hedera-smart-contract-service-impl/build.gradle.kts
  hedera-node/hedera-util-service-impl/build.gradle.kts
Labels: CI:FinalChecks

#7028 Make no-min fractional fees viewable via precompiles
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EvmTokenUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/EvmTokenUtilTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
Labels: CI:UnitTests, CI:FinalChecks

#7029 Fix null pointer exception in critical quorum
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/CriticalQuorumImpl.java
Labels: CI:FinalChecks

#7026 Add JUL bridge for log4j
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
  settings.gradle.kts
Labels: CI:FinalChecks

#7030 Move spender validation only for approvals
  hedera-node/data/config/api-permission.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/ApproveAllowanceLogic.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoApproveAllowanceSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteAllowanceSuite.java
Labels: CI:FinalChecks

#7031 Make no-min fractional fees viewable via precompiles
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EvmTokenUtil.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/EvmTokenUtilTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/utils/contracts/precompile/HTSPrecompileResult.java
Labels: CI:FinalChecks

#7032 implement get Record query
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetReceiptHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkTransactionGetRecordHandler.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkAdminHandlerTestBase.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetReceiptHandlerTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/NetworkTransactionGetRecordHandlerTest.java
Labels: CI:FinalChecks

#7035 Allow max response size of 100KiB
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
Labels: CI:FinalChecks

#6996 TokenMint handle() implementation
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/SingleTransactionRecordBuilder.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenRelationStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenRelationStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseCryptoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRevokeKycFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnfreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/records/TokenMintRecordBuilder.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenRelListCalculator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/ApproveAllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/DeleteAllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenSupplyChangeOpsValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableTokenRelationStoreImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableTokenRelationStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAssociateToAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFreezeAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenRevokeKycFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnfreezeAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoTokenHandlerTestBase.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableTokenRelationStore.java
Labels: CI:FinalChecks

#7040 Unsupported token queries
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetAccountNftInfosHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfosHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGetAccountNftInfosHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGetNftInfosHandlerTest.java
Labels: CI:FinalChecks

#6995 Implement CryptoGetAccountInfoHandler
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableStakingInfoStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/utils/RewardCalculator.java
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableStakingInfoStoreImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountInfoHandlerTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableStakingInfoStore.java
Labels: CI:UnitTests, CI:FinalChecks

#6886 6885: Enable / disable data on disk and MerkleDb in dev environments
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/data/config/bootstrap.properties
Labels: CI:UnitTests, CI:FinalChecks, Platform Virtual Map

#7057 Make consistency testing tool play nicely with local testing.
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolConfig.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolState.java
Labels: CI:FinalChecks

#7056 07046 Temporarily disabled tests to unblock other team and buy some time for the investigation
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
Labels: CI:UnitTests, Tech Debt Incurred, CI:FinalChecks

#7062 07061 sync test flake
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/DummyHashgraph.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
Labels: CI:FinalChecks

#6842 Validate manifest file
  platform-sdk/settings.gradle.kts
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SavedStateLoader.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/ValidateManifestFileCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectLearner.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencySignedStateValidator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EmergencyRecoveryManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/Bootstrap.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/EmergencyRecoveryFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/Intervals.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/Location.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/Package.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/Recovery.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/State.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/Stream.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateLoaderTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocolTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencySignedStateValidatorTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventRecoveryWorkflowTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/EmergencyRecoveryFileTests.java
  platform-sdk/swirlds-platform-core/src/test/resources/com/swirlds/platform/recovery/emergencyfile/invalid/emergencyRecovery.yaml
  platform-sdk/swirlds-platform-core/src/test/resources/com/swirlds/platform/recovery/emergencyfile/valid/emergencyRecovery.yaml
Labels: CI:FinalChecks

#7004 07001 queue thread idle callback
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/AbstractQueueThreadConfiguration.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/QueueThreadImpl.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
Labels: CI:FinalChecks

#7049 Use RecycleBin to handle files after discontinuity in PCES.
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/config/RecycleBinConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/RecycleBin.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/RecycleBinImpl.java
  platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/TestRecycleBin.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamConfig.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/utility/RecycleBinTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreconsensusEventWriterTests.java
Labels: CI:FinalChecks

#7050 Set swirlds app thread as users thread to avoid JVM exit
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ThreadDumpGenerator.java
Labels: CI:UnitTests, CI:FinalChecks

#7072 Finish small refinements for Helidon version of GRPC (#6984)
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/GrpcServerManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/HelidonGrpcServerManager.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/HelidonGrpcServerManagerTest.java
Labels: CI:FinalChecks

#7075 Remove False warnings from Settings engine for valid parameters
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
Labels: CI:UnitTests, CI:FinalChecks

#7058 Implement token burn handling
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableNftStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenSupplyChangeOpsValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableNftStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/ParityTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/TokenHandlerHelperTest.java
Labels: CI:FinalChecks, Modularization

#7068 implement TokenGetInfoHandler
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetInfoHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGetInfoHandlerTest.java
Labels: CI:FinalChecks

#7007 7006: Old virtual map copies aren't released during to disk migration
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MapMigrationToDisk.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/UniqueTokensMigrator.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Virtual Map

#7019 7006: Old virtual map copies aren't released during to disk migration
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MapMigrationToDisk.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Virtual Map, Platform Data Structures

#7041 TokenCreate `handle()` implementation
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/SingleTransactionRecordBuilder.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenCreateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/records/TokenCreateRecordBuilder.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAttributesValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenCreateValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenSupplyChangeOpsValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandleParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoTokenHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/TokenHandlerHelperTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/CustomFeesValidatorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/TokenAttributesValidatorTest.java
Labels: CI:FinalChecks

#7039 implement prepareUpgrade in FreezeService
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/WritableStoreFactory.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/ReadableSpecialFileStoreImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/ReadableUpdateFileStoreImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/WritableUpdateFileStore.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/ReadableUpdateFileStoreTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/WritableUpdateFileStoreTest.java
  hedera-node/hedera-network-admin-service-impl/src/test/java/com/hedera/node/app/service/networkadmin/impl/test/handlers/FreezeHandlerTest.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/ReadableSpecialFileStore.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/ReadableUpdateFileStore.java
Labels: CI:FinalChecks, Modularization

#7043 Time interface moved to swirlds-base
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/Time.java
  platform-sdk/swirlds-base/src/main/java/module-info.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/BusyTime.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/CountPerSecond.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultRunningAverageMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultSpeedometerMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/SnapshotService.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/StatsRunningAverage.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/StatsSpeedometer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/internal/StatsBuffer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/config/QueueThreadMetricsConfiguration.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/time/IntegerEpochTime.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/time/OSTime.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/throttle/RateLimiter.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/SnapshotServiceTest.java
  platform-sdk/swirlds-common/src/testFixtures/java/com/swirlds/common/test/fixtures/FakeTime.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventTaskDispatcher.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/ChatterEventCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventReplayWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/protocol/ChatterCore.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/protocol/heartbeat/HeartbeatSendReceive.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/protocol/heartbeat/HeartbeatSender.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/protocol/processing/ProcessingTimeSendReceive.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/protocol/SyncProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/heartbeats/HeartbeatProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/intake/IntakeCycleStats.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ConsensusHandlingMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/EventIntakeMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/ConsensusHashManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/IssHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateHistory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateSentinel.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/stats/cycle/CycleTracker.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeTracker.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/simulated/SimpleSimulatedGossip.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/simulated/SimulatedEventCreationNode.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/network/DelayableIntakeQueue.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/network/TimedEventCreator.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/network/framework/ChatterInstance.java
Labels: CI:UnitTests, CI:FinalChecks

#7077 update of Lock api
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/AutoClosableLock.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/AutoClosableResourceLock.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/IndexLock.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/Locks.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AcquiredOnTry.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AcquiredResource.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AutoLock.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/AutoNoOpLock.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/DefaultIndexLock.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/NotAcquiredResource.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/ResourceLock.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/internal/package-info.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/locks/locked/LockedResource.java
Labels: CI:UnitTests, CI:FinalChecks

#6999 Remove obsolete tests
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Basic-3500-22m.json
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Basic-500-60m.json
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-Basic-500k-60m.json
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCM-BasicStress-2.5k-13m.json
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/resources/FCMFCQ-Basic-1-12m.json
Labels: CI:FinalChecks

#7071 CryptoLiveHash handlers
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoAddLiveHashHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteLiveHashHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetLiveHashHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoAddLiveHashHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteLiveHashHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetLiveHashHandlerTest.java
Labels: CI:FinalChecks

#7048 #6449 Introduce EventConfig
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/EventConfig.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/export/ConfigExportTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingsProvider.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StaticSettingsProvider.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventTaskCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigMappings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncManagerImpl.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/TestSettings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/ConsensusRoundHandlerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/TestSettings.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventTaskCreatorTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
Labels: CI:UnitTests, CI:FinalChecks

#7109 7108: Enable MerkleDb in previewnet, testnet, and mainnet in 0.39
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/preprod/bootstrap.properties
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
Labels: CI:UnitTests, CI:FinalChecks, Platform Data Structures

#7045 ArgumentUtils#throwArgNull replaced by Objects#requireNonNull (for base modules)
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/ArgumentUtils.java
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/function/CheckedConsumer.java
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/function/CheckedFunction.java
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/state/Lifecycle.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/LegacyFileConfigSource.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/MappedConfigSource.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/CountPerSecond.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/config/QueueThreadMetricsConfiguration.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/CommonUtils.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigDataFactory.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigDataService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigNumberUtils.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigPropertiesService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigSourceService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigValidationService.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationBuilderImpl.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConfigurationImpl.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConstraintValidator.java
  platform-sdk/swirlds-config-impl/src/main/java/com/swirlds/config/impl/internal/ConverterService.java
Labels: CI:UnitTests, CI:FinalChecks

#7093 portforwarding moved to com.swirlds.platform
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/Network.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/portforwarding/PortForwarder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/portforwarding/PortMapping.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/portforwarding/PortMappingListener.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/portforwarding/portmapper/MappingRefresher.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/portforwarding/portmapper/PortMapperPortForwarder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/portforwarding/portmapper/PortPair.java
Labels: CI:UnitTests, CI:FinalChecks

#7117 Fix test flake in random event test.
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventTaskCreatorTest.java
Labels: CI:FinalChecks

#7112 More stable maxRateTest()
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/StoppableThreadTests.java
Labels: CI:FinalChecks

#7114 Fix bug where round has no transactions.
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolRound.java
Labels: CI:FinalChecks

#7086 Implement token account wipe
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDeleteHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/IdConvenienceUtils.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenRelListCalculator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenSupplyChangeOpsValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDeleteHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/ParityTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/IdConvenienceUtilsTest.java
Labels: CI:FinalChecks, Modularization

#7110 #6451 Introduce MetricsConfig
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/internal/SettingsCommon.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/RunningAverageMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/SpeedometerMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/config/MetricsConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultMetricsProvider.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultStatEntry.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/prometheus/PrometheusConfig.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/export/ConfigExportTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/RunningAverageMetricConfigTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/SpeedometerMetricConfigTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultMetricsTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultRunningAverageMetricTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultSpeedometerMetricTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/DefaultStatEntryTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/LegacyCsvWriterTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/metrics/platform/prometheus/PrometheusConfigTest.java
  platform-sdk/swirlds-common/src/test/resources/metrics-test.properties
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/ConfigMappings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/MetricsDocUtilsTest.java
Labels: CI:UnitTests, CI:FinalChecks

#7118 Removed terrible `throws Throwable` from some test scenario code, replaced with correct exceptions
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/ScheduleSignScenarios.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/sigs/SigFactory.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/SignedTxnFactory.java
Labels: CI:FinalChecks

#7120 Objects.requireNonNull used in platform-core
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreconsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreconsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/ConsensusRound.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearnerThrottle.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocolResponder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectThrottle.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/iss/IssHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
Labels: CI:UnitTests, CI:FinalChecks

#7089 Time interface is facade for OSTime
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/Time.java
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/time/internal/OSTime.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/BusyTime.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/CountPerSecond.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultRunningAverageMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/DefaultSpeedometerMetric.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/platform/SnapshotService.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/StatsRunningAverage.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/StatsSpeedometer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/statistics/internal/StatsBuffer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/config/QueueThreadMetricsConfiguration.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateSentinel.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/NoOpIntakeCycleStats.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/chatter/SimulatedChatterFactories.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/consensus/TestIntake.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/ChatterCoreTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventTaskDispatcherTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreconsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventReplayWorkflowTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreconsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/ConsensusHashManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssHandlerTests.java
Labels: CI:UnitTests, CI:FinalChecks

#7115 add bi-direction file translator (for migration)
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/codec/FileServiceStateTranslator.java
  hedera-node/hedera-file-service-impl/src/main/java/module-info.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileTestBase.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/ReadableFileStoreImplTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/WritableFileStoreImplTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/codec/FileServiceStateTranslatorTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileAppendTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileCreateTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetContentsTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileGetInfoTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileUpdateTest.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
Labels: CI:FinalChecks

#7066 7053: MerkleDb metadata file must not be changed in saved states
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
Labels: CI:UnitTests

#7131 Make all TokenService validators not depend on `ConfigProvider`
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/info/NodeInfo.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAccountWipeHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenBurnHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenMintHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/AllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/ApproveAllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/DeleteAllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAttributesValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenCreateValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenSupplyChangeOpsValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoDeleteAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoUpdateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAccountWipeHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenBurnHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandleParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenMintHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoTokenHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/AllowanceValidatorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/ApproveAllowanceValidatorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/DeleteAllowanceValidatorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/TokenAttributesValidatorTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/UniqueTokenManagementSpecs.java
Labels: CI:FinalChecks

#7127 06688 pces emergency reconnect3
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EmergencyRecoveryManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/emergencyfile/EmergencyRecoveryFile.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventFileManagerTests.java
Labels: CI:FinalChecks

#7149 Implement TokenGetNftInfoHandler
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGetNftInfoHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGetNftInfoHandlerTest.java
Labels: CI:FinalChecks

#7134 7087: ISS in account store after migration to disk
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/entities/OnDiskAccount.java
Labels: CI:UnitTests, P0, CI:FinalChecks

#7154 Automatically assert `FastCopyable` copies have stable serialization
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
Labels: CI:FinalChecks

#7159 release39 tag changes
  settings.gradle.kts
Labels: CI:FinalChecks

#7179 07046 Fixed excessive logging caused by MemoryIndexDiskKeyValueStoreMergeHammerTest
  platform-sdk/swirlds-jasperdb/build.gradle.kts
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/MemoryIndexDiskKeyValueStoreMergeHammerTest.java
Labels: Tech Debt Reduced

#7171 Added functionality to read original value from WritableKVState
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableKVState.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableKVStateBase.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/WritableKVStateBaseTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/WritableKVStateStack.java
Labels: Modularization

#7139 Implement crypto get account records
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryComponentTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountRecordsHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoGetAccountRecordsHandlerTest.java
Labels: Modularization

#7253 Add pureChecks and validateSemantics for CryptoCreateHandler
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoCreateValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAccountStoreImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/CryptoCreateValidatorTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAccountStore.java
Labels: Modularization

#7100 06703 optional keys in handle
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/signatures/SignatureVerification.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleContext.java
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/itest/java/signatures/SignatureVerificationTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/meta/MonoHandleContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/SignatureExpander.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/CompoundSignatureVerificationFuture.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextVerifier.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/impl/SignatureVerifierImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoProcessLogicTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/CompoundSignatureVerificationFutureTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextVerifierTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleResultTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/signature/ExpandedSignaturePairFactory.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/HederaConfig.java
  hedera-node/hedera-mono-service/src/main/java/module-info.java
Labels: Modularization

#7254 Implement pure checks and validate semantics for crypto transfer
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigRequirementsTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/CryptoTransferScenarios.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerHandleTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerPureChecksTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTransferHandlerTestBase.java
Labels: Modularization

#6373 6347: Evaluating parameter for ValidationUtils.validateTrue() is expensive
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/utils/ValidationUtils.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/utils/ValidationUtilsTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/models/Token.java
Labels: Performance

#7295 API for enhanced signature verification
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/TransactionKeys.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/VerificationAssistant.java
Labels: Modularization

#7225 AttributeValidator and ExpiryValidator
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/AttributeValidator.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/Savepoint.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedExpiryValidator.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/ExpiryValidatorImplTest.java
Labels: Modularization
