Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-05, with the labels that each got.

#6168 Adds junit-pioneer to set of unit test facilities
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/throttling/DeterministicThrottlingTest.java
  settings.gradle.kts
Labels: CI:FinalChecks

#6322 Only clear memo in `TokenUpdateLogic` if client code can signal unset vs empty
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStore.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompileTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6321 5199: VirtualRootNode constructor creates a cache object that doesn't get reused
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Virtual Map, Platform Data Structures

#6338 Abort `EntityAutoExpiry` cycle immediately once all entities are scanned
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiry.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/EntityAutoExpiryTest.java
Labels: Hedera Smart Contract Service, CI:FinalChecks

#6330 06329: Update AddressBookTestingTool README.md
  platform-sdk/platform-apps/tests/AddressBookTestingTool/README.md
Labels: CI:UnitTests

#6214 Refactoring for #5799
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/initialization/BlocklistAccountCreator.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/ServicesTxnManager.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Limechain, CI:UnitTests

#6337 Fix string formatting bug
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/DefaultSignedStateValidator.java
Labels: CI:FinalChecks

#6342 Increase the TPS for AddressBookTestingTool to 1k
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
Labels: CI:FinalChecks

#6317 Add `ExportingRecoveredStateListener`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesApp.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/StateModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/exports/ExportingRecoveredStateListener.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/StateModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/ExportingRecoveredStateListenerTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5568 5319: Optimize virtual node cache flush strategy
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/bytecode/SmartContractByteCodeMapValueSerializerMerkleDb.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBench.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/VirtualMapBench.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/VirtualDataSourceJasperDB.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/DataFileCollection.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/files/MemoryIndexDiskKeyValueStore.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/serialize/BaseSerializer.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/serialize/KeySerializer.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/CloseFlushTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/ExampleLongKeyVariableSize.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/ExampleLongLongKeyVariableSize.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/VirtualMapSerializationTests.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/ExampleVariableSizeDataSerializer.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestValueSerializerMerkleDb.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BreakableDataSource.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/VirtualMapSettingsImpl.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/TestValueSerializerMerkleDb.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/DefaultVirtualMapSettings.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualMapSettings.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSource.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipeline.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/pipeline/VirtualRoot.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/TestVirtualMapSettings.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/datasource/InMemoryDataSource.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCacheTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/RecordAccessorImplTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/DummyVirtualRoot.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/ReconnectHashListenerTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java
Labels: P1, CI:UnitTests, Performance, CI:FinalChecks, Platform Virtual Map, Platform Data Structures

#5878 Refactor CryptoCreate
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/primitives/StateView.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/marshalling/AliasResolver.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JContractAliasKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JWildcardECDSAKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookup.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/WorldLedgers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EntityIdUtils.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAccountStoreImpl.java
Labels: Limechain, CI:UnitTests

#6236 HIP-721: 06026 - add software version to events
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/events/BaseEventHashedData.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/events/Event.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/ChatterEventCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/EventImpl.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/CriticalQuorumTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/EventImplTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/TestUtils.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/event/DetGenerateUtils.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/RecoveryTestUtils.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/TransactionHandlerTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/components/AccessibleEventCreator.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/event/RandomEventUtils.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/simulated/SimulatedEventCreationNode.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/utils/EqualsVerifier.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/EventStringsTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/TransactionHandlingTestUtils.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/GossipEventBuilder.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/creation/EventCreationSimulationTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/validation/EventValidatorTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/EventFactory.java
Labels: CI:FinalChecks

#6339 Abbreviate and shorten JDB test asset names
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/SignedState.swh
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS.vmap
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/iHSD/fSclniHs_Oct20--03-14-49-184_______1104.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/iHSD/fSclniHs_Oct20--03-14-50-248_______1105.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/iHSD/fSclniHs_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/metadata.jdbm
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_Oct20--03-06-48-801________152.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_Oct20--03-06-49-866________153.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_Oct20--03-10-28-422________154.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_Oct20--03-12-07-463________155.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_Oct20--03-12-08-514________156.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_Oct20--03-12-09-573________157.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_Oct20--03-12-10-638________158.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_bucket_index.ll
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/oK2P/fSclnoK2P_metadata.hdhm
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/p2HKV/fSclnp2HKV_Oct20--03-14-49-184_______1104.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/p2HKV/fSclnp2HKV_Oct20--03-14-50-248_______1105.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/p2HKV/fSclnp2HKV_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/pathToDiskLocationInternalNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/fS/pathToDiskLocationLeafNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS.vmap
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/iHSD/sCIKVSclniHs_Oct20--03-14-48-117________784.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/iHSD/sCIKVSclniHs_Oct20--03-14-49-184________785.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/iHSD/sCIKVSclniHs_Oct20--03-14-50-248________786.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/iHSD/sCIKVSclniHs_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/metadata.jdbm
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/oK2P/sCIKVSclnoK2P_Oct20--03-05-30-920_________32.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/oK2P/sCIKVSclnoK2P_Oct20--03-05-33-042_________33.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/oK2P/sCIKVSclnoK2P_Oct20--03-06-48-803_________34.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/oK2P/sCIKVSclnoK2P_bucket_index.ll
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/oK2P/sCIKVSclnoK2P_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/oK2P/sCIKVSclnoK2P_metadata.hdhm
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/p2HKV/sCIKVSclnp2HKV_Oct20--03-14-48-117________784.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/p2HKV/sCIKVSclnp2HKV_Oct20--03-14-49-184________785.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/p2HKV/sCIKVSclnp2HKV_Oct20--03-14-50-248________786.jdb
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/p2HKV/sCIKVSclnp2HKV_metadata.dfc
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/pathToDiskLocationInternalNodes.ll
  hedera-node/hedera-mono-service/src/test/resources/states/0.30.5/sCIKVS/pathToDiskLocationLeafNodes.ll
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6334 06331 - r0.38.0 - `AddressBook.forceUseOfAddressBook` default setting…
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/AddressBookConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookUtils.java
Labels: CI:FinalChecks

#6404 Add feature flag for state ref count debug feature.
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/ReservedSignedState.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
Labels: CI:FinalChecks

#6405 06331 - `AddressBook.forceUseOfAddressBook` default setting to false
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/AddressBookConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookUtils.java
Labels: CI:FinalChecks

#5798 05574 d busy time metric
  platform-sdk/docs/base/metrics/busy-time-metric.md
  platform-sdk/docs/base/metrics/busy-time.svg
  platform-sdk/docs/platformWiki.md
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/atomic/AtomicIntPair.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/BusyTime.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/extensions/CountPerSecond.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/time/IntegerEpochTime.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/ByteUtils.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/metrics/extensions/BusyTimeTest.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/metrics/extensions/CountPerSecondTest.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/time/IntegerEpochTimeTest.java
Labels: CI:UnitTests

#6381 Turn off traceability migration in 0.38
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Hedera Smart Contract Service, CI:FinalChecks

#5919 05779 Sync as protocol
  platform-sdk/swirlds-common/build.gradle.kts
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/SyncPermitProvider.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/SyncPermitProviderTest.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/SyncPermitTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SyncCaller.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/chatter/ChatterSubSetting.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/chatter/config/ChatterConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/heartbeats/HeartbeatProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/SyncMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/communication/NegotiatorThread.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectSettingsImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/SingleNodeNetworkSync.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/SyncProtocolResponder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/config/SyncConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/protocol/PeerAgnosticSyncChecks.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/protocol/SyncProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/heartbeat/HeartbeatProtocolTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/sync/protocol/PeerAgnosticSyncChecksTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/sync/protocol/SyncProtocolTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/network/communication/multithreaded/TestNegotiator.java
Labels: CI:FinalChecks

#6431 06368 d ref count debug flag
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/ReservedSignedState.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
Labels: CI:FinalChecks

#6406 06083 queue thread flush
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/QueueThread.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/AbstractQueueThreadConfiguration.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/QueueThreadImpl.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/AbstractQueueThreadConfigurationTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/PreConsensusEventHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
Labels: CI:FinalChecks

#6432 Cherry pick 6322
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/tokens/HederaTokenStore.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TokenUpdateLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractTokenUpdatePrecompileTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: CI:FinalChecks

#6434 Deleted unused code in platform module
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/streamevent/LoadEventFile.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/streamevent/README.txt
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/APIUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/EventConsumer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/RandomExtended.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StreamEventParser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ThreadDumpGenerator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Utilities.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/VetoSemaphore.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/EventImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/legacy/EventFileParser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/legacy/EventStreamParser.java
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/StreamEventParserTest.java
Labels: CI:FinalChecks

#6442 Lay groundwork for ignoring app transactions during pces replay.
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/platform/FCMQueryControllerTest.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/platform/MockPlatform.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformStatus.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/TransactionSubmitter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
Labels: CI:FinalChecks

#6444 Don't send signature transactions unless the node is active.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponentFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SignatureTransmitter.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
Labels: CI:FinalChecks

#6458 Add query performance test to nightly test panel
  .github/workflows/node-flow-fsts-daily-interval-04.yaml
Labels: CI:UnitTests, CI:FinalChecks

#5962 EVM version update and optimisations
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmMessageCallProcessorV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaBalanceOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmOperationsUtilV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExceptionalHaltReason.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeCopyOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeHashOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeSizeOperationV038.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmMessageCallProcessorV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaBalanceOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmOperationsUtilV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeCopyOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeHashOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeSizeOperationV038Test.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_38Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallCodeOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaOperationUtilV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallCodeOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaOperationUtilV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CreateOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeCopyOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeHashOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeSizeOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC1155ContractInteractions.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/contract/contracts/TestContract/TestContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/TestContract/TestContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/TestContract/TestContract.sol
  hedera-node/test-clients/src/main/resource/precompile-bootstrap.properties
Labels: Limechain, CI:UnitTests, CI:FinalChecks

#6426 6425: Fail to read a data item after data source compaction was interrupted
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/ImmutableIndexedObjectList.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/ImmutableIndexedObjectListUsingArray.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/ImmutableIndexedObjectListUsingMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileCollection.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/ImmutableIndexedObjectListUsingArrayTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileReaderCloseTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileReaderHammerTest.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Virtual Map

#6468 Cherry-pick into 0.38: EVM version update and optimisations (#5962)
  hedera-node/configuration/previewnet/bootstrap.properties
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmMessageCallProcessorV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaBalanceOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmOperationsUtilV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExceptionalHaltReason.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeCopyOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeHashOperationV038.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeSizeOperationV038.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmMessageCallProcessorV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaBalanceOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaDelegateCallOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaEvmOperationsUtilV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeCopyOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeHashOperationV038Test.java
  hedera-node/hedera-evm/src/test/java/com/hedera/node/app/service/evm/contracts/operations/HederaExtCodeSizeOperationV038Test.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_38Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallCodeOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaOperationUtilV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperationV038.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/ContractsModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaMessageCallProcessorV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallCodeOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaOperationUtilV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperationV038Test.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CreateOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeCopyOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeHashOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeSizeOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC1155ContractInteractions.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/contract/contracts/TestContract/TestContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/TestContract/TestContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/TestContract/TestContract.sol
  hedera-node/test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:UnitTests, Hedera Smart Contract Service, CI:FinalChecks

#4855 Add fuzz tests for hollow account completion
  hedera-node/test-clients/src/eet/java/EndToEndTests.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/BiasedDelegatingProvider.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomContractCallSignedBy.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomContractCreateSignedBy.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomHollowAccount.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomHollowAccountDeletion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomOperationSignedBy.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomTokenAssociateSignedBy.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomTransferSignedBy.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenAssociate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/HollowAccountCompletionFuzzing.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/AccountCompletionFuzzingFactory.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/IdFuzzingProviderFactory.java
  hedera-node/test-clients/src/main/resource/eet-config/hollow-account-fuzzing.properties
Labels: Limechain, CI:UnitTests

#6430 Only com.swirlds is scanned by ConfigurationHolder
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/singleton/ConfigurationHolder.java
Labels: CI:UnitTests, CI:FinalChecks

#6474 Continue sending signature transactions during a freeze.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SignatureTransmitter.java
Labels: CI:FinalChecks

#6462 Don't sync slowly in the hashgraph demo.
  platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java
Labels: CI:FinalChecks

#6420 PCES startup lifecycle
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/interrupt/Uninterruptable.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/NoOpPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/utility/UninterruptableTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreConsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java
Labels: CI:FinalChecks

#6480 06479 - AddressBookInitializer do not validate state loaded addressbook
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
Labels: CI:FinalChecks

#6481 Cherry-Pick into v0.38 for 06479 - AddressBookInitializer skip validating state loaded addressbook
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
Labels: CI:FinalChecks

#6459 Update branch to latest protobufs
  settings.gradle.kts
Labels: CI:FinalChecks

#6495 Increment docker timeout
  hedera-node/test-clients/src/eet/java/E2ETestBase.java
  hedera-node/test-clients/src/itest/java/IntegrationTestBase.java
Labels: CI:FinalChecks

#6499 Fix state loading.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
Labels: CI:FinalChecks

#6497 Bump platform version
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6467 Implement token freeze handling
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/workflows/ExceptionConditions.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/TokenFreezeScenarios.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/TokenFreezeFactory.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFreezeAccountHandlerTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableTokenStore.java
Labels: CI:FinalChecks, Modularization

#6341 Di services refactoring part 2
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServiceModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServicesModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandlersModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/DummyPreHandleDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowModule.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowModuleTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusHandlers.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/FileServiceModule.java
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/handlers/FileHandlers.java
  hedera-node/hedera-file-service-impl/src/main/java/module-info.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/FileComponentTest.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/NetworkServiceModule.java
  hedera-node/hedera-network-service-impl/src/main/java/com/hedera/node/app/service/network/impl/handlers/NetworkHandlers.java
  hedera-node/hedera-network-service-impl/src/main/java/module-info.java
  hedera-node/hedera-network-service-impl/src/test/java/com/hedera/node/app/service/network/impl/test/NetworkComponentTest.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/ScheduleServiceModule.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleCreateHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleHandlers.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/ScheduleSignHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/module-info.java
  hedera-node/hedera-schedule-service-impl/src/test/java/com/hedera/node/app/service/schedule/impl/test/ScheduleComponentTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceModule.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractHandlers.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/ContractComponentTest.java
  hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/UtilServiceModule.java
  hedera-node/hedera-util-service-impl/src/main/java/com/hedera/node/app/service/util/impl/handlers/UtilHandlers.java
Labels: CI:UnitTests, CI:FinalChecks

#6494 Flatten buildEventIntake()
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/config/SyncConfig.java
Labels: CI:FinalChecks

#6507 Remove HTS performance test from nightly regression
  .github/workflows/node-flow-fsts-daily-interval-05.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6502 Implement token unfreeze handle()
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/TokenUnfreezeScenarios.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/TokenUnfreezeFactory.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnfreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnfreezeAccountHandlerParityTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnfreezeAccountHandlerTest.java
Labels: CI:FinalChecks, Modularization

#6382 Turn off traceability migration in 0.39 and subsequent releases
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Hedera Smart Contract Service, CI:FinalChecks

#6526 Method name in TestConfigBuilder fixed
  platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/com/swirlds/test/framework/config/TestConfigBuilder.java
Labels: CI:UnitTests, CI:FinalChecks

#6510 Use adjusted account offsets in JRS test
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/AutoAccountCreationValidationsAfterReconnect.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/MixedValidationsAfterReconnect.java
Labels: CI:FinalChecks

#6529 #6528 Add support back for genesisFreezeTime
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/legacy/LegacyConfigPropertiesLoader.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/GenesisStateBuilder.java
Labels: CI:FullStackTests, CI:FinalChecks

#6520 Accommodate varying sig map sizes in `canAutoCreateWithFungibleTokenTransfersToAlias()`
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/HapiTxnOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6376 Remove ChatterSettings and use ChatterConfig instead
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterSettings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterSubSetting.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/protocol/ChatterCore.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/chatter/SimulatedChatterFactories.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/simulated/SimulatedEventCreationNode.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/ChatterCoreTests.java
Labels: CI:FullStackTests, CI:FinalChecks

#6519 Extend software version to use configuration
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/SemanticVersions.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVers.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/SemanticVersionsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVersTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/empty-config.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/incomplete.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetVersionInfo.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/meta/VersionInfoSpec.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:FinalChecks

#6543 Cherry-pick : Extend software version to use configuration (#6519)
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/SemanticVersions.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVers.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/SemanticVersionsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVersTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/serde/SerializedForms.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/incomplete.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetVersionInfo.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/meta/VersionInfoSpec.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
  hedera-node/test-clients/src/main/resource/precompile-bootstrap.properties
Labels: CI:FinalChecks

#6525 Config provided by Dagger
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/meta/HandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/QueryContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaApp.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/VersionedConfigImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/ConfigProviderImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/utils/TestUtils.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryComponentTest.java
  hedera-node/hedera-config/src/testFixtures/java/com/hedera/node/config/testfixtures/HederaTestConfigBuilder.java
Labels: CI:UnitTests, CI:FinalChecks

#6537 Add tests for gas utility functions
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/utils/PrecompilePricingUtilsTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
Labels: CI:FinalChecks

#6540 6538: Large reconnect relates tests fail after recent changes
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/VirtualDataSourceJasperDB.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Reconnect, Platform Data Structures

#6553 update platform build to 0.38.0
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6551 Cherry pick 06537
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/AbstractReadOnlyPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/utils/PrecompilePricingUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/utils/PrecompilePricingUtilsTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
Labels: CI:FinalChecks

#6521 06518 6516 delete platform metrics
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/EventStreamManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/FreezeMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/CriticalQuorumImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventMapper.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/EventCounter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/EventTransactionPool.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/PreConsensusEventHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/shadowgraph/SimultaneousSyncThrottle.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncCaller.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookInitializer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookMetrics.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/CriticalQuorumTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/PreConsensusEventHandlerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/RecoveryTestUtils.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/stream/EventStreamManagerTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/simulated/SimulatedEventCreationNode.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventMapperTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
Labels: CI:FinalChecks

#6558 Only allow positive amounts for transferToken function
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/ZenosBank/ZenosBank.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/ZenosBank/ZenosBank.sol
Labels: CI:FinalChecks

#6346 06010 - pcli event stream info command to accept timestamp
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/report/EventStreamScanner.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamLowerBound.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamMultiFileIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamPathIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamRoundIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamRoundLowerBound.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamTimestampLowerBound.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamMultiFileIteratorTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamPathIteratorTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/cli/EventStreamReportingToolTest.java
Labels: CI:FinalChecks

#6539 6524: Skip sending class IDs for virtual leaf records during reconnects
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/NodeToSend.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualLearnerTreeView.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/reconnect/VirtualTeacherTreeView.java
Labels: CI:UnitTests, Performance, CI:FinalChecks, Platform Reconnect

#6369 6367: Implement getTypicalSerializedSize() method for variable-sized HS virtual map classes
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/IterableContractMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/IterableContractValue.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/OnDiskAccountMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenValue.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobMerkleDbValueSerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobValue.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/entities/OnDiskAccount.java
Labels: CI:UnitTests, CI:FinalChecks

#6573 Cherry pick 06558
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/ZenosBank/ZenosBank.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/ZenosBank/ZenosBank.sol
Labels: CI:FinalChecks

#6575 change platform version to final 0.38
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6564 Move (some) signatures and decoders of versioned ABIs to a dedicated location
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/BurnWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/MintWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/BurnPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MintPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SystemContractAbis.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SystemContractTypes.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/UpdateTokenExpiryInfoPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/WipeFungiblePrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/BurnPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/MintPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SystemContractAbisTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/UpdateTokenExpiryInfoPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/WipeFungiblePrecompileTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6569 0.38.x: Move (some) signatures and decoders of versioned ABIs to a dedicated location
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/BurnWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/MintWrapper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/BurnPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/MintPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SystemContractAbis.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/SystemContractTypes.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/UpdateTokenExpiryInfoPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/WipeFungiblePrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/BurnPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/MintPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SystemContractAbisTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/UpdateTokenExpiryInfoPrecompileTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/WipeFungiblePrecompileTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6482 Added an extended test work flow for platform function change PRs
  .github/workflows/platform-pull-request-extended-checks.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6578 Export the uptime package to the config package.
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
Labels: CI:FinalChecks

#6584 Export sync config to config impl.
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
Labels: CI:FinalChecks

#6378 Remove FCHashMapSettings and use FCHashMapConfig instead
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkSettings.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/ThreadCountPropertyConfigSource.java
  platform-sdk/swirlds-fchashmap/src/main/java/com/swirlds/fchashmap/FCHashMap.java
  platform-sdk/swirlds-fchashmap/src/main/java/com/swirlds/fchashmap/FCHashMapSettings.java
  platform-sdk/swirlds-fchashmap/src/main/java/com/swirlds/fchashmap/FCHashMapSettingsFactory.java
  platform-sdk/swirlds-fchashmap/src/main/java/com/swirlds/fchashmap/config/FCHashMapConfig.java
  platform-sdk/swirlds-fchashmap/src/test/java/com/swirlds/fchashmap/FCHashMapTests.java
  platform-sdk/swirlds-fchashmap/src/test/java/com/swirlds/fchashmap/config/FCHashMapConfigTest.java
  platform-sdk/swirlds-merkle/src/main/java/com/swirlds/merkle/map/MerkleMap.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/FCHashMapSettingsImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
Labels: CI:FullStackTests, CI:FinalChecks

#6591 03400 d extended test lable
  .github/workflows/platform-pull-request-extended-checks.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6549 6548 6518 remove getters
  platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/com/swirlds/demo/crypto/CryptocurrencyDemoMain.java
  platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/com/swirlds/demo/crypto/CryptocurrencyDemoState.java
  platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java
  platform-sdk/platform-apps/demos/HelloSwirldDemo/src/main/java/com/swirlds/demo/hello/HelloSwirldDemoMain.java
  platform-sdk/platform-apps/demos/StatsDemo/src/main/java/com/swirlds/demo/stats/StatsDemoMain.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolMain.java
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
  platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedMapUtils.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
  platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformIdentity.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformWithDeprecatedMethods.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ParameterProvider.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncCaller.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiPlatformAccessor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/SwirldsGui.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/PlatformHashgraphGuiSource.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/SwirldMenu.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTab2Consensus.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTabSecurity.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
Labels: CI:FinalChecks

#6552 remove onlyDefaultHapiSpec
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
Labels: CI:FinalChecks

#6233 Fix #6232 Remove ReconnectSettings and use configuration instead
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/NodeToSend.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/settings/ReconnectSettings.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/settings/ReconnectSettingsFactory.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/streams/AsyncInputStream.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/streams/AsyncOutputStream.java
  platform-sdk/swirlds-common/src/main/java/module-info.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapJPDBReconnectTest.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapMerkleDbReconnectTest.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/FallenBehindManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearnerFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectLearnerThrottle.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocolResponder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectSettingsImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectThrottle.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/ReconnectThrottleTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectProtocolTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocolTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/merkle/AsyncStreamTest.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/merkle/MerkleSynchronizationTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/reconnect/FallenBehindManagerTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java
Labels: CI:FullStackTests, CI:FinalChecks

#6505 05783 consistency testing tool
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/README.md
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/build.gradle.kts
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/gradle.properties
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolConfig.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolMain.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolRound.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/ConsistencyTestingToolState.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/TransactionGenerator.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/com/swirlds/demo/consistency/TransactionHandlingHistory.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/main/java/module-info.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/test/java/com/swirlds/demo/consistency/ConsistencyTestingToolRoundTests.java
  platform-sdk/platform-apps/tests/ConsistencyTestingTool/src/test/java/com/swirlds/demo/consistency/TransactionHandlingHistoryTests.java
  platform-sdk/sdk/config.txt
  platform-sdk/settings.gradle.kts
Labels: CI:FinalChecks

#6567 06565 6548 remove unsafe state access
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/merkle/map/internal/ExpectedMapUtils.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/AppClient.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/UnsafeMutablePTTStateAccessor.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/state/VirtualMerkleStateInitializer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformWithDeprecatedMethods.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
Labels: CI:FinalChecks

#6600 Remove redundant pause check.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
Labels: CI:FinalChecks

#6604 Remove zero stake check in submission
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlow.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlowTest.java
Labels: CI:FinalChecks

#6587 Update .gitignore for new metricsDoc.tsv spew
  .gitignore
Labels: CI:FinalChecks

#6608 Remove zero stake check in submission (#6604)
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlow.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/submission/BasicSubmissionFlowTest.java
Labels: CI:FinalChecks

#6579 Update hedera-protobufs-java version to 0.38.10
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6602 06601 6518 remove get events
  platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/test/java/com/swirlds/demo/merkle/map/MapValueFCQTests.java
  platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformWithDeprecatedMethods.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiPlatformAccessor.java
Labels: CI:FinalChecks

#6622 Remove unwanted check
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/InvariantChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/InvariantChecksTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6440 06303 - deprecating long node ids and adding NodeId API to Address
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/NodeId.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookValidator.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/internal/AddressBookIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ApplicationDefinitionLoader.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/hashgraph/internal/AddressBookMetadata.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTabAddresses.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/connectivity/InboundConnectionHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeTracker.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSigningTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/uptime/UptimeTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/RandomAddressBookGenerator.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/AddressBookStoreTests.java
Labels: CI:FinalChecks

#6597 6585: ReusableBucketPool synchronization redone
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/ReusableBucketPool.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/ReusableBucketPoolTest.java
Labels: CI:UnitTests, Performance, CI:FinalChecks

#6630 6627: FCQueue is not properly destroyed
  platform-sdk/swirlds-fcqueue/src/main/java/com/swirlds/fcqueue/FCQueue.java
Labels: CI:UnitTests, CI:FinalChecks

#6606 Integrate Platform adhoc build 0.39.0-adhoc.xc2987c73 to services dev…
  hedera-node/hedera-app/src/itest/java/grpc/GrpcTestBase.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/MonoServicesMain.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/VersionedConfigImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/platform/PlatformModule.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/AppTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/ServicesMainTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/utils/TestUtils.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryComponentTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/ContextModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/grpc/GrpcStarter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ServicesStatsManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stream/RecordStreamManager.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesAppTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/grpc/GrpcStarterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/StateModuleTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/ExportingRecoveredStateListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/ServicesSignedStateListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/exports/SignedStateBalancesExporterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StatusChangeListenerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/ServicesStatsManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stream/RecordStreamRecoveryTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AddresBookUtils.java
  hedera-node/hedera-mono-service/swirlds-sst-tmp/fileStore/internalHashStoreDisk/fileStore:internalHashes_metadata.dfc
  hedera-node/hedera-mono-service/swirlds-sst-tmp/fileStore/objectKeyToPath/fileStore:objectKeyToPath_bucket_index.ll
  hedera-node/hedera-mono-service/swirlds-sst-tmp/fileStore/objectKeyToPath/fileStore:objectKeyToPath_metadata.dfc
  hedera-node/hedera-mono-service/swirlds-sst-tmp/fileStore/objectKeyToPath/fileStore:objectKeyToPath_metadata.hdhm
  hedera-node/hedera-mono-service/swirlds-sst-tmp/fileStore/pathToHashKeyValue/fileStore:pathToHashKeyValue_metadata.dfc
  hedera-node/hedera-mono-service/swirlds-sst-tmp/smartContractIterableKvStore/internalHashStoreDisk/smartContractIterableKvStore:internalHashes_metadata.dfc
  hedera-node/hedera-mono-service/swirlds-sst-tmp/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_bucket_index.ll
  hedera-node/hedera-mono-service/swirlds-sst-tmp/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_metadata.dfc
  hedera-node/hedera-mono-service/swirlds-sst-tmp/smartContractIterableKvStore/objectKeyToPath/smartContractIterableKvStore:objectKeyToPath_metadata.hdhm
  hedera-node/hedera-mono-service/swirlds-sst-tmp/smartContractIterableKvStore/pathToHashKeyValue/smartContractIterableKvStore:pathToHashKeyValue_metadata.dfc
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6610 Use keccak hash of signed bytes for ECDSA_SECP256K1 message
  hedera-node/docs/design/app/signatures.md
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/signatures/SignatureVerification.java
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/src/itest/java/signatures/SignatureVerificationTest.java
  hedera-node/hedera-app/src/jmh/java/com/hedera/node/app/signature/impl/ExpansionBenchmark.java
  hedera-node/hedera-app/src/jmh/java/com/hedera/node/app/signature/impl/KeccakBenchmark.java
  hedera-node/hedera-app/src/jmh/java/com/hedera/node/app/signature/impl/VerificationBenchmark.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/ExpandedSignaturePair.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/SignatureExpander.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/SignatureVerificationFuture.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/impl/SignatureExpanderImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/impl/SignatureVerificationFutureImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/impl/SignatureVerificationImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/signature/impl/SignatureVerifierImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/CompoundSignatureVerificationFuture.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/impl/SignatureExpanderImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/impl/SignatureVerificationFutureImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/impl/SignatureVerifierImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/CompoundSignatureVerificationFutureTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleResultTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6626 Set ReconnectController state to null after releasing
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
Labels: CI:FinalChecks, CI:PlatformExtendedChecks

#5758 Аdd hollow account finalization doc
  hedera-node/docs/design/services/token-service/hollow-finalization.md
Labels: Limechain, CI:UnitTests, Design

#6629 Remove unwanted check
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/InvariantChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/InvariantChecksTest.java
Labels: CI:FinalChecks

#6632 06304 - Updates Metrics to use non-contiguous NodeIds
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/UptimeData.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/IssMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/NetworkMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/NetworkStatsTransmitter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/address/AddressBookUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/MutableUptimeData.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeDataImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeTracker.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/uptime/UptimeTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/state/IssMetricsTests.java
Labels: CI:FinalChecks

#6646 Implement complete SubmissionManager with expiry dedupe cache
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/HapiUtilsTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/SubmissionManagerTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6624 06008 multinode event stream report
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamInfoCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/report/EventStreamMultiNodeReport.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamMultiFileIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamSingleFileIterator.java
Labels: CI:FinalChecks

#6657 Add token grant kyc checks
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
Labels: CI:FinalChecks, Modularization

#6635 6308 - Crypto and State use non contiguous NodeId
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/PlatformIdentity.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoSetup.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/crypto/CryptoStatic.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/RecoveryPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadata.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SigInfo.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SigSet.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateManager.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/CryptoArgsProvider.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/KeysAndCertsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateLoaderTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateMetadataTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/DefaultSignedStateValidatorTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencySignedStateValidatorTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/RandomSignedStateGenerator.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/SigSetTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/StateSigningTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/AbstractSignedStateManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/AddIncompleteStateTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/EarlySignaturesTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/EmergencyStateFinderTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/OldCompleteStateEventuallyReleasedTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SequentialSignaturesRestartTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/manager/SequentialSignaturesTest.java
Labels: CI:UnitTests

#6668 06667 colorize pcli logs
  platform-sdk/swirlds-cli/color-logs.py
  platform-sdk/swirlds-cli/pcli.sh
Labels: CI:FinalChecks

#6653 06651 Added missing rehash for VirtualMap leaves
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolState.java
Labels: CI:FinalChecks

#6670 integrate with platform adhoc build 0.39.0-adhoc.xa9477c7f
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskKeySerializer.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/StateLifecyclesTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/adapters/VirtualMapLikeAdapterTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/ContractKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/EntityNumVirtualKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/UniqueTokenKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualBlobKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/schedule/ScheduleEqualityVirtualKeySerializer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/temporal/SecondSinceEpocVirtualKeySerializer.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/adapters/VirtualMapLikeTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/VirtualBlobKeySerializer.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AddresBookUtils.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6662 Also log timestamp when ISSTestingToolState provokes an ISS
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
Labels: CI:FinalChecks

#6647 Added comment that hashCode test values must not be changed
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/virtual/ContractKeyTest.java
Labels: CI:FinalChecks

#6678 Add missing migration test panel
  .github/workflows/platform-zxf-jrs-daily-interval-06.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6562 use busy time metric
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/config/QueueThreadMetricsConfiguration.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/AbstractQueueThreadConfiguration.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/QueueThreadImpl.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/QueueThreadMetrics.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/QueueThreadPoolImpl.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/ThreadBuildingUtils.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/AbstractQueueThreadConfigurationTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/PreConsensusEventHandler.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/QueueThreadTests.java
Labels: CI:FinalChecks

#6683 Cause pcli.sh to fall back to no color if the color script is missing
  platform-sdk/swirlds-cli/pcli.sh
Labels: CI:FinalChecks

#6680 Cherry pick #6679
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/StoresModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccessTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6652 06650 - MigrationTestingTool compatible with v0.38 saved state
  platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
  platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolState.java
Labels: CI:FinalChecks

#6563 Add e2e tests for consensus-service
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/AttributeValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/StandardizedAttributeValidator.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-consensus-service-impl/build.gradle.kts
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/ReadableTopicStoreImpl.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/TopicStore.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/WritableTopicStore.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusDeleteTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusGetTopicInfoHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusSubmitMessageHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/records/ConsensusSubmitMessageRecordBuilder.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/records/SubmitMessageRecordBuilder.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/ReadableTopicStoreImplTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerParityTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicHandlerParityTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusDeleteTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusGetTopicInfoHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageHandlerParityTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusSubmitMessageHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusTestUtils.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/records/SubmitMessageRecordBuilderTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/module-info.java
  hedera-node/hedera-consensus-service/src/main/java/com/hedera/node/app/service/consensus/ReadableTopicStore.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6696 Add ReadableQueueState and WritableQueueState to the SPI and Merkle implementation
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/EmptyReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/EmptyWritableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/FilteredReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/FilteredWritableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableQueueState.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableQueueStateBase.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/ReadableStates.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/StateDefinition.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableQueueState.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableQueueStateBase.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableStates.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/EmptyReadableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/EmptyWritableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/FilteredReadableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/FilteredWritableStatesTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/ReadableQueueStateBaseTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/StateDefinitionTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/StateTestBase.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/WritableQueueStateBaseTest.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/ListReadableQueueState.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/ListWritableQueueState.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapReadableStates.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/state/MapWritableStates.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleSchemaRegistry.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/queue/QueueNode.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/queue/ReadableQueueStateImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/queue/WritableQueueStateImpl.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleHederaStateTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/SerializationTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6679 Refactor top-level sig check
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/StoresModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccess.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/MutableEntityAccessTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#6691 06671 NodeId implements SelfSerializable
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/NodeId.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SigSet.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/uptime/UptimeDataImpl.java
Labels: CI:FinalChecks

#6685 06037 Enabled leaf rehashing for existing VirtualMap instances.
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/VirtualMapFactory.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: CI:UnitTests, CI:FinalChecks

#6681 6656: Inconsistency between VirtualNodeCache and DataSource during snapshots
  platform-sdk/swirlds-benchmarks/settings.txt
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BaseBench.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBench.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBenchMerkleDb.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/VirtualMapBench.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/config/BenchmarkConfig.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSourceBuilder.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceSnapshotMergeTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbSnapshotTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
Labels: P1, CI:UnitTests, CI:FinalChecks, Platform Virtual Map

#6542 Add optional keys and optional hollow accounts to pre-handle context
  .gitignore
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreCheckException.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/workflows/FakePreHandleContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImpl.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FinalChecks

#6665 Reflect mainnet 0.0.111 (fees) and 0.0.123 (throttles) contents in repo
  hedera-node/configuration/mainnet/upgrade/feeSchedules.json
  hedera-node/configuration/mainnet/upgrade/throttles.json
  hedera-node/hedera-mono-service/src/main/resources/feeSchedules.json
  hedera-node/hedera-mono-service/src/main/resources/throttles.json
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4818 Update HIP-583 design doc and test plan
  hedera-node/docs/design/services/token-service/alias-configuration.md
  hedera-node/docs/test-plans/hip-583.md
Labels: Limechain, CI:UnitTests

#6527 04632 Fuzzing test for LazyCreate through precompiles
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/precompile/RandomERC20TransferLazyCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/precompile/RandomERC721TransferLazyCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/precompile/RandomFungibleTransferLazyCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/precompile/RandomHbarTransferLazyCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/precompile/RandomNonFungibleTransferLazyCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/AddressAliasIdFuzzing.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/IdFuzzingProviderFactory.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/utils/ECDSAKeysUtils.java
  hedera-node/test-clients/src/main/resource/eet-config/lazycreate-precompile-fuzzing.properties
Labels: Limechain, CI:UnitTests

#6697 Add `pureChecks()` method to TransactionHandler
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreCheckException.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/TransactionHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoCreateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRevokeKycFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnfreezeAccountHandler.java
Labels: CI:FinalChecks

#6721 06720: Added contracts.nonces.externalization.enabled feature flag
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Limechain, CI:UnitTests

#6717 06716 MAX_FULL_REHASHING_BUFFER_TIMEOUT is increased to 60 seconds.
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapHashingTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNodeTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6733 Use instantaneous capacity checks for gauges and `TraceabilityExportTask`
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottle.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottle.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitBucketThrottle.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottle.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/BucketThrottleTest.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/DeterministicThrottleTest.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/GasLimitBucketThrottleTest.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/GasLimitDeterministicThrottleTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTask.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/stats/ThrottleGauges.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/tasks/TraceabilityExportTaskTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/stats/ThrottleGaugesTest.java
Labels: CI:FinalChecks

#6699 PreHandle and QueryContext.configuration
  hedera-node/hedera-app-spi/build.gradle.kts
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreHandleContext.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/QueryContext.java
  hedera-node/hedera-app-spi/src/main/java/module-info.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/workflows/FakePreHandleContext.java
  hedera-node/hedera-app/src/itest/java/signatures/SignatureVerificationTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleResult.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoProcessLogicTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleContextListUpdatesTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleResultTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
Labels: CI:UnitTests, Modularization

#6740 06737 - AddressBook.toConfigText() Supports Memo
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java
Labels: CI:FinalChecks

#6744 06739 Add helpful debug messages for JRS failure
  platform-sdk/platform-apps/tests/ISSTestingTool/src/main/java/com/swirlds/demo/iss/ISSTestingToolState.java
Labels: CI:FinalChecks

#6718 Consolidate all records in single `FCQueue`
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/mocks/MockRecordsHistorian.java
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/mocks/MockTransactionContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/BasicTransactionContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/TransactionContext.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/init/EntitiesInitializationFlow.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/HederaLedger.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordsHistorian.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorian.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/expiry/ExpiryManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/AccountStorageAdapter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/MapMigrationToDisk.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/RecordConsolidation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/RecordsStorageAdapter.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/StateChildIndices.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/migration/StorageStrategy.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/submerkle/ExpirableTxnRecord.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/BasicTransactionContextTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/init/EntitiesInitializationFlowTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ledger/HederaLedgerLiveTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/records/TxnAwareRecordsHistorianTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/expiry/ExpiryManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/AccountStorageAdapterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/MapMigrationToDiskTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/RecordConsolidationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/migration/RecordsStorageAdapterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/schedule/ScheduleCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/UtilsConstructorTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests, CI:FinalChecks

#6663 Handle old events
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/AdaptedMonoProcessLogic.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoProcessLogicTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVers.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/records/RecordCache.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/StandardProcessLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/ProcessLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/SerializableSemVersTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/records/RecordCacheTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/StandardProcessLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/ProcessLogicTest.java
Labels: CI:FinalChecks

#6669 Create platform status readme
  platform-sdk/docs/core/platform-status-transitions.svg
  platform-sdk/docs/core/platform-status.md
  platform-sdk/docs/platformWiki.md
Labels: CI:FinalChecks

#6734 Allow queried `TransactionID` to have deleted payer account
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/queries/meta/GetTxnRecordAnswer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/helpers/DeletionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/queries/meta/GetTxnRecordAnswerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/helpers/DeletionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractDelete.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoDeleteSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleExecutionSpecs.java
Labels: CI:UnitTests, CI:FinalChecks

#6738 Properly clear pipelines before a reconnect.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/GossipFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SingleNodeSyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
Labels: CI:FinalChecks, CI:PlatformExtendedChecks

#6756 Added script for merging config.txt and currentAddressBook.txt.
  platform-sdk/swirlds-cli/misc/generate-new-node-config.py
Labels: CI:UnitTests

#6766 file service fix the configuration method
  hedera-node/hedera-file-service-impl/src/main/java/com/hedera/node/app/service/file/impl/utils/FileServiceUtils.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileDeleteHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemDeleteHandlerTest.java
  hedera-node/hedera-file-service-impl/src/test/java/com/hedera/node/app/service/file/impl/test/handlers/FileSystemUndeleteHandlerTest.java
Labels: CI:UnitTests, CI:FinalChecks

#6748 06737 - AddressBook.toConfigText() Supports Memo Field
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java
Labels: CI:FinalChecks

#6609 Implement Token Association to Account
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/MonoTransactionDispatcherTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/TxnHandlingScenario.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenRelationStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenRelationStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableTokenStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/ContextualRetriever.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenAssociateToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFeeScheduleUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenFreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenGrantKycToAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenPauseHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRevokeKycFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnfreezeAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUnpauseHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CustomFeesValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenListChecks.java
  hedera-node/hedera-token-service-impl/src/main/java/module-info.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableTokenRelationStoreImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableTokenRelationStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableTokenStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/ContextualRetrieverTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoTokenHandlerTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/ParityTestBase.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenAssociateToAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFeeScheduleUpdateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenFreezeAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenGrantKycToAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenPauseHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenRevokeKycFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnfreezeAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUnpauseHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/util/SigReqAdapterUtils.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/TokenListChecksTest.java
  hedera-node/hedera-token-service-impl/src/test/java/module-info.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableTokenRelationStore.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableTokenStore.java
Labels: CI:FinalChecks, Modularization

#6772 Bump platform version to 0.38.3
  .github/workflows/platform-zxcron-release-jrs-regression.yaml
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks, CI:PlatformExtendedChecks

#6743 Config sources for services defined
  buildSrc/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  hedera-node/hedera-app/application.properties
  hedera-node/hedera-app/build.gradle.kts
  hedera-node/hedera-app/for-test/application.properties.test
  hedera-node/hedera-app/for-test/genesis.properties.test
  hedera-node/hedera-app/genesis.properties
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/GenesisUsage.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/config/ConfigProviderImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryComponentTest.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/sources/PropertyConfigSource.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#6777 Update zero weights for new nodes
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/AddresBookUtils.java
Labels: CI:FinalChecks

#6769 6763: FCQueue.getHash() is a hashing bottleneck
  platform-sdk/swirlds-fcqueue/src/main/java/com/swirlds/fcqueue/FCQueue.java
Labels: CI:UnitTests, CI:FinalChecks

#6754 Implement the modular record cache
  hedera-node/hapi/src/main/java/module-info.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/records/RecordCache.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/DeduplicationCache.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaRecordCache.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/HederaStateInjectionModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/WrappedHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleHederaState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MerkleRecordCache.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/MonoRecordCache.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/DeduplicationCacheImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/recordcache/RecordCacheService.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/stack/SavepointStackImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/DeduplicationCacheTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/RecordCacheImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/recordcache/RecordCacheServiceTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/SubmissionManagerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImplTest.java
  hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeHederaState.java
  hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeRecordCache.java
  hedera-node/hedera-app/src/testFixtures/java/com/hedera/node/app/fixtures/state/FakeSchemaRegistry.java
  settings.gradle.kts
Labels: CI:UnitTests, CI:FinalChecks

#6695 06305 Browser and Platform support noncontiguous NodeId
  platform-sdk/platform-apps/demos/CryptocurrencyDemo/src/main/java/com/swirlds/demo/crypto/CryptocurrencyDemoMain.java
  platform-sdk/platform-apps/demos/HashgraphDemo/src/main/java/com/swirlds/demo/hashgraph/HashgraphDemoMain.java
  platform-sdk/platform-apps/demos/HelloSwirldDemo/src/main/java/com/swirlds/demo/hello/HelloSwirldDemoMain.java
  platform-sdk/platform-apps/demos/StatsDemo/src/main/java/com/swirlds/demo/stats/StatsDemoMain.java
  platform-sdk/platform-apps/tests/MigrationTestingTool/src/main/java/com/swirlds/demo/migration/MigrationTestingToolMain.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/AppClient.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
  platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/EventStreamManager.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/stream/QueueThreadObjectStreamConfiguration.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/framework/internal/AbstractThreadConfiguration.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/framework/internal/AbstractQueueThreadConfigurationTest.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/ApplicationDefinitionLoader.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/BrowseCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/EventCreatorThread.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/PreConsensusEventHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/AbstractGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SingleNodeSyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/GuiPlatformAccessor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/SwirldsGui.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/PlatformHashgraphGuiSource.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/SwirldMenu.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTab2Consensus.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gui/internal/WinTabSecurity.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/ApplicationDefinitionLoaderTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/ConsensusQueueTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/ConsensusRoundHandlerTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/StoppableThreadTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/ThreadTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/SwirldStateTracker.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/TransactionFeeder.java
Labels: CI:FinalChecks, CI:PlatformExtendedChecks

#6787 setup release 0.39 branch
  .github/workflows/config/node-release.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6557 6556: Teacher should stop teaching if it falls behind while teaching
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/TeachingSynchronizer.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/synchronization/internal/TeacherSendingThread.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapMerkleDbReconnectTest.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/chatter/ChatterGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/LegacySyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/gossip/sync/SyncGossip.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectProtocolResponder.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/ReconnectTeacher.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocol.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTeacher.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/ReconnectTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocolTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/merkle/util/LaggingTeachingSynchronizer.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/merkle/util/MerkleTestUtils.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Reconnect

#6801 delay release 0.39 branch creation to next Tuesday
  .github/workflows/config/node-release.yaml
Labels: CI:UnitTests, CI:FinalChecks

#6779 Allow `INVALID_SIGNATURE` status on `EthTx` value sent to EOA with `receiverSigRequired=true`
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/EthereumTransferToRandomEVMAddress.java
Labels: CI:UnitTests, CI:FinalChecks

#6795 6794: Enable data on disk and MerkleDb for nightly services runs
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/data/config/bootstrap.properties
Labels: CI:FinalChecks

#6796 06788 Better handling of failed async hashing
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/exceptions/FailedRehashException.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/merkle/utility/MerkleUtils.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/merkle/MerkleRehashTests.java
Labels: CI:UnitTests, Tech Debt Reduced, CI:FinalChecks

#6808 6806: MerkleDb compactions are stopped after a snapshot
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
Labels: CI:UnitTests, CI:FinalChecks, Platform Virtual Map, Platform Data Structures

#6804 Fix Hedera so it can start again
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/ServicesMain.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests

#6810 Revert "Turn off traceability migration in 0.38 (#6381)"
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:UnitTests, CI:FinalChecks

#6813 Add extra information to state dump log.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
Labels: CI:FinalChecks

#6643 Bytes Converter added for Config
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/config/ConfigProviderImpl.java
  hedera-node/hedera-config/build.gradle.kts
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/converter/BytesConverter.java
  hedera-node/hedera-config/src/main/java/module-info.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/PropertySourceBasedConfigTest.java
  hedera-node/hedera-config/src/test/java/com/hedera/node/config/converter/BytesConverterTest.java
  hedera-node/hedera-config/src/testFixtures/java/com/hedera/node/config/testfixtures/HederaTestConfigBuilder.java
Labels: CI:UnitTests, CI:FinalChecks
