Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-08, with the labels that each got.

#7696 Add EIP 2930 support to EthTXData
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigs.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigsTest.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: P1, Feature Enhancement, Hedera Smart Contract Service

#7808 Add support for test package runs for HapiTestEngine
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/HapiTestEngine.java
Labels: Modularization

#7797 cherry-pick Add EIP 2930 support to EthTXData (#7696)
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigs.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxSigsTest.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/ethereum/EthereumTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: P1, Limechain, Feature Enhancement, Hedera Smart Contract Service

#7811 Fix Sonar errors in token-service-impl
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableTokenStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/codec/NetworkingStakingTranslator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountBalanceHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoGetAccountInfoHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenDissociateFromAccountHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenHandlers.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakeIdChangeType.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakePeriodManager.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomFractionalFeeAssessor.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/customfees/CustomRoyaltyFeeAssessor.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/AllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/ApproveAllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/DeleteAllowanceValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/StakingValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenAttributesValidator.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/TokenSupplyChangeOpsValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/codec/NetworkingStakingTranslatorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoApproveAllowanceHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/CryptoCreateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/FinalizeParentRecordHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenCreateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenDissociateFromAccountHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/staking/StakingRewardsHandlerImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/AutoAccountCreatorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/transfer/CustomFeeAssessmentStepTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/ApproveAllowanceValidatorTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/CustomFeesValidatorTest.java
Labels: Modularization

#7964 07926 mismatched sender owner nft
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/WorldLedgers.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/WorldLedgersTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/OwnershipCheck/OwnershipCheck.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/OwnershipCheck/OwnershipCheck.json
  hedera-node/test-clients/src/main/resource/contract/contracts/OwnershipCheck/OwnershipCheck.sol
Labels: P1, Bug, Limechain, Hedera Smart Contract Service

#7999 Cherry pick - mismatched sender owner nft
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/WorldLedgers.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/WorldLedgersTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/OwnershipCheck/OwnershipCheck.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/OwnershipCheck/OwnershipCheck.json
  hedera-node/test-clients/src/main/resource/contract/contracts/OwnershipCheck/OwnershipCheck.sol
Labels: Hedera Smart Contract Service

#7933 Fix Sonar errors in hedera-app-spi, hapi-utils, and hapi-fees
  hedera-node/hapi-fees/src/main/java/com/hedera/node/app/hapi/fees/usage/QueryUsage.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/FileSignTool.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exports/RecordBlockNumberTool.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/fee/SmartContractFeeBuilder.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/sysfiles/validation/ExpectedCustomThrottlesTest.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/throttles/ConcurrentThrottleTestHelper.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/key/KeyUtils.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/state/WritableQueueStateBase.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/FreeQueryHandler.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleException.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/PreCheckException.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/key/KeyUtilsTest.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/state/WritableKVStateBaseTest.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/TestBase.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/fees/FakeFeeAccumulator.java
  hedera-node/hedera-app-spi/src/testFixtures/java/com/hedera/node/app/spi/fixtures/util/LogCaptureExtension.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/TestLongCodec.java
Labels: Modularization

#7331 Updated contract nonces design doc
  hedera-node/docs/design/services/smart-contract-service/contract-accounts-nonces.md
Labels: Limechain

#8072 07960 updating the special files handling for throttles
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleManager.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacility.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/HederaTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/ThrottleManagerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacilityTest.java
Labels: Modularization

#8174 6475: com.swirlds.merkledb.files.DataFileCollectionTest test flake
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileCollectionTest.java
Labels: Test Development, Tech Debt Reduced, Platform Virtual Map, Platform Data Structures

#7886 Adhoc Docker images from branches
  .github/workflows/node-zxc-build-release-artifact.yaml
Labels: P1, Feature Enhancement

#7571 Fix code style comments
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizer.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCreateOperationExternalizerTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
Labels: Limechain

#8147 Call ExchangeRateManager.update in SystemFileUpdateFacility
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/Hedera.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/HederaInjectionComponent.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacility.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/components/IngestComponentTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/SystemFileUpdateFacilityTest.java
Labels: Modularization

#7916 Fix Sonar errors in cli-clients module
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/AccountBalanceSigningUtils.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/sign/RecordStreamSigningUtils.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/signedstate/DumpAccountsSubcommand.java
Labels: Modularization

#8183 Implement frontend throttle
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/MonoThrottleAccumulator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/ThrottleManager.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/throttle/MonoThrottleAccumulatorTest.java
Labels: Modularization

#8199 fix: IllegalAccessException preventing mono local node run
  build-logic/src/main/kotlin/com.hedera.hashgraph.jpms-modules.gradle.kts
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/MonoServicesMain.java
  hedera-node/hedera-app/src/main/java/module-info.java
  hedera-platform/build.gradle.kts
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
Labels: Bug
