Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2023-03, with the labels that each got.

#5088 Fix minGenInfo in signed state.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerDouble.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerSingle.java
Labels: CI:FinalChecks

#5021 4659 token balances reconcile
  hedera-node/test-clients/src/itest/java/AllIntegrationTests.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TokenReconciliationValidator.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/validators/AccountNumTokenNum.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TokenBalanceValidation.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5126 Implement `TopicUpdate` handle logic
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/exceptions/HandleStatusException.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/validation/ExpiryValidator.java
  hedera-node/hedera-app-spi/src/test/java/com/hedera/node/app/spi/exceptions/HandleStatusExceptionTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/AdaptedMonoTransitionRunner.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoTransitionRunnerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidatorTest.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusCreateTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/main/java/com/hedera/node/app/service/consensus/impl/handlers/ConsensusUpdateTopicHandler.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusCreateTopicHandlerTest.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusHandlerTestBase.java
  hedera-node/hedera-consensus-service-impl/src/test/java/com/hedera/node/app/service/consensus/impl/test/handlers/ConsensusUpdateTopicHandlerTest.java
Labels: CI:UnitTests

#5155 Update mainnet settings to enable prometheus
  hedera-node/configuration/mainnet/settings.txt
Labels: CI:UnitTests

#5114 Dashboard handoff
  hedera-node/infrastructure/dashboards/all-stats-prom.json
  hedera-node/infrastructure/dashboards/arbitrary-stat-prom.json
  hedera-node/infrastructure/dashboards/important-stats-prom.json
  hedera-node/infrastructure/dashboards/jasperdb-node-details-prom.json
  hedera-node/infrastructure/dashboards/network-details-prom.json
Labels: CI:FinalChecks

#5154 Disable transThrottle.
  hedera-node/configuration/compose/settings.txt
  hedera-node/configuration/dev/settings.txt
  hedera-node/configuration/mainnet/settings.txt
  hedera-node/configuration/preprod/settings.txt
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/configuration/testnet/settings.txt
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
Labels: CI:FinalChecks

#5455 enable node software compression of recordstream and account balance files for mainnet
  hedera-node/configuration/mainnet/bootstrap.properties
  hedera-node/configuration/testnet/bootstrap.properties
Labels: CI:FinalChecks

#5097 Rework system transaction handling
  platform-sdk/docs/PlatformThreads.drawio.svg
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/FreezeManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StartUpEventFrozenManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SyncManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/SystemTransactionHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/SystemTransactionHandlerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/StateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/TransactionPool.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/TransactionSupplier.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/TransactionTracker.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PostConsensusSystemTransactionConsumer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PostConsensusSystemTransactionHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PostConsensusSystemTransactionManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PostConsensusSystemTransactionManagerFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PostConsensusSystemTransactionTypedHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PreConsensusSystemTransactionConsumer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PreConsensusSystemTransactionHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PreConsensusSystemTransactionManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PreConsensusSystemTransactionManagerFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/PreConsensusSystemTransactionTypedHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/internal/PostConsensusSystemTransactionManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/system/internal/PreConsensusSystemTransactionManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncAndCreateRule.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncAndCreateRuleResponse.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncAndCreateRules.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncRule.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/creation/ChatterEventCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/EventTransactionPool.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerDouble.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerSingle.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/AbstractEventHandlerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/ConsensusRoundHandlerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/SwirldStateManagerDoubleTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/DummySystemTransaction.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/components/AccessibleEventCreator.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventCreatorTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/PostConsensusSystemTransactionManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/PreConsensusSystemTransactionManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/SystemTransactionHandlerTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/TransactionHandlingTestUtils.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/TransactionTrackerTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/SystemTransactionTracker.java
Labels: CI:FinalChecks

#5122 Skeleton Mindmap
  platform-sdk/docs/components/components.drawio.svg
  platform-sdk/docs/components/components.html
  platform-sdk/docs/configuration/README.MD
  platform-sdk/docs/configuration/config-modules.svg
  platform-sdk/docs/mindmap-node.drawio.svg
  platform-sdk/docs/mindmap-node.html
Labels: CI:UnitTests

#5113 Adding metric to track closing connection frequency
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SocketConnection.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/ConnectionTracker.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/network/NetworkMetrics.java
Labels: CI:UnitTests, CI:FinalChecks

#5452 5450 short circuiting event stream unit tests when they fail randomly in PRs.
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamMultiFileIteratorTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamRoundIteratorTest.java
Labels: CI:UnitTests, CI:FinalChecks

#5470 Fix Broken Documentation Link
  .gitignore
  platform-sdk/docs/mindmap-node.drawio.svg
  platform-sdk/docs/mindmap-node.html
Labels: CI:FinalChecks

#5490 feat: update the repository code owner definitions
  .github/CODEOWNERS
Labels: CI:FinalChecks

#5447 5446: MerkleDb throws an exception on restore, if the shared DB dir doesn't exist
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
Labels: CI:UnitTests, CI:FinalChecks

#5192 Fix action sidecars missing expected fields
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/traceability/HederaEvmOperationTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/SolidityActionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LogCaptor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LoggingSubject.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
Labels: CI:UnitTests

#5484 Mono-service fixes for PBJ-branch
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/codec/CodecFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/codec/MonoMapCodecAdapter.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/AbstractVirtualCodecTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/CodecFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/DataBufferTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/MonoMapSerdesAdapterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/UtilsConstructorTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/VirtualKeySerdesAdapterTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/codec/VirtualValueSerdesAdapterTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
Labels: Modularization

#5103 pcli command to repair a damaged event stream
  platform-sdk/swirlds-cli/src/main/java/com/swirlds/cli/utility/ParameterizedClass.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRepairCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamSingleFileIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamSingleFileRepairIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/EventStreamSingleFileRepairer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/internal/ObjectStreamIterator.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/cli/EventStreamSingleFileRepairTest.java
Labels: CI:UnitTests, CI:FinalChecks

#5489 Add thread diagram to mindmap
  platform-sdk/docs/PlatformThreads.drawio.svg
  platform-sdk/docs/mindmap-node.drawio.svg
  platform-sdk/docs/mindmap-node.html
  platform-sdk/docs/threads/eventflow-threads.drawio.svg
  platform-sdk/docs/threads/eventflow-threads.html
Labels: CI:FinalChecks

#5444 remove trans throttle
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/BasicConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/FreezeManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SettingConstants.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Settings.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/StartUpEventFrozenManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SyncCaller.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SyncManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventCreator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/StateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/TransactionTracker.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncAndCreateRule.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncAndCreateRuleResponse.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncAndCreateRules.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/transaction/throttle/TransThrottleSyncRule.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/EventTransactionPool.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerImpl.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/SwirldStateManagerUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/sync/SyncManager.java
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/FreezeManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SettingsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/StartUpEventFrozenManagerTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SyncManagerTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/components/AccessibleEventCreator.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventCreatorTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/TransactionTrackerTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/sync/TestingSyncManager.java
Labels: CI:FinalChecks

#5270 5269: Improve data file migration to MerkleDb on node startup
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5544 Write timestamps to recovery YAML
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/jackson/InstantDeserializer.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/jackson/InstantDeserializerTests.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamRecoverCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/EmergencyRecoveryFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateLoaderTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectProtocolTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencyReconnectTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/emergency/EmergencySignedStateValidatorTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventRecoveryWorkflowTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/EmergencyRecoveryFileTests.java
Labels: CI:FinalChecks

#5535 Action sidecars missing field fix cherry-pick to 0.36
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/HederaEvmTxProcessor.java
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/execution/traceability/HederaEvmOperationTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/EvmTxProcessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/HederaTracer.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/execution/traceability/SolidityAction.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/HederaTracerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/execution/SolidityActionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LogCaptor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/test/extensions/LoggingSubject.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
Labels: CI:FinalChecks

#5569 Fix tests in smart contract impl module
  hedera-node/hedera-admin-service-impl/src/main/java/com/hedera/node/app/service/admin/impl/handlers/FreezeHandler.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/utils/TestFixturesKeyLookup.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractDeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBySolidityIDHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemDeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractSystemUndeleteHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EtherumTransactionHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/AdapterUtils.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractDeleteHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractUpdateHandlerParityTest.java
Labels: Modularization

#4998 Remove CryptoCreate capability to create hollow accounts
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/config/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ledger/TransferLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/FeatureFlags.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/HapiSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Limechain, CI:UnitTests

#5445 05338 preconsensus event stream
  platform-sdk/docs/components/preconsensusEventStream.svg
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/formatting/StringFormattingUtils.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/exceptions/ClassNotFoundException.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/exceptions/InvalidVersionException.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/DebuggableMerkleDataInputStream.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/SerializableDataInputStream.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/CountUpLatch.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/LongRunningAverage.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/GossipEvent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventMultiFileIterator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventMutableFile.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventStreamConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventStreamSequencer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/EventImpl.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamMultiFileIteratorTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamRoundIteratorTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamSingleFileIteratorTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/ObjectStreamIteratorTest.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/AssertionUtils.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/com/swirlds/common/test/io/FileManipulation.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/formatting/StringFormattingUtilsTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/threading/CountUpLatchTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/utility/LongRunningAverageTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/com/swirlds/test/framework/config/TestConfigBuilder.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/com/swirlds/platform/test/event/IndexedEvent.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreConsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventReadWriteTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreconsensusEventStreamSequencerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java
Labels: CI:UnitTests, CI:FinalChecks

#5637 Fixes required to make mono-service compile.
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/accessors/SignedTxnAccessorTest.java
Labels: CI:UnitTests, CI:FinalChecks, Modularization

#5606 0.35 - Catch exceptions in prepareComputation
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/contracts/operations/HederaExceptionalHaltReason.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContract.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/HTSPrecompiledContractTest.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
  test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
  test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.bin
  test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.json
  test-clients/src/main/resource/contract/contracts/FactoryMirror/FactoryMirror.sol
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5612 Fix cryptoCreateWithAlias feature flag rename
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
Labels: Limechain, CI:UnitTests

#5652 Fix flaky test.
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileManagerTests.java
Labels: CI:FinalChecks

#5644 Improve transaction TPS of SignState test demo
  platform-sdk/platform-apps/tests/StatsSigningTestingTool/src/main/java/com/swirlds/demo/stats/signing/StatsSigningTestingToolMain.java
Labels: CI:UnitTests, CI:FinalChecks

#5465 Fix local `TraceabilitySuite` configs
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  hedera-node/test-clients/src/main/resource/spec-default.properties
Labels: Test Development, Limechain, CI:UnitTests

#5485 Fix no active payer exception in `ContractCallLocal`
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_30Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/ContractsV_0_34Module.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallCodeOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperation.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV034.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaOperationUtil.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperation.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaCallOperationV034Test.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaOperationUtilTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaStaticCallOperationTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
Labels: Bug, Limechain, CI:UnitTests

#5010 Populate EVM Address in CryptoTranscation
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/AbstractAutoCreationLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/AutoCreationLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
Labels: Limechain, CI:UnitTests

#5093 PropertyFileConfigSource supports custom ordinal
  platform-sdk/settings.gradle.kts
  platform-sdk/swirlds-common/build.gradle.kts
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/sources/PropertyFileConfigSource.java
  platform-sdk/swirlds-common/src/main/java/module-info.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/config/sources/PropertyFileConfigSourceTest.java
  platform-sdk/swirlds-common/src/test/resources/com/swirlds/common/config/sources/config1.properties
  platform-sdk/swirlds-common/src/test/resources/com/swirlds/common/config/sources/config2.properties
  platform-sdk/swirlds-common/src/test/resources/com/swirlds/common/config/sources/config3.properties
Labels: CI:UnitTests, CI:FinalChecks

#5481 NonNull & Nullable annotations can be used in all platform modules
  documentation/null-handling/README.md
  platform-sdk/swirlds-cli/build.gradle.kts
  platform-sdk/swirlds-cli/src/main/java/module-info.java
  platform-sdk/swirlds-common/build.gradle.kts
  platform-sdk/swirlds-config-api/build.gradle.kts
  platform-sdk/swirlds-config-api/src/main/java/module-info.java
  platform-sdk/swirlds-config-benchmark/build.gradle.kts
  platform-sdk/swirlds-config-impl/build.gradle.kts
  platform-sdk/swirlds-config-impl/src/main/java/module-info.java
  platform-sdk/swirlds-fchashmap/build.gradle.kts
  platform-sdk/swirlds-fchashmap/src/main/java/module-info.java
  platform-sdk/swirlds-fcqueue/build.gradle.kts
  platform-sdk/swirlds-fcqueue/src/main/java/module-info.java
  platform-sdk/swirlds-jasperdb/build.gradle.kts
  platform-sdk/swirlds-jasperdb/src/main/java/module-info.java
  platform-sdk/swirlds-logging/build.gradle.kts
  platform-sdk/swirlds-logging/src/main/java/module-info.java
  platform-sdk/swirlds-merkle/build.gradle.kts
  platform-sdk/swirlds-merkle/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/build.gradle.kts
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/build.gradle.kts
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/module-info.java
  platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/build.gradle.kts
  platform-sdk/swirlds-unit-tests/common/swirlds-test-framework/src/main/java/module-info.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/build.gradle.kts
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/main/java/module-info.java
  platform-sdk/swirlds-unit-tests/structures/swirlds-merkle-test/build.gradle.kts
  platform-sdk/swirlds-virtualmap/build.gradle.kts
  platform-sdk/swirlds-virtualmap/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FinalChecks

#5653 Improve transaction submitter to avoid a sudden surge
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/PlatformTestingToolMain.java
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/platform/TransactionSubmitter.java
Labels: CI:UnitTests, CI:FinalChecks

#5092 Optimized disk usage for LongListOffHeap and LongListDisk implementations
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/KeyValueStoreBench.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/AbstractLongList.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/LongList.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/LongListDisk.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/LongListHeap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/collections/LongListOffHeap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/MemoryIndexDiskKeyValueStore.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/utilities/MerkleDbFileUtils.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceMetricsTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/AbstractLongListTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/LongListDiskTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/LongListHeapTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/LongListMinValidIndexTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/LongListOffHeapTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/collections/LongListTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/MemoryIndexDiskKeyValueStoreMergeHammerTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/MemoryIndexDiskKeyValueStoreTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/utilities/MerkleDBFileUtilsTest.java
  platform-sdk/swirlds-jasperdb/src/test/resources/test_data/LongListOffHeapHalfEmpty_10k_10pc_v1.ll
  platform-sdk/swirlds-jasperdb/src/test/resources/test_data/LongListOffHeap_unsupported_version.ll
Labels: Java, Improvement, CI:UnitTests, Performance, CI:FinalChecks

#5666 5665: Add a metric for open file descriptors to platform benchmarks
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkMetrics.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/CryptoBenchMerkleDb.java
Labels: CI:UnitTests, CI:FinalChecks

#5674 5533: File descriptor leak from Files.list() v.2
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/streams/MerkleDataOutputStream.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/utility/FileUtils.java
Labels: CI:FinalChecks

#5690 5688 - Removed curly braces and returns when there is just one statement in the lambda
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/AccountDetailsAsserts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransferListAsserts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/fees/FeeCalculator.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/persistence/Contract.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/persistence/File.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicDelete.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/consensus/HapiTopicUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractDelete.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/crypto/HapiCryptoDeleteAllowance.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/file/HapiFileDelete.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/network/HapiUncheckedSubmit.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/schedule/HapiScheduleDelete.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenDelete.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenPause.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUnpause.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/fees/CongestionPricingSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/PermissionSemanticsSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/negative/CreateFailuresSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/positive/SysDelSysUndelSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/issues/Issue1765Suite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/KeyExport.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/crypto/CryptoTransferLoadTestWithInvalidAccounts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/file/FileExpansionLoadProvider.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/perf/token/UniqueTokenStateSetup.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/ValidateCongestionPricingAfterReconnect.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#4990 [HIP-583] Finalize hollow accounts via any signature in the sig map
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JHollowKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/legacy/core/jproto/JWildcardECDSAKey.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/Expansion.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/ExpansionHelper.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/HederaToPlatformSigOps.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/HollowScreening.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/PlatformSigOps.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/Rationalization.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookup.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigReqsManager.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/sourcing/PojoSigMap.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/sourcing/PojoSigMapPubKeyToSigBytes.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/sourcing/PubKeyToSigBytes.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/utils/MiscCryptoUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/verification/PrecheckVerifier.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/SigsAndPayerKeyScreen.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/logic/TopLevelTransition.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/HollowAccountFinalizationLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/PendingCompletion.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/RationalizedSigMeta.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/accessors/PlatformTxnAccessor.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/accessors/SwirldsTxnAccessor.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/legacy/core/jproto/JKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/legacy/core/jproto/JWildcardECDSAKeyTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/ExpandHandleHollowScreeningTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/ExpansionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/HederaToPlatformSigOpsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/PlatformSigOpsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/RationalizationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/SigOpsRegressionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/metadata/StateChildrenSigMetadataLookupTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigReqsManagerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/sourcing/PojoSigMapPubKeyToSigBytesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/utils/MiscCryptoUtilsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/verification/PrecheckVerifierTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/SigsAndPayerKeyScreenTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/state/logic/TopLevelTransitionTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/HollowAccountFinalizationLogicTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/RationalizedSigMetaTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/accessors/PlatformTxnAccessorTest.java
  hedera-node/test-clients/src/itest/java/ConcurrentSuites.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java
Labels: Limechain, CI:UnitTests

#5645 Remove CryptoCreate with key alias
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: Limechain, CI:UnitTests

#5483 swirlds-base module created
  platform-sdk/settings.gradle.kts
  platform-sdk/swirlds-base/build.gradle.kts
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/ArgumentUtils.java
  platform-sdk/swirlds-base/src/main/java/module-info.java
  platform-sdk/swirlds-base/src/test/java/com/swirlds/base/ArgumentUtilsTest.java
  platform-sdk/swirlds-common/build.gradle.kts
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/utility/CommonUtils.java
  platform-sdk/swirlds-common/src/main/java/module-info.java
Labels: CI:UnitTests, CI:FinalChecks

#5669 5664 - serialize / deserialize AddressBook to text compatible with config.txt
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookUtils.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java
Labels: CI:UnitTests, CI:FinalChecks

#5672 Smart Contracts PBJ Round 2
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/ContractServiceImpl.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallLocalHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBySolidityIDHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetBytecodeHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetInfoHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractGetRecordsHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractUpdateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCallHandlerTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractHandlerTestBase.java
Labels: Modularization

#5699 chore: update Platform SDK code owners
  .github/CODEOWNERS
Labels: CI:FinalChecks

#5565 05561 wiki 2
  platform-sdk/docs/base/configuration/config-modules.svg
  platform-sdk/docs/base/configuration/configuration.md
  platform-sdk/docs/configuration/config-modules.svg
  platform-sdk/docs/core/components/components.drawio.svg
  platform-sdk/docs/core/components/components.html
  platform-sdk/docs/mindmap-node.html
  platform-sdk/docs/platformWiki.md
Labels: CI:FinalChecks

#5707 Add better startup and shutdown logs.
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
Labels: CI:FinalChecks

#5726 Add new metric for consensus time.
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/metrics/MetricConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ConsensusHandlingMetrics.java
Labels: CI:FinalChecks

#4375 Enable all EVM E2E suites to run with Ethereum Calls
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCallTransitionLogicTest.java
  hedera-node/test-clients/src/eet/java/EndToEndTests.java
  hedera-node/test-clients/src/itest/java/AllIntegrationTests.java
  hedera-node/test-clients/src/itest/java/ConcurrentSuites.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DeleteTokenPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
Labels: Limechain, CI:UnitTests

#5048 Change the long zero address encoding algorithm
  hedera-node/hedera-evm/src/main/java/com/hedera/node/app/service/evm/accounts/HederaEvmContractAliases.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/contracts/sources/AddressKeyedMapFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/submerkle/EntityId.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EntityIdUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/EntityNum.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/primitives/StateViewTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/operation/HederaSelfDestructOperationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/contracts/sources/AddressKeyedMapFactoryTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/queries/crypto/GetAccountInfoAnswerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/queries/meta/GetAccountDetailsAnswerTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC721PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/EntityIdUtilsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/EntityNumTest.java
Labels: Limechain, CI:UnitTests

#5741 05190 Made VirtualRecord sealed
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualRecord.java
Labels: Java, CI:UnitTests, Tech Debt Reduced, CI:FinalChecks

#5729 `hedera-app` Part 2
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoFeeAccumulator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/fees/MonoGetTopicInfoUsage.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/grpc/MethodBase.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflowModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/MonoExpiryValidator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/SubmissionManager.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/onset/WorkflowOnset.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowModule.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryChecker.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/query/QueryWorkflowImpl.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/MonoFeeAccumulatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/fees/MonoGetTopicInfoUsageTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/QueryMethodTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/grpc/TransactionMethodTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/signature/MonoSignaturePreparerTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/MerkleTestBase.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcherTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoFeeCalculatorTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/AdaptedMonoProcessLogicTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestWorkflowImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/onset/WorkflowOnsetTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/query/QueryWorkflowImplTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/serdes/MonoSchedulingStateAdapterCodec.java
Labels: Modularization

#5648 5475 - Initialize Address Book On Startup
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/SwirldState.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBookValidator.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
Labels: CI:UnitTests

#5735 05649 add cron tasks
  .github/workflows/node-flow-fsts-daily-interval-01.yaml
  .github/workflows/node-flow-fsts-daily-interval-02.yaml
  .github/workflows/node-flow-fsts-daily-interval-03.yaml
  .github/workflows/node-flow-fsts-daily-interval-04.yaml
  .github/workflows/node-flow-fsts-daily-interval-05.yaml
  .github/workflows/node-flow-fsts-daily-regression.yaml
Labels: CI:UnitTests, CI:FinalChecks

#5749 05737-Address-Book-Update-Stake-Method
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/AddressBook.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/AddressBookTests.java
Labels: CI:UnitTests

#5634 State metadata file
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/ConsensusWrapper.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/consensus/RoundCalculationUtils.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/ConsensusRound.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/recovery/EventRecoveryWorkflow.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformData.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/editor/StateEditorSave.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateInfo.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadata.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SavedStateMetadataField.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SigSet.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedState.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileWriter.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateLoaderTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SavedStateMetadataTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/consensus/RoundCalculationUtilsTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/recovery/EventStreamRoundIteratorTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/state/RandomSignedStateGenerator.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/linking/OrphanBufferingLinkerTest.java
Labels: CI:FinalChecks

#5759 Add more info on incorrect child records
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/Expansion.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/HollowScreening.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/Rationalization.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/HollowAccountFinalizationLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/ExpandHandleHollowScreeningTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/RationalizationTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/HollowAccountFinalizationLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5728 5717: Improve VirtualNodeCache.merge
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/VirtualNodeCache.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapTests.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/cache/ConcurrentArrayTest.java
Labels: Performance, CI:FinalChecks

#5731 expand diagram
  platform-sdk/docs/threads/eventflow-threads.drawio.svg
  platform-sdk/docs/threads/eventflow-threads.html
Labels: CI:FinalChecks

#5794 5793: ConcurrentArray.merge() may fail to correctly compute the resulting size
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/cache/ConcurrentArray.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/cache/ConcurrentArrayTest.java
Labels: CI:FinalChecks

#5640 Validate all TransactionBody's have an oneof set
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonUtils.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/exception/UnknownHederaFunctionality.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/CommonUtilsTest.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/onset/WorkflowOnset.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/domain/security/PermissionFileUtils.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigRequirements.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/merkle/MerkleSchedule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/state/virtual/schedule/ScheduleVirtualValue.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/throttling/DeterministicThrottling.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/MiscUtils.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/PrngSystemPrecompiledContractTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/MiscUtilsTest.java
  hedera-node/hedera-schedule-service-impl/build.gradle.kts
  hedera-node/hedera-schedule-service-impl/src/main/java/com/hedera/node/app/service/schedule/impl/handlers/AbstractScheduleHandler.java
  hedera-node/hedera-schedule-service-impl/src/main/java/module-info.java
  hedera-node/test-clients/src/itest/java/AllIntegrationTests.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/TransactionBodyValidator.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/utils/TransactionBodyClassifier.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/records/TransactionBodyValidation.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5807 Remove workflow parameter
  .github/workflows/zxc-jrs-regression.yaml
Labels: CI:UnitTests, CI:FinalChecks

#5780 Add top level cron job to launch nightly regression
  .github/workflows/node-zxcron-develop-fsts-regression.yaml
Labels: CI:UnitTests, CI:FinalChecks

#5693 5636: MerkleDb may throw IllegalStateException when taking a snapshot after reconnect
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/ServicesState.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/ServicesStateTest.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/jasperdb/JasperDbBuilder.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDb.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSourceBuilder.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbTableConfig.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbBuilderTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/TestType.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilder.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilderJPDB.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/BrokenBuilderMerkleDb.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/datasource/VirtualDataSourceBuilder.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/datasource/InMemoryBuilder.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java
Labels: CI:UnitTests, Platform Virtual Map

#5774 5571: NativeThreadSet overhead in DataFileReader on highly concurrent reads
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/DataFileReaderHammerTest.java
Labels: CI:UnitTests, Performance, CI:FinalChecks

#5784 Sync Permits
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/SyncPermit.java
  platform-sdk/swirlds-common/src/test/java/com/swirlds/common/threading/SyncPermitTest.java
Labels: CI:FinalChecks

#5821 Include `ownerId` in synthetic child `ApproveAllowance` txn
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactory.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/ApprovePrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/ERC20PrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/SyntheticTxnFactoryTest.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5011 `CryptoCeate` with an evm address alias derived from any key
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/sigs/order/SigRequirements.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/validators/CryptoCreateChecks.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/sigs/order/SigRequirementsTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoCreateTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/scenarios/CryptoCreateScenarios.java
  hedera-node/hedera-mono-service/src/testFixtures/java/com/hedera/test/factories/txns/CryptoCreateFactory.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
Labels: Limechain, CI:UnitTests

#5025 Enable CryptoCreate with alias
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Limechain, CI:UnitTests

#5744 5314: JasperDB to MerkleDb: logs and settings
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/configuration/dev/log4j2.xml
  hedera-node/configuration/dev/settings.txt
  hedera-node/configuration/mainnet/log4j2.xml
  hedera-node/configuration/mainnet/settings.txt
  hedera-node/configuration/preprod/log4j2.xml
  hedera-node/configuration/preprod/settings.txt
  hedera-node/configuration/previewnet/log4j2.xml
  hedera-node/configuration/previewnet/settings.txt
  hedera-node/configuration/testnet/log4j2.xml
  hedera-node/configuration/testnet/settings.txt
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/contracts/SizeLimitedStorageBench.java
  hedera-node/hedera-mono-service/src/jmh/java/com/hedera/node/app/service/mono/setup/Constructables.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
Labels: CI:UnitTests

#5859 Smart contract service review
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/ContractCreateHandlerParityTest.java
Labels: Modularization

#5791 05738 - deletes old saved address books
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/config/AddressBookConfig.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/AddressBookInitializerTest.java
Labels: CI:FinalChecks

#5877 Update protobufs to v0.36.0 tag
  settings.gradle.kts
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5885 Update protobufs to v0.36.1 tag
  settings.gradle.kts
Labels: CI:FinalChecks

#5870 5869: Faster bucket index updates in HalfDiskHashMap
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java
Labels: CI:UnitTests, Performance, CI:FinalChecks, Platform Data Structures

#5886 Update hedera protobuf java api to v0.36.1
  settings.gradle.kts
Labels: CI:FinalChecks

#5785 05584 - AddressBookTestingTool app created
  platform-sdk/platform-apps/tests/AddressBookTestingTool/README.md
  platform-sdk/platform-apps/tests/AddressBookTestingTool/build.gradle.kts
  platform-sdk/platform-apps/tests/AddressBookTestingTool/gradle.properties
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolMain.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/AddressBookTestingToolState.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/com/swirlds/demo/addressbook/TransactionGenerator.java
  platform-sdk/platform-apps/tests/AddressBookTestingTool/src/main/java/module-info.java
  platform-sdk/sdk/config.txt
  platform-sdk/settings.gradle.kts
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/system/address/Address.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/AddressBookInitializer.java
Labels: CI:FinalChecks

#5858 05757 event stream signing PCLI
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/EventStreamSignCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/cli/SignCommand.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/util/EventStreamSigningUtils.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/util/EventStreamSigningUtilsTests.java
Labels: CI:FinalChecks

#5892 Fix for IngestCheckerTest
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/ingest/IngestCheckerTest.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
Labels: Modularization

#5888 Update hedera protobufs, java api to v0.36.1
  settings.gradle.kts
Labels: CI:FinalChecks

#5705 Copy latest `bootstrap.properties` from main `hedera-node/hedera-mono-service`
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: CI:FinalChecks

#5896 05895 - fixing startup crash due to new SwirldMain configuration
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
Labels: CI:FinalChecks

#5633 Write preconsensus event stream
  platform-sdk/docs/threads/eventflow-threads.drawio.svg
  platform-sdk/docs/threads/eventflow-threads.html
  platform-sdk/sdk/settings.txt
  platform-sdk/swirlds-base/src/main/java/com/swirlds/base/functions/ThrowingConsumer.java
  platform-sdk/swirlds-base/src/main/java/module-info.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/config/StateConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/io/config/TemporaryFileConfig.java
  platform-sdk/swirlds-common/src/main/java/com/swirlds/common/threading/interrupt/Uninterruptable.java
  platform-sdk/swirlds-platform-core/build.gradle.kts
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/Browser.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/PlatformConstructor.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/SwirldsPlatform.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/ConsensusWrapper.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/EventIntake.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponent.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/DefaultStateManagementComponentFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/StateManagementComponentFactory.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/state/output/MinimumGenerationNonAncientConsumer.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/components/wiring/ManualWiring.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/AsyncPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/NoOpPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreConsensusEventStreamConfig.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/PreconsensusEventMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/event/preconsensus/SyncPreConsensusEventWriter.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/eventhandling/ConsensusRoundHandler.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/internal/ConsensusRound.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/metrics/ConsensusHandlingMetrics.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/observers/EventObserverDispatcher.java
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/signed/SignedStateFileManager.java
  platform-sdk/swirlds-platform-core/src/main/java/module-info.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/ConsensusRoundTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileManagerTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/SignedStateFileReadWriteTest.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/components/state/StateManagementComponentTests.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/eventhandling/ConsensusRoundHandlerTests.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/build.gradle.kts
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/main/java/module-info.java
  platform-sdk/swirlds-unit-tests/common/swirlds-common-test/src/test/java/com/swirlds/common/test/utility/UninterruptableTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/chatter/ChatterNotifierTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/EventObserverDispatcherTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/components/TransactionHandlingTestUtils.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/intake/OrphanEventsIntakeTest.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/AsyncPreConsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/PreConsensusEventFileManagerTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/event/preconsensus/SyncPreConsensusEventWriterTests.java
  platform-sdk/swirlds-unit-tests/core/swirlds-platform-test/src/test/java/com/swirlds/platform/test/eventflow/EventFlowTests.java
  platform-sdk/swirlds-virtualmap/build.gradle.kts
  platform-sdk/swirlds-virtualmap/src/main/java/module-info.java
Labels: CI:FinalChecks

#5904 03074 d stake workflow
  .github/workflows/node-flow-fsts-daily-interval-06.yaml
Labels: CI:UnitTests, CI:FinalChecks

#5884 Cherry pick - Use mirror address of selfdestruct-ed creation in record
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogic.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/contract/ContractCreateTransitionLogicTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/TransactionRecordAsserts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5882 cherry pick Fix AccountID's generated from missing EVM addresses
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacade.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/codec/DecodingFacadeTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java
Labels: CI:UnitTests, CI:FullStackTests, CI:FinalChecks

#5909 05908 Fixed DataFileWriter.finishWriting for Windows
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileWriter.java
Labels: CI:UnitTests, CI:FinalChecks
