Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2024-04, with the labels that each got.

#12168 test: security v2 model - add test for token associate with callcode
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileV2SecurityModelSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSV2SecurityModelSuite.java
Labels: Limechain

#11602 fix: enable HelloWorldEthereumSuite hapi tests
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/ingest/IngestChecker.java
  hedera-node/test-clients/record-snapshots/HelloWorldEthereum.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
Labels: Limechain

#12550 fix: tokenAssociate throws IndexOutOfBoundsException (#12453)
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
Labels: Limechain

#12553 fix: tokenDissociate can fail with NullPointerException
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenRelListCalculator.java
Labels: Limechain

#12540 chore: 12227 Moved HAPI to the project root level.
  build-logic/project-plugins/src/main/kotlin/com.hedera.hashgraph.spotless-java-conventions.gradle.kts
  hapi/build.gradle.kts
  hapi/src/main/java/module-info.java
  hapi/src/testFixtures/java/com/hedera/node/hapi/fixtures/TransactionHelper.java
  hapi/src/testFixtures/java/module-info.java
  settings.gradle.kts
Labels: Hedera GRPC API

#12557 chore: cherry pick pause fix
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenPauseHandler.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
Labels: Limechain

#12596 fix: failing test due to typo for NegativeHtsTransferFrom contract
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
Labels: Limechain

#12695 fix: 12693: Enhance ReconnectBench to reconnect merkle trees with multiple virtual maps
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/ReconnectBench.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/reconnect/MerkleBenchmarkUtils.java
Labels: Performance, Platform Reconnect, Platform Virtual Map, Platform Data Structures

#12618 fix: 12609: Merkle synchronization tests take too long for no obvious reason [TEST_ONLY]
  platform-sdk/swirlds-merkle/build.gradle.kts
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/merkle/test/MerkleSynchronizationTests.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapLargeReconnectTest.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTest.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/VirtualMapReconnectTestBase.java
  platform-sdk/swirlds-virtualmap/src/jmh/java/com/swirlds/virtualmap/benchmark/reconnect/VirtualMapReconnectBenchBase.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/reconnect/VirtualMapReconnectTestBase.java
Labels: Test Development, Platform Reconnect, Platform Data Structures

#12493 test: Improvements to smart contract specs related to aliases
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/MismatchedSidecar.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/SidecarAwareHapiSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/EncodingUtils.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  hedera-node/test-clients/src/main/java/module-info.java
Labels: Limechain

#12753 perf: reduced warmup overhead #11915; warm treasury account for token transfer #12278
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableKVState.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/CacheWarmer.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/state/merkle/disk/OnDiskReadableStateTest.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
Labels: Performance

#12396 fix: remove admin key as defaultSigner for HapiTokenUpdate
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/GracePeriodRestrictionsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/autorenew/NoGprIfNoAutoRenewSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallV1SecurityModelSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/Create2OperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileV2SecurityModelSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSV1SecurityModelSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSV2SecurityModelSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSV2SecurityModelSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DelegatePrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DeleteTokenPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/misc/MemoValidation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/schedule/ScheduleSignSpecs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/Hip17UnhappyTokensSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenAssociationSpecs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenPauseSpecs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenTransactSpecs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
Labels: Limechain

#12713 feat: allow the deterministic deployment proxy contract transaction to succeed
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/ethereum/EthTxData.java
  hedera-node/hapi-utils/src/test/java/com/hedera/node/app/hapi/utils/ethereum/EthTxDataTest.java
  hedera-node/test-clients/record-snapshots/ContractCreate.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
Labels: Hedera Smart Contract Service

#12845 fix: 12311: HalfDiskHashMap: Unknown bucket field 2
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/DataFileReader.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/Bucket.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/ParsedBucket.java
Labels: Platform Virtual Map, Platform Data Structures

#12393 chore: Add github actions for uploading junit test reports as artifacts
  .github/workflows/node-zxc-compile-application-code.yaml
Labels: Limechain

#12903 fix: 12901: Backport the fix for 11966 to release 0.49
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbTableConfig.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/config/MerkleDbConfig.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbTableConfigTest.java
Labels: Platform Virtual Map, Platform Data Structures

#12905 fix: Don't double-count child staking rewards in parent finalization
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
Labels: Modularization

#12793 feat: internal call against PRNG returns success instead of invalid fee submitted
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/PrngSystemContract.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/PrngSystemContractTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PrngPrecompileSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/PrngSystemContract/PrngSystemContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/PrngSystemContract/PrngSystemContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/PrngSystemContract/PrngSystemContract.sol
Labels: Limechain

#11643 fix: Transferring tokens with HTS precompile to system accounts between 0.0.350 and 0.0.361 returns INVALID_ALIAS_KEY
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/store/contracts/precompile/impl/TransferPrecompile.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/store/contracts/precompile/TransferPrecompilesTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/SystemAccountCreditScreen.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
Labels: Bug, Limechain

#12769 test: add additional tests for custom fees with hollow account collector
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoCreateUtils.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/HollowAccountFinalizationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFixedFees.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomFractionalFees.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/TransferWithCustomRoyaltyFees.java
Labels: Limechain

#12832 fix: contractCalls to etheretumContractCalls NPE
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/CustomSpecAssert.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilStateChange.java
Labels: Bug, Limechain

#12328 docs: Add documentation for the differences in the operations with system accounts
  hedera-node/docs/system-accounts-operations.md
Labels: Limechain

#12678 test: Improvements to assertions on sidecar files
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/matchers/FieldByFieldMatcher.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/matchers/GasMatcher.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/matchers/MatcherUtils.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/matchers/TransactionSidecarRecordMatcher.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/ExpectedSidecar.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/MismatchedSidecar.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/verification/traceability/SidecarWatcher.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/SidecarAwareHapiSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  hedera-node/test-clients/src/main/java/module-info.java
Labels: Limechain

#12965 fix: Cherry Pick of #12905 (double-count child staking rewards)
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/staking/StakingRewardsHandlerImpl.java
Labels: Modularization

#12123 test: Add Completed Hollow Account fuzzy tests
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/OpProvider.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/consensus/RandomTopicCreation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/consensus/RandomTopicDeletion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/consensus/RandomTopicUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/contract/RandomCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/contract/RandomCallLocal.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/contract/RandomContract.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/contract/RandomContractDeletion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/RandomAccount.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/RandomAccountDeletion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/RandomAccountUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/RandomTransfer.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/RandomTransferFromSigner.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/crypto/RandomTransferToSigner.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/files/RandomFileDeletion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/files/RandomFileUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomTokenAssociationHollowAccount.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/hollow/RandomTokenHollowAccount.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/schedule/RandomSchedule.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/schedule/RandomScheduleDeletion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/schedule/RandomScheduleSign.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomToken.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenAccountWipe.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenAssociation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenBurn.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenDeletion.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenDissociation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenFreeze.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenKycGrant.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenKycRevoke.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenMint.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenTransfer.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenUnfreeze.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenUpdate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/CompletedHollowAccountOperationsFuzzing.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/UmbrellaRedux.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/HollowAccountCompletedFuzzingFactory.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/HollowAccountFuzzingFactory.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/regression/factories/RegressionProviderFactory.java
  hedera-node/test-clients/src/main/resource/eet-config/completed-hollow-account-fuzzing.properties
Labels: Test Development, Limechain

#12866 feat: Initial changes for handler flow for the new TokenReject functionality
  hapi/build.gradle.kts
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/services/ServiceScopeLookup.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionDispatcher.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/dispatcher/TransactionHandlers.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandlersInjectionModule.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/pbj/PbjConverter.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/TokenServiceInjectionModule.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenHandlers.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRejectHandler.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/TokenServiceDefinition.java
Labels: Limechain

#12593 test: add negative tests for transferNFT, transferNFTs, transferToken, transferTokens
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
Labels: Limechain

#12785 docs: add design document for HIP-904 maxAutoAssociations changes
  hedera-node/docs/design/services/token-service/airdrops/max-auto-associations-changes.md
Labels: Limechain, Design

#13005 perf: warm up more entities
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/RecordFinalizerBase.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
Labels: Performance
