Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2024-01, with the labels that each got.

#10760 chore: add "Possibly CATASTROPHIC failure" logs
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/prehandle/PreHandleWorkflowImpl.java
Labels: Limechain, Modularization

#10736 test: enable fuzzy matching for some suites
  hedera-node/test-clients/record-snapshots/ERC721ContractInteractions.json
  hedera-node/test-clients/record-snapshots/PushZeroOperation.json
  hedera-node/test-clients/record-snapshots/StaticCallOperation.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PushZeroOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/StaticCallOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC721ContractInteractions.java
Labels: Limechain

#10703 feat: adding getter to RecordStreamEntry for TransactionRecord
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/utils/forensics/RecordStreamEntry.java
Labels: Limechain, Feature Enhancement

#10788 fix: Enable fuzzy matching in `SelfDestructSuite`
  hedera-node/test-clients/record-snapshots/SelfDestruct.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SelfDestructSuite.java
Labels: Limechain

#10792 feat: Enable fuzzy matching in `ContractHTSSuite`
  hedera-node/test-clients/record-snapshots/ContractHTS.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
Labels: Limechain

#10768 fix: Enable fuzzy matching for `ERC20ContractInteractions`
  hedera-node/test-clients/record-snapshots/ERC20ContractInteractions.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC20ContractInteractions.java
Labels: Limechain

#10697 fix: Enable Smart Contract Records and Operations suites fuzzy matching
  hedera-node/test-clients/record-snapshots/BalanceOperation.json
  hedera-node/test-clients/record-snapshots/CallCodeOperation.json
  hedera-node/test-clients/record-snapshots/CallOperation.json
  hedera-node/test-clients/record-snapshots/Records.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/BalanceOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CallCodeOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CallOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/records/RecordsSuite.java
Labels: Limechain

#10699 fix: Enable fuzzy matching in PrngSeedOperationSuite
  hedera-node/test-clients/record-snapshots/PrngSeedOperation.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PrngSeedOperationSuite.java
Labels: Limechain

#10766 fix: Enable fuzzy matching for SStoreSuite
  hedera-node/test-clients/record-snapshots/SStore.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/SStoreSuite.java
Labels: Limechain

#10807 fix: Enable Fuzzy matching for some Smart Contract suites and BlockSuite
  hedera-node/test-clients/record-snapshots/Block.json
  hedera-node/test-clients/record-snapshots/ContractCall.json
  hedera-node/test-clients/record-snapshots/ContractCallLocal.json
  hedera-node/test-clients/record-snapshots/ContractGetInfo.json
  hedera-node/test-clients/record-snapshots/ContractUpdate.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/block/BlockSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetInfoSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
Labels: Limechain

#10857 test: enable GrantRemoveKycSuite fuzzy matching
  hedera-node/test-clients/record-snapshots/GrantRevokeKyc.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
Labels: Limechain

#10856 test: Fix fuzzy match flakiness
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetInfoSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/BalanceOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/ExtCodeHashOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PushZeroOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC721ContractInteractions.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/SigningReqsSuite.java
Labels: Limechain, Modularization

#10834 chore: update local node images to Java 21
  hedera-node/infrastructure/docker/containers/local-node/network-node-base/Dockerfile
Labels: Bug, Release

#10921 test: enable RedirectPrecompileSuite fuzzy matching
  hedera-node/test-clients/record-snapshots/RedirectPrecompile.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/PrngSeedOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/RedirectPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenCreateSpecs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenDeleteSpecs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenManagementSpecs.java
Labels: Limechain

#10868 fix: Enable fuzzy match in ContractBurnHTSSuite
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/HtsSystemContract.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/HtsCallAttempt.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/burn/BurnDecoder.java
  hedera-node/test-clients/record-snapshots/ContractBurnHTS.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSSuite.java
Labels: Limechain

#10850 test: Enable fuzzy record matching for PrngPrecompileSuite
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PrngPrecompileSuite.java
Labels: Limechain, Modularization

#10852 test: Enable fuzzy record matching for ERC1155ContractInteractions
  hedera-node/test-clients/record-snapshots/ERC1155ContractInteractions.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC1155ContractInteractions.java
Labels: Limechain, Modularization

#10806 test: enable ContractCreateSuite fuzzy matching
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/CallOutcome.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCallHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/ContractCreateHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/handlers/EthereumTransactionHandler.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/CallOutcomeTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/handlers/EthereumTransactionHandlerTest.java
  hedera-node/test-clients/record-snapshots/ContractCreate.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
Labels: Limechain

#10906 test: enable DefaultTokenStatusSuite fuzzy matching
  hedera-node/test-clients/record-snapshots/DefaultTokenStatus.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DefaultTokenStatusSuite.java
Labels: Limechain

#10866 test: enable AssociatePrecompileSuite fuzzy matching
  hedera-node/test-clients/record-snapshots/AssociatePrecompile.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AssociatePrecompileSuite.java
Labels: Limechain

#10943 test: enable EthereumSuite fuzzy matching
  hedera-node/test-clients/record-snapshots/Ethereum.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
Labels: Limechain

#10873 fix: Enable fuzzy matching for DelegatePrecompile
  hedera-node/test-clients/record-snapshots/DelegatePrecompile.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DelegatePrecompileSuite.java
Labels: Limechain

#10867 test: Enable fuzzy record matching for FreezeUnfreezeTokenPrecompileSuite
  hedera-node/test-clients/record-snapshots/FreezeUnfreezeTokenPrecompile.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java
Labels: Limechain, Modularization

#10861 test: enable TokenExpiryInfoSuite fuzzy matching
  hedera-node/test-clients/record-snapshots/TokenExpiryInfo.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenExpiryInfoSuite.java
Labels: Limechain

#10839 test: Enable fuzzy match for all CreatePrecompileSuite tests
  hedera-node/test-clients/record-snapshots/CreatePrecompile.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
Labels: Limechain, Modularization

#10840 test: Add tests for V2 token mint for EOA-CONTRACT-PRECOMPILE
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSV2SecurityModelSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/V1SecurityModelOverrides.java
  hedera-node/test-clients/src/main/resource/contract/contracts/MintContract/MintContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/MintContract/MintContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/MixedMintToken/MixedMintToken.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/MixedMintToken/MixedMintToken.json
  hedera-node/test-clients/src/main/resource/contract/contracts/MixedMintToken/MixedMintToken.sol
Labels: Limechain

#10940 fix: Reclaim throttle usage for auto account creation
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/workflows/HandleContext.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/throttle/SynchronizedThrottleAccumulator.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleContextImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/HandleWorkflow.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleContextImplTest.java
  hedera-node/hedera-app/src/test/java/com/hedera/node/app/workflows/handle/HandleWorkflowTest.java
  hedera-node/hedera-app/src/xtest/java/common/BaseScaffoldingModule.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/transfer/TransferContextImpl.java
Labels: Limechain, Modularization

#11037 fix: Enable fuzzy matching for TraceabilitySuite
  hedera-node/test-clients/record-snapshots/Traceability.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
Labels: Limechain

#11014 test: enable fuzzy match on TokenInfoHTSSuite
  hedera-node/test-clients/record-snapshots/TokenInfoHTS.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
Labels: Limechain, Modularization

#10701 feat: unlink alias on account deletion
  hedera-node/configuration/dev/bootstrap.properties
  hedera-node/data/config/bootstrap.properties
  hedera-node/hedera-app/src/test/resources/bootstrap.properties
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/AccountsConfig.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/BootstrapProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicProperties.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/context/properties/PropertyNames.java
  hedera-node/hedera-mono-service/src/main/java/com/hedera/node/app/service/mono/txns/crypto/CryptoDeleteTransitionLogic.java
  hedera-node/hedera-mono-service/src/main/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/BootstrapPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/context/properties/GlobalDynamicPropertiesTest.java
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/txns/crypto/CryptoDeleteTransitionLogicTest.java
  hedera-node/hedera-mono-service/src/test/resources/bootstrap.properties
  hedera-node/hedera-mono-service/src/test/resources/bootstrap/standard.properties
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoDeleteHandler.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyCryptoTestsSuite.java
  hedera-node/test-clients/src/main/resource/bootstrap.properties
Labels: Limechain

#11001 feat: 10961: Virtual hashing is the next bottleneck
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/config/VirtualMapConfig.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/Path.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/ArrayHashingQueue.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/CompoundHashingQueue.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/HashJob.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/HashingQueue.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/PeekIterator.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHashListener.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/AbstractHashListener.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/VirtualMapHashingTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/PathTests.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/hash/ArrayHashingQueueTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/hash/CompoundHashingQueueTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/hash/HashingQueueTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/hash/PeekIteratorTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/hash/VirtualHasherTest.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/hash/VirtualHasherTestBase.java
Labels: Performance, Platform Virtual Map, Platform Data Structures

#11184 test: 11135 - create hapi tests for balance operation for system accounts
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/BalanceChecker46Version/BalanceChecker46Version.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/BalanceChecker46Version/BalanceChecker46Version.json
  hedera-node/test-clients/src/main/resource/contract/contracts/BalanceChecker46Version/BalanceChecker46Version.sol
Labels: Test Development, Limechain

#11183 fix: 10315 use ordinal when revert PrecompileContractResult (ERCPrecompileSuite fuzzy match)
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/FullResult.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/TestHelpers.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/create/ClassicCreatesCallTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc20TransfersCallTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/Erc721TransferFromCallTest.java
  hedera-node/test-clients/record-snapshots/ERCPrecompile.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
Labels: Limechain

#10735 test: add additional test for conditional records
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/openzeppelin/ERC20ContractInteractions.java
Labels: Limechain

#11163 test: add `htsTransferFromForNFTViaContractCreateLazyCreate` to `LazyCreateThroughPrecompileSuite` and enable fuzzy-matching on it
  hedera-node/test-clients/record-snapshots/LeakyContractTests.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/leaky/LeakyContractTestsSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/NestedLazyCreateViaConstructor/NestedLazyCreateViaConstructor.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/NestedLazyCreateViaConstructor/NestedLazyCreateViaConstructor.json
  hedera-node/test-clients/src/main/resource/contract/contracts/NestedLazyCreateViaConstructor/NestedLazyCreateViaConstructor.sol
Labels: Limechain

#11185 fix: 10315 Add ALLOW_EMPTY_ERROR_MSG snapshot mode (ERCPrecompileSuite fuzzy match)
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomMessageCallProcessor.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotMatchMode.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/AutoAccountCreationSuite.java
Labels: Limechain

#11239 test: unlinking of alias is not working as expected
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoCreateSuite.java
Labels: Limechain

#11181 fix: Fuzzy match AtomicCryptoTransferSuite
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersDecoder.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersTranslator.java
  hedera-node/test-clients/record-snapshots/AtomicCryptoTransferHTS.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/AtomicCryptoTransferHTSSuite.java
Labels: Limechain

#11179 fix: 10315 fix leftovers (ERCPrecompileSuite fuzzy match)
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/setapproval/SetApprovalForAllCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/Erc721TransferFromCall.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/setapproval/SetApprovalForAllCallTest.java
Labels: Limechain

#11178 fix: 10315 add logs to grant approval calls (ERCPrecompileSuite fuzzy match)
  hedera-node/hedera-mono-service/src/test/java/com/hedera/node/app/service/mono/utils/MiscUtilsTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/AbstractGrantApprovalCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/GrantApprovalLoggingUtils.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/grantapproval/GrantApprovalTranslator.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ApprovalSwitchHelper.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/transfer/ClassicTransfersCall.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/grantapproval/ClassicGrantApprovalCallTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/grantapproval/ERCGrantApprovalCallTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ApprovalSwitchHelperTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/transfer/ClassicTransfersCallTest.java
  hedera-node/test-clients/record-snapshots/ERCPrecompile.json
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
Labels: Limechain
