Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2024-07, with the labels that each got.

#14053 feat: HIP-904: Add `TokenCancelAirdrop` transaction verb for `test-clients`
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/junit/hedera/utils/GrpcUtils.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnFactory.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/token/HapiTokenCancelAirdrop.java
Labels: Limechain

#13730 docs: 13690 Added a design doc for `Ledger State API`
  platform-sdk/docs/proposals/001-ledger-state-api/001-ledger-state-api.md
Labels: Design, Platform

#14061 docs: update token reject design doc
  hedera-node/docs/design/services/token-service/airdrops/token-reject.md
Labels: Limechain

#13566 feat: Implement pending state for airdrop purposes
  hapi/build.gradle.kts
  hapi/src/main/java/com/hedera/hapi/util/HapiUtils.java
  hedera-node/hapi-utils/src/main/java/com/hedera/node/app/hapi/utils/CommonPbjConverters.java
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/metrics/StoreMetricsService.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/metrics/StoreMetricsServiceImpl.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/ReadableStoreFactory.java
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/store/WritableStoreFactory.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ApiPermissionConfig.java
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/TokensConfig.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/ReadableAirdropStoreImpl.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/WritableAirdropStore.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/schemas/V0500TokenSchema.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/ReadableAirdropStoreImplTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/WritableAirdropStoreTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/StateBuilderUtil.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/schemas/V0500TokenSchemaTest.java
  hedera-node/hedera-token-service/src/main/java/com/hedera/node/app/service/token/ReadableAirdropStore.java
Labels: Limechain

#14036 test: HIP-904 Create HAPI tests for a hollow account on an alias on which we have a deleted account
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
Labels: Limechain

#14119 ci: cherry pick fix to lower tps for reconnect tests
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/reconnect/CreateFilesBeforeReconnect.java
Labels: Bug

#14078 chore: remove unneeded code
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenHandlerHelper.java
Labels: Limechain

#14154 chore: Update codeowners for smart contracts contributors
  .github/CODEOWNERS
Labels: Improvement, Hedera Smart Contract Service

#11490 test: 11138 - Create hapi tests for transfer and send operations for system accounts Part 2
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/assertions/ContractFnResultAsserts.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CryptoTransferHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/crypto/CryptoTransferSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/CryptoTransfer/CryptoTransfer.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/CryptoTransfer/CryptoTransfer.json
Labels: Test Development, Limechain

#13686 test: Add hapi tests for call operations on system accounts
  hedera-node/docs/system-accounts-operations.md
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/CallOperationsCheckerSuccess/CallOperationsCheckerSuccess.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/CallOperationsCheckerSuccess/CallOperationsCheckerSuccess.json
  hedera-node/test-clients/src/main/resource/contract/contracts/CallOperationsCheckerSuccess/CallOperationsCheckerSuccess.sol
Labels: Test Development, Limechain

#14088 feat: Create tool for reading block files
  hapi/build.gradle.kts
  hedera-node/cli-clients/build.gradle.kts
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/block/BlockCommand.java
  hedera-node/cli-clients/src/main/java/com/hedera/services/cli/block/BlockRead.java
  hedera-node/cli-clients/src/test/java/com/hedera/services/cli/block/test/BlockReadTest.java
  hedera-node/cli-clients/src/test/resources/com/hedera/services/cli/block/test/rsc/1.blk.gz
  hedera-node/cli-clients/src/test/resources/com/hedera/services/cli/block/test/rsc/block-2-compressed/2.blk.gz
  hedera-node/cli-clients/src/test/resources/com/hedera/services/cli/block/test/rsc/block-2-uncompressed/2.blk
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/records/impl/producers/formats/v1/BlockStreamFormatV1.java
Labels: Block Streams

#14216 chore: File Service compiler warning fixes
  hedera-node/hedera-file-service-impl/build.gradle.kts
  hedera-node/hedera-file-service-impl/src/main/java/module-info.java
  hedera-node/hedera-file-service/build.gradle.kts
Labels: HapiThursday

#14263 chore: updated perf nightly workflow
  .github/workflows/flow-node-performance-tests.yaml
Labels: Completed

#14290 ci: stop release 0.51 regression
  .github/workflows/node-zxcron-release-fsts-regression.yaml
  .github/workflows/platform-zxcron-release-jrs-regression.yaml
Labels: github_actions

#14332 fix: 14230 Fixed incorrect deserialization of `PlatformState`
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java
Labels: Bug

#14323 fix: 14309: Drop KeyIndexType.SEQUENTIAL_INCREMENTING_LONGS support
  platform-sdk/platform-apps/tests/PlatformTestingTool/src/main/java/com/swirlds/demo/virtualmerkle/map/smartcontracts/bytecode/SmartContractByteCodeMapKey.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BaseBench.java
  platform-sdk/swirlds-benchmarks/src/jmh/java/com/swirlds/benchmark/BenchmarkKey.java
  platform-sdk/swirlds-jasperdb/src/hammer/java/com/swirlds/merkledb/files/CloseFlushTest.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbCompactionCoordinator.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbPaths.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatistics.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatisticsUpdater.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMap.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/serialize/KeyIndexType.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/serialize/KeySerializer.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/CompactionInterruptTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbCompactionCoordinatorTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceMetricsTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceSnapshotMergeTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbStatisticsTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/FilesTestType.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/VirtualLeafRecordSerializerTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/BucketTest.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/files/hashmap/HalfDiskHashMapTest.java
  platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/ExampleLongKeyFixedSize.java
  platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/ExampleLongKeyVariableSize.java
  platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/ExampleLongLongKeyFixedSize.java
  platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/ExampleLongLongKeyVariableSize.java
  platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/TestType.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestKey.java
  platform-sdk/swirlds-merkle/src/test/java/com/swirlds/virtual/merkle/TestKeySerializer.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/TestKey.java
  platform-sdk/swirlds-platform-core/src/test/java/com/swirlds/platform/reconnect/TestKeySerializer.java
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/VirtualLongKey.java
  platform-sdk/swirlds-virtualmap/src/testFixtures/java/com/swirlds/virtualmap/test/fixtures/TestKey.java
Labels: Tech Debt Reduced, Platform Virtual Map, Platform Data Structures, Platform

#14334 fix: 14230 platform state deserialization fix
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/state/PlatformState.java
Labels: Bug

#14348 chore: remove V052AddressBookSchema from release 0.52 branch
  hedera-node/hedera-addressbook-service-impl/build.gradle.kts
  hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/AddressBookServiceImpl.java
  hedera-node/hedera-addressbook-service-impl/src/main/java/com/hedera/node/app/service/addressbook/impl/schemas/V052AddressBookSchema.java
  hedera-node/hedera-addressbook-service-impl/src/main/java/module-info.java
  hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/AddressBookServiceImplTest.java
  hedera-node/hedera-addressbook-service-impl/src/test/java/com/hedera/node/app/service/addressbook/impl/test/schemas/V052AddressBookSchemaTest.java
Labels: Dynamic Address Book

#14412 feat: Add javadoc for networkadmin service
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/FreezeServiceImpl.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/NetworkAdminServiceInjectionModule.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/FreezeUpgradeActions.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkAdminHandlers.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/NetworkGetAccountDetailsHandler.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/handlers/ReadableFreezeUpgradeActions.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/package-info.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/schemas/V0490FreezeSchema.java
  hedera-node/hedera-network-admin-service-impl/src/main/java/com/hedera/node/app/service/networkadmin/impl/schemas/V0490NetworkSchema.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/FreezeService.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/FreezeServiceDefinition.java
  hedera-node/hedera-network-admin-service/src/main/java/com/hedera/node/app/service/networkadmin/NetworkServiceDefinition.java
Labels: HapiThursday

#14260 feat: HIP-1010 UpdateTokenCustomFees system contract implementation
  hedera-node/configuration/dev/application.properties
  hedera-node/configuration/preprod/application.properties
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/ContractsConfig.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/gas/DispatchType.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/HtsTranslatorsModule.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesDecoder.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesTranslator.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/module-info.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesDecoderTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/hts/updatetokencustomfees/UpdateTokenCustomFeesTranslatorTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/dsl/operations/transactions/AuthorizeContractOperation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/token/HapiGetTokenInfo.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/UpdateTokenFeeScheduleTest.java
  hedera-node/test-clients/src/main/resource/contract/contracts/UpdateTokenFeeSchedules/UpdateTokenFeeSchedules.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/UpdateTokenFeeSchedules/UpdateTokenFeeSchedules.json
  hedera-node/test-clients/src/main/resource/contract/contracts/UpdateTokenFeeSchedules/UpdateTokenFeeSchedules.sol
Labels: Limechain

#14413 fix(bug): Suppress warning in ConfigUtils
  .github/workflows/zxc-verify-gradle-build-determinism.yaml
  gradle/plugins/src/main/kotlin/com.hedera.gradle.java.gradle.kts
  hapi/build.gradle.kts
  platform-sdk/swirlds-logging/build.gradle.kts
  platform-sdk/swirlds-logging/src/jmh/java/com/swirlds/logging/benchmark/log4j2/Log4JRunner.java
Labels: github_actions

#14470 perf: VirtualHasher.hash() keeps too many tasks in memory
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/hash/VirtualHasher.java
Labels: Performance

#14469 ci: Add registry mirrors to daemon-config on crazy-max/ghaction-setup-docker
  .github/workflows/node-zxc-build-release-artifact.yaml
  .github/workflows/zxc-publish-production-image.yaml
  .github/workflows/zxc-verify-docker-build-determinism.yaml
Labels: github_actions

#14372 docs: Update glossary defns of aliases, triplets
  docs/glossary.md
Labels: Hedera Smart Contract Service
