Repository hiero-ledger/hiero-consensus-node, pull requests merged in 2024-05, with the labels that each got.

#12786 docs: add design document for HIP-904 token reject operation
  hedera-node/docs/design/services/token-service/airdrops/token-reject.md
Labels: Limechain, Design

#13097 fix: 12853: Memory leak from MerkleDbDataSource.copyStatisticsFrom()
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatisticsUpdater.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
  platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/TestType.java
Labels: Platform Virtual Map, Platform Data Structures

#12093 feat: Map HapiContractCreate to HapiEthereumContractCreate
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpecOperation.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiBaseContractCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumContractCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/CustomSpecAssert.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ApproveAllowanceSuite.java
Labels: Limechain

#13119 fix: add createTokenWithEthereumContractCallSignedWithSECP256K1 hapi…
  hedera-node/hedera-app/src/xtest/java/contract/AbstractContractXTest.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/TransactionModule.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/EitherOrVerificationStrategy.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleHederaNativeOperations.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/HandleSystemContractOperations.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/SpecificCryptoVerificationStrategy.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/scope/VerificationStrategy.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/ClassicCreatesCall.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HydratedEthTxData.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/infra/HevmTransactionFactory.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/TransactionModuleTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/ActiveContractVerificationStrategyTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/EitherOrVerificationStrategyTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleHederaNativeOperationsTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/HandleSystemContractOperationsTest.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/scope/SpecificCryptoVerificationStrategyTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/providers/ops/token/RandomTokenUnfreeze.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/AccountCreationDetails.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/meta/HapiGetTxnRecord.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/inventory/NewSpecKey.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/QueryModificationsOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/mod/SubmitModificationsOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/file/positive/SysDelSysUndelSpec.java
  hedera-node/test-clients/src/main/resource/contract/contracts/TestTokenCreateContract/TestTokenCreateContract.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/TestTokenCreateContract/TestTokenCreateContract.json
  hedera-node/test-clients/src/main/resource/contract/contracts/TestTokenCreateContract/TestTokenCreateContract.sol
Labels: Limechain

#12838 docs: add design document for HIP-904 token claim airdrop transaction
  hedera-node/docs/design/services/token-service/airdrops/token-claim-airdrop.md
Labels: Limechain, Design

#13175 fix: internal calls to system accounts
  hedera-node/docs/system-accounts-operations.md
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/FrameRunner.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/failure/CustomExceptionalHaltReason.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomMessageCallProcessor.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/hevm/HevmPropagatedCallFailure.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/processors/CustomMessageCallProcessorTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/HelloWorldEthereumSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/NonceSuite.java
  hedera-node/test-clients/src/main/java/module-info.java
  hedera-node/test-clients/src/main/resource/contract/contracts/MakeCalls/MakeCalls.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/MakeCalls/MakeCalls.json
  hedera-node/test-clients/src/main/resource/contract/contracts/MakeCalls/MakeCalls.sol
Labels: Limechain

#12118 fix: bugs found in Hedera > Ethereum conversion framework
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/HapiSpec.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/infrastructure/HapiSpecRegistry.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/queries/contract/HapiGetContractInfo.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnUtils.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/TxnVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiBaseCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiContractCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/transactions/contract/HapiEthereumContractCreate.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/CustomSpecAssert.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/UtilVerbs.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/records/SnapshotModeOp.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/Utils.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallLocalSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCreateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractDeleteSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractGetInfoSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractUpdateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/opcodes/CreateOperationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractKeysHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DelegatePrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ERCPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/LazyCreateThroughPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/SigningReqsSuite.java
Labels: Limechain

#13053 fix: Exchange rate precompile return error when called with value #13052
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/ExchangeRateSystemContract.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/PrngSystemContract.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/systemcontracts/ExchangeRateSystemContractTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/hapi/ContractCallSuite.java
  hedera-node/test-clients/src/main/resource/contract/contracts/ExchangeRatePrecompile/ExchangeRatePrecompile.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/ExchangeRatePrecompile/ExchangeRatePrecompile.json
  hedera-node/test-clients/src/main/resource/contract/contracts/ExchangeRatePrecompile/ExchangeRatePrecompile.sol
  hedera-node/test-clients/src/main/resource/contract/contracts/ExchangeRatePrecompile/SelfFunding.sol
Labels: Bug, Limechain

#12998 feat: Write tests for burn operations #12726
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractBurnHTSV2SecurityModelSuite.java
Labels: Test Development, Limechain

#13117 feat: Implement pureChecks and preHandle validation logic for TokenRejectHandler
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRejectHandler.java
Labels: Limechain

#12916 test: Add hapi tests for ECDSA hollow account alias as different types of keys
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/consensus/TopicUpdateSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/ContractMintHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/PauseUnpauseTokenAccountPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/WipeTokenAccountPrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenFeeScheduleUpdateSpecs.java
Labels: Test Development, Limechain

#13338 fix: 13336: :swirlds-virtualmap:timingSensitive sizeBasedFlushes is flaky
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipeline.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/DummyVirtualRoot.java
  platform-sdk/swirlds-virtualmap/src/test/java/com/swirlds/virtualmap/internal/pipeline/VirtualPipelineTests.java
Labels: Test Development, Platform Virtual Map, Platform Data Structures

#13062 feat: Write tests for kyc operations
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/GrantRevokeKycSuite.java
Labels: Test Development, Limechain

#13130 fix: 13128: Backport the fix for #12853 to release 0.50
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbDataSource.java
  platform-sdk/swirlds-jasperdb/src/main/java/com/swirlds/merkledb/MerkleDbStatisticsUpdater.java
  platform-sdk/swirlds-jasperdb/src/test/java/com/swirlds/merkledb/MerkleDbDataSourceTest.java
  platform-sdk/swirlds-jasperdb/src/testFixtures/java/com/swirlds/merkledb/test/fixtures/TestType.java
Labels: Platform Virtual Map, Platform Data Structures

#13369 fix: (cherry pick) TokenInfo single field update via contract calls
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/TokenUpdateHandlerTest.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/handlers/util/CryptoTokenHandlerTestBase.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/token/TokenUpdateSpecs.java
  hedera-node/test-clients/src/main/resource/contract/contracts/TokenInfoSingularUpdate/TokenInfoSingularUpdate.bin
  hedera-node/test-clients/src/main/resource/contract/contracts/TokenInfoSingularUpdate/TokenInfoSingularUpdate.json
  hedera-node/test-clients/src/main/resource/contract/contracts/TokenInfoSingularUpdate/TokenInfoSingularUpdate.sol
Labels: Limechain

#13422 fix: resolve release pipeline failures due to job dependencies
  .github/workflows/node-zxc-build-release-artifact.yaml
Labels: Bug, P0

#12833 feat: Direct call w/o value to system accounts [0.0.361-0.0.750] change output
  hedera-node/docs/system-accounts-operations.md
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/processors/CustomMessageCallProcessor.java
  hedera-node/hedera-smart-contract-service-impl/src/test/java/com/hedera/node/app/service/contract/impl/test/exec/processors/CustomMessageCallProcessorTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/evm/Evm46ValidationSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/traceability/TraceabilitySuite.java
Labels: Limechain

#12952 test: Write v2 security tests for token create operation
  hedera-node/hedera-app/src/main/java/com/hedera/node/app/workflows/handle/validation/AttributeValidatorImpl.java
  hedera-node/hedera-smart-contract-service-impl/src/main/java/com/hedera/node/app/service/contract/impl/exec/systemcontracts/hts/create/ClassicCreatesCall.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/CreatePrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/ethereum/EthereumSuite.java
Labels: Limechain

#12957 feat: Fee calculation for TokenReject functionality
  hedera-node/configuration/mainnet/upgrade/feeSchedules.json
  hedera-node/configuration/mainnet/upgrade/throttles.json
  hedera-node/configuration/testnet/upgrade/feeSchedules.json
  hedera-node/configuration/testnet/upgrade/throttles.json
  hedera-node/hapi-fees/src/main/resources/canonical-prices.json
  hedera-node/hedera-file-service-impl/src/main/resources/genesis/feeSchedules.json
  hedera-node/hedera-file-service-impl/src/main/resources/genesis/throttles-dev.json
  hedera-node/hedera-file-service-impl/src/main/resources/genesis/throttles.json
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/TokenRejectHandler.java
Labels: Limechain

#13016 feat: Write tests for freeze/unfreeze operations
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/FreezeUnfreezeTokenPrecompileSuite.java
Labels: Test Development, Limechain

#13169 feat: Write tests for dissociate operations #12724
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/DissociatePrecompileSuite.java
Labels: Test Development, Limechain

#13453 perf: Warm up fungible token relations
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoTransferHandler.java
Labels: Performance

#13526 perf: don't block heartbeats
  platform-sdk/swirlds-platform-core/src/main/java/com/swirlds/platform/wiring/PlatformWiring.java
Labels: Performance

#13041 feat: HIP-904 Introduce `unlimitedAutoAssociations` feature flag
  hedera-node/hedera-config/src/main/java/com/hedera/node/config/data/EntitiesConfig.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/BaseTokenHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/handlers/CryptoUpdateHandler.java
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/validators/CryptoCreateValidator.java
  hedera-node/hedera-token-service-impl/src/test/java/com/hedera/node/app/service/token/impl/test/validators/CryptoCreateValidatorTest.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/spec/utilops/FeatureFlags.java
Labels: Limechain

#13586 fix: 13584: Thread race between VirtualPipeline.hashCopy() and VirtualRootNode.computeHash()
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: Platform Virtual Map, Platform Data Structures

#13591 perf: HapiUtils.parsedIntOrZero() throws too many exceptions
  hapi/src/main/java/com/hedera/hapi/util/HapiUtils.java
Labels: Performance

#13467 fix: write v2 security model tests for token update HSCS operations
  hedera-node/hedera-token-service-impl/src/main/java/com/hedera/node/app/service/token/impl/util/TokenKey.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenExpiryInfoSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenInfoHTSSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileSuite.java
  hedera-node/test-clients/src/main/java/com/hedera/services/bdd/suites/contract/precompile/TokenUpdatePrecompileV1SecurityModelSuite.java
Labels: Test Development, Limechain

#13609 perf: cherry-pick: HapiUtils.parsedIntOrZero() throws too many exceptions
  hedera-node/hedera-app-spi/src/main/java/com/hedera/node/app/spi/HapiUtils.java
Labels: Performance

#13611 fix: 13610: Backport the fix for 13584 to 0.50
  platform-sdk/swirlds-virtualmap/src/main/java/com/swirlds/virtualmap/internal/merkle/VirtualRootNode.java
Labels: Platform Virtual Map, Platform Data Structures
